../src/def.svh
../src/AXI_define.svh
../src/top.sv
../src/WDT.sv
../src/alu.sv
../src/WDT_wrapper.sv
../src/AXI/AXI.sv
../src/branch_predictor.sv
../src/CPU.sv
../src/CPU_wrapper.sv
../src/CSR.sv
//../src/CHIP.v
../src/DM_cache.sv
../src/DM_tag_array_wrapper.sv
../src/DM_data_array_wrapper.sv
../src/DMA.sv
../src/DMA_wrapper.sv
../src/DRAM_FSM.sv
../src/DRAM_wrapper.sv
../src/easy_decoder.sv
../src/Forward.sv
../src/IM_cache.sv
../src/IM_tag_array_wrapper.sv
../src/IM_data_array_wrapper.sv
../src/ins_decoder.sv
../src/JB_Unit.sv
../src/LD_filter.sv
../src/mux0.sv
../src/mux1.sv
../src/mux11.sv
../src/mux12.sv
../src/mux2.sv
../src/mux3.sv
../src/mux4.sv
../src/mux5.sv
../src/mux6.sv
../src/mux7.sv
../src/mux8.sv
../src/mux9.sv
../src/mux_ad.sv
../src/mux_jb.sv
../src/PC_reg.sv
../src/reg1.sv
../src/reg2.sv
../src/reg3.sv
../src/reg4.sv
../src/reg_file.sv
../src/reg_f_file.sv
../src/reg_jb_pc.sv
../src/ROM_wrapper.sv
../src/SRAM_wrapper.sv
../src/async_CDC_4.sv
../src/async_CDC_1.sv
../src/async_CDC_16.sv
../src/ONE_CDC.sv
// ---- EPU: PE sparse-GEMM engine + AXI-S6 wrapper (trapezoid_pkg first) ----
../../rtl/trapezoid_pkg.sv
../../rtl/mfiu/mfiu.sv
../../rtl/dist/crossbar.sv
../../rtl/dist/reduction_tree_radix16.sv
../../rtl/pe/mac_unit.sv
../../rtl/pe/sram_128x32_1r1w.sv
../../rtl/pe/local_buffer_row.sv
../../rtl/pe/pe_row_tail.sv
../../rtl/pe/pe_mfiu_seq.sv
../../rtl/pe/pe_entry.sv
../../rtl/pe/pe_ab_buffer.sv
../../rtl/pe/pe_row.sv
../../rtl/pe/pe_array.sv
../../rtl/EPU_wrapper.sv
//usr/cad/CBDK/Executable_Package/Collaterals/IP/stdio/N16ADFP_StdIO/VERILOG/N16ADFP_StdIO.v