// Generated by CIRCT firtool-1.135.0
module Arbiter1_SimpleBusReqBundle(	// src/main/scala/chisel3/util/Arbiter.scala:149:7
  output        io_in_0_ready,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input         io_in_0_valid,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input  [31:0] io_in_0_bits_addr,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input  [86:0] io_in_0_bits_user,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input         io_out_ready,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  output        io_out_valid,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  output [31:0] io_out_bits_addr,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  output [86:0] io_out_bits_user	// src/main/scala/chisel3/util/Arbiter.scala:156:14
);

  assign io_in_0_ready = io_out_ready;	// src/main/scala/chisel3/util/Arbiter.scala:149:7
  assign io_out_valid = io_in_0_valid;	// src/main/scala/chisel3/util/Arbiter.scala:149:7
  assign io_out_bits_addr = io_in_0_bits_addr;	// src/main/scala/chisel3/util/Arbiter.scala:149:7
  assign io_out_bits_user = io_in_0_bits_user;	// src/main/scala/chisel3/util/Arbiter.scala:149:7
endmodule

