// Generated by CIRCT firtool-1.135.0
module Arbiter2_SimpleBusReqBundle(	// src/main/scala/chisel3/util/Arbiter.scala:149:7
  output        io_in_0_ready,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input         io_in_0_valid,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input  [31:0] io_in_0_bits_addr,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input  [3:0]  io_in_0_bits_cmd,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input  [7:0]  io_in_0_bits_wmask,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input  [63:0] io_in_0_bits_wdata,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  output        io_in_1_ready,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input         io_in_1_valid,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input  [31:0] io_in_1_bits_addr,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input  [3:0]  io_in_1_bits_cmd,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input  [7:0]  io_in_1_bits_wmask,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input  [63:0] io_in_1_bits_wdata,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input         io_out_ready,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  output        io_out_valid,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  output [31:0] io_out_bits_addr,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  output [3:0]  io_out_bits_cmd,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  output [7:0]  io_out_bits_wmask,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  output [63:0] io_out_bits_wdata	// src/main/scala/chisel3/util/Arbiter.scala:156:14
);

  assign io_in_0_ready = io_out_ready;	// src/main/scala/chisel3/util/Arbiter.scala:149:7
  assign io_in_1_ready = ~io_in_0_valid & io_out_ready;	// src/main/scala/chisel3/util/Arbiter.scala:45:78, :149:7, :169:19
  assign io_out_valid = io_in_0_valid | io_in_1_valid;	// src/main/scala/chisel3/util/Arbiter.scala:149:7, :170:31
  assign io_out_bits_addr = io_in_0_valid ? io_in_0_bits_addr : io_in_1_bits_addr;	// src/main/scala/chisel3/util/Arbiter.scala:149:7, :159:15, :161:26, :163:19
  assign io_out_bits_cmd = io_in_0_valid ? io_in_0_bits_cmd : io_in_1_bits_cmd;	// src/main/scala/chisel3/util/Arbiter.scala:149:7, :159:15, :161:26, :163:19
  assign io_out_bits_wmask = io_in_0_valid ? io_in_0_bits_wmask : io_in_1_bits_wmask;	// src/main/scala/chisel3/util/Arbiter.scala:149:7, :159:15, :161:26, :163:19
  assign io_out_bits_wdata = io_in_0_valid ? io_in_0_bits_wdata : io_in_1_bits_wdata;	// src/main/scala/chisel3/util/Arbiter.scala:149:7, :159:15, :161:26, :163:19
endmodule

