// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module AXI4UART(	// src/main/scala/device/AXI4UART.scala:26:7
  input         clock,	// src/main/scala/device/AXI4UART.scala:26:7
                reset,	// src/main/scala/device/AXI4UART.scala:26:7
  output        io_in_aw_ready,	// src/main/scala/device/AXI4Slave.scala:28:14
  input         io_in_aw_valid,	// src/main/scala/device/AXI4Slave.scala:28:14
  input  [31:0] io_in_aw_bits_addr,	// src/main/scala/device/AXI4Slave.scala:28:14
  output        io_in_w_ready,	// src/main/scala/device/AXI4Slave.scala:28:14
  input         io_in_w_valid,	// src/main/scala/device/AXI4Slave.scala:28:14
  input  [63:0] io_in_w_bits_data,	// src/main/scala/device/AXI4Slave.scala:28:14
  input  [7:0]  io_in_w_bits_strb,	// src/main/scala/device/AXI4Slave.scala:28:14
  input         io_in_b_ready,	// src/main/scala/device/AXI4Slave.scala:28:14
  output        io_in_b_valid,	// src/main/scala/device/AXI4Slave.scala:28:14
                io_in_ar_ready,	// src/main/scala/device/AXI4Slave.scala:28:14
  input         io_in_ar_valid,	// src/main/scala/device/AXI4Slave.scala:28:14
  input  [31:0] io_in_ar_bits_addr,	// src/main/scala/device/AXI4Slave.scala:28:14
  input         io_in_r_ready,	// src/main/scala/device/AXI4Slave.scala:28:14
  output        io_in_r_valid,	// src/main/scala/device/AXI4Slave.scala:28:14
  output [63:0] io_in_r_bits_data,	// src/main/scala/device/AXI4Slave.scala:28:14
  output        io_extra_out_valid,	// src/main/scala/device/AXI4Slave.scala:28:14
  output [7:0]  io_extra_out_ch,	// src/main/scala/device/AXI4Slave.scala:28:14
  output        io_extra_in_valid,	// src/main/scala/device/AXI4Slave.scala:28:14
  input  [7:0]  io_extra_in_ch	// src/main/scala/device/AXI4Slave.scala:28:14
);

  reg         io_in_r_valid_r;	// src/main/scala/utils/StopWatch.scala:24:20
  wire        _io_extra_in_valid_T_2 = io_in_r_ready & io_in_r_valid_r;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/utils/StopWatch.scala:24:20
  reg         r_busy;	// src/main/scala/utils/StopWatch.scala:24:20
  wire        io_in_ar_ready_0 = io_in_r_ready | ~r_busy;	// src/main/scala/device/AXI4Slave.scala:71:{29,32}, src/main/scala/utils/StopWatch.scala:24:20
  reg         ren_REG;	// src/main/scala/device/AXI4Slave.scala:73:17
  reg         w_busy;	// src/main/scala/utils/StopWatch.scala:24:20
  wire        io_in_w_ready_0 = io_in_aw_valid | w_busy;	// src/main/scala/device/AXI4Slave.scala:95:30, src/main/scala/utils/StopWatch.scala:24:20
  wire        _io_extra_out_valid_T_2 = io_in_w_ready_0 & io_in_w_valid;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/device/AXI4Slave.scala:95:30
  reg         io_in_b_valid_r;	// src/main/scala/utils/StopWatch.scala:24:20
  reg  [31:0] txfifo;	// src/main/scala/device/AXI4UART.scala:29:19
  reg  [31:0] stat;	// src/main/scala/device/AXI4UART.scala:30:21
  reg  [31:0] ctrl;	// src/main/scala/device/AXI4UART.scala:31:21
  always @(posedge clock) begin	// src/main/scala/device/AXI4UART.scala:26:7
    automatic logic [7:0]  _GEN = io_in_w_bits_strb >> io_in_aw_bits_addr[2:0];	// src/main/scala/device/AXI4UART.scala:45:{77,85}
    automatic logic [31:0] _GEN_0;	// src/main/scala/device/AXI4UART.scala:45:92
    _GEN_0 = {{8{_GEN[3]}}, {8{_GEN[2]}}, {8{_GEN[1]}}, {8{_GEN[0]}}};	// src/main/scala/device/AXI4UART.scala:45:{77,92}, src/main/scala/utils/BitUtils.scala:27:{29,45}
    if (reset) begin	// src/main/scala/device/AXI4UART.scala:26:7
      r_busy <= 1'h0;	// src/main/scala/utils/StopWatch.scala:24:20
      ren_REG <= 1'h0;	// src/main/scala/device/AXI4Slave.scala:73:17, src/main/scala/utils/StopWatch.scala:24:20
      io_in_r_valid_r <= 1'h0;	// src/main/scala/utils/StopWatch.scala:24:20
      w_busy <= 1'h0;	// src/main/scala/utils/StopWatch.scala:24:20
      io_in_b_valid_r <= 1'h0;	// src/main/scala/utils/StopWatch.scala:24:20
      stat <= 32'h1;	// src/main/scala/device/AXI4UART.scala:30:21
      ctrl <= 32'h0;	// src/main/scala/device/AXI4UART.scala:31:21
    end
    else begin	// src/main/scala/device/AXI4UART.scala:26:7
      automatic logic _io_in_r_valid_T = io_in_ar_ready_0 & io_in_ar_valid;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/device/AXI4Slave.scala:71:29
      automatic logic _io_in_b_valid_T_2;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      _io_in_b_valid_T_2 = io_in_b_ready & io_in_b_valid_r;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/utils/StopWatch.scala:24:20
      r_busy <= _io_in_r_valid_T | ~_io_extra_in_valid_T_2 & r_busy;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/utils/StopWatch.scala:24:20, :26:{19,23}, :27:{20,24}
      ren_REG <= _io_in_r_valid_T;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/device/AXI4Slave.scala:73:17
      io_in_r_valid_r <=
        ren_REG & (_io_in_r_valid_T | r_busy) | ~_io_extra_in_valid_T_2 & io_in_r_valid_r;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/device/AXI4Slave.scala:73:17, :74:{35,50}, src/main/scala/utils/StopWatch.scala:24:20, :26:{19,23}, :27:{20,24}
      w_busy <= ~w_busy & io_in_aw_valid | ~_io_in_b_valid_T_2 & w_busy;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/device/AXI4Slave.scala:94:18, src/main/scala/utils/StopWatch.scala:24:20, :26:{19,23}, :27:{20,24}
      io_in_b_valid_r <= _io_extra_out_valid_T_2 | ~_io_in_b_valid_T_2 & io_in_b_valid_r;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/utils/StopWatch.scala:24:20, :26:{19,23}, :27:{20,24}
      if (_io_extra_out_valid_T_2 & io_in_aw_bits_addr[3:0] == 4'h8)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/device/AXI4UART.scala:33:35, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:32:{32,41}
        stat <= io_in_w_bits_data[31:0] & _GEN_0 | stat & ~_GEN_0;	// src/main/scala/device/AXI4UART.scala:30:21, :45:{42,92}, src/main/scala/utils/BitUtils.scala:34:{14,26,37,39}
      if (_io_extra_out_valid_T_2 & io_in_aw_bits_addr[3:0] == 4'hC)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/device/AXI4UART.scala:33:35, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:32:{32,41}
        ctrl <= io_in_w_bits_data[31:0] & _GEN_0 | ctrl & ~_GEN_0;	// src/main/scala/device/AXI4UART.scala:31:21, :45:{42,92}, src/main/scala/utils/BitUtils.scala:34:{14,26,37,39}
    end
    if (_io_extra_out_valid_T_2 & io_in_aw_bits_addr[3:0] == 4'h4)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/device/AXI4UART.scala:33:{35,41}, src/main/scala/utils/RegMap.scala:32:{32,41}
      txfifo <= io_in_w_bits_data[31:0] & _GEN_0 | txfifo & ~_GEN_0;	// src/main/scala/device/AXI4UART.scala:29:19, :45:{42,92}, src/main/scala/utils/BitUtils.scala:34:{14,26,37,39}
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/device/AXI4UART.scala:26:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/device/AXI4UART.scala:26:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/device/AXI4UART.scala:26:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/device/AXI4UART.scala:26:7
      automatic logic [31:0] _RANDOM[0:4];	// src/main/scala/device/AXI4UART.scala:26:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/device/AXI4UART.scala:26:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/device/AXI4UART.scala:26:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/device/AXI4UART.scala:26:7
        for (logic [2:0] i = 3'h0; i < 3'h5; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/device/AXI4UART.scala:26:7
        end	// src/main/scala/device/AXI4UART.scala:26:7
        r_busy = _RANDOM[3'h0][0];	// src/main/scala/device/AXI4UART.scala:26:7, src/main/scala/utils/StopWatch.scala:24:20
        ren_REG = _RANDOM[3'h0][1];	// src/main/scala/device/AXI4Slave.scala:73:17, src/main/scala/device/AXI4UART.scala:26:7, src/main/scala/utils/StopWatch.scala:24:20
        io_in_r_valid_r = _RANDOM[3'h0][2];	// src/main/scala/device/AXI4UART.scala:26:7, src/main/scala/utils/StopWatch.scala:24:20
        w_busy = _RANDOM[3'h0][3];	// src/main/scala/device/AXI4UART.scala:26:7, src/main/scala/utils/StopWatch.scala:24:20
        io_in_b_valid_r = _RANDOM[3'h0][4];	// src/main/scala/device/AXI4UART.scala:26:7, src/main/scala/utils/StopWatch.scala:24:20
        txfifo = {_RANDOM[3'h1][31:5], _RANDOM[3'h2][4:0]};	// src/main/scala/device/AXI4UART.scala:26:7, :29:19
        stat = {_RANDOM[3'h2][31:5], _RANDOM[3'h3][4:0]};	// src/main/scala/device/AXI4UART.scala:26:7, :29:19, :30:21
        ctrl = {_RANDOM[3'h3][31:5], _RANDOM[3'h4][4:0]};	// src/main/scala/device/AXI4UART.scala:26:7, :30:21, :31:21
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/device/AXI4UART.scala:26:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/device/AXI4UART.scala:26:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_in_aw_ready = ~w_busy;	// src/main/scala/device/AXI4Slave.scala:94:18, src/main/scala/device/AXI4UART.scala:26:7, src/main/scala/utils/StopWatch.scala:24:20
  assign io_in_w_ready = io_in_w_ready_0;	// src/main/scala/device/AXI4Slave.scala:95:30, src/main/scala/device/AXI4UART.scala:26:7
  assign io_in_b_valid = io_in_b_valid_r;	// src/main/scala/device/AXI4UART.scala:26:7, src/main/scala/utils/StopWatch.scala:24:20
  assign io_in_ar_ready = io_in_ar_ready_0;	// src/main/scala/device/AXI4Slave.scala:71:29, src/main/scala/device/AXI4UART.scala:26:7
  assign io_in_r_valid = io_in_r_valid_r;	// src/main/scala/device/AXI4UART.scala:26:7, src/main/scala/utils/StopWatch.scala:24:20
  assign io_in_r_bits_data =
    {32'h0,
     {24'h0, (|(io_in_ar_bits_addr[3:0])) ? 8'h0 : io_extra_in_ch}
       | (io_in_ar_bits_addr[3:0] == 4'h4 ? txfifo : 32'h0)
       | (io_in_ar_bits_addr[3:0] == 4'h8 ? stat : 32'h0)
       | (io_in_ar_bits_addr[3:0] == 4'hC ? ctrl : 32'h0)};	// src/main/scala/device/AXI4UART.scala:26:7, :29:19, :30:21, :31:21, :33:41, :35:{34,40}, src/main/scala/utils/LookupTree.scala:24:{10,34}, src/main/scala/utils/RegMap.scala:30:11
  assign io_extra_out_valid = io_in_aw_bits_addr[3:0] == 4'h4 & _io_extra_out_valid_T_2;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/device/AXI4UART.scala:26:7, :33:{35,41,49}
  assign io_extra_out_ch = io_in_w_bits_data[7:0];	// src/main/scala/device/AXI4UART.scala:26:7, :34:40
  assign io_extra_in_valid = ~(|(io_in_ar_bits_addr[3:0])) & _io_extra_in_valid_T_2;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/device/AXI4UART.scala:26:7, :35:{34,40,48}
endmodule

