// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module AXI4RAM_1(	// src/main/scala/device/AXI4RAM.scala:26:7
  input         clock,	// src/main/scala/device/AXI4RAM.scala:26:7
                reset,	// src/main/scala/device/AXI4RAM.scala:26:7
  output        io_in_aw_ready,	// src/main/scala/device/AXI4Slave.scala:28:14
  input         io_in_aw_valid,	// src/main/scala/device/AXI4Slave.scala:28:14
  input  [31:0] io_in_aw_bits_addr,	// src/main/scala/device/AXI4Slave.scala:28:14
  output        io_in_w_ready,	// src/main/scala/device/AXI4Slave.scala:28:14
  input         io_in_w_valid,	// src/main/scala/device/AXI4Slave.scala:28:14
  input  [63:0] io_in_w_bits_data,	// src/main/scala/device/AXI4Slave.scala:28:14
  input  [7:0]  io_in_w_bits_strb,	// src/main/scala/device/AXI4Slave.scala:28:14
  input         io_in_b_ready,	// src/main/scala/device/AXI4Slave.scala:28:14
  output        io_in_b_valid,	// src/main/scala/device/AXI4Slave.scala:28:14
  input         io_in_ar_valid,	// src/main/scala/device/AXI4Slave.scala:28:14
  input  [31:0] io_in_ar_bits_addr,	// src/main/scala/device/AXI4Slave.scala:28:14
  output        io_in_r_valid,	// src/main/scala/device/AXI4Slave.scala:28:14
  output [63:0] io_in_r_bits_data	// src/main/scala/device/AXI4Slave.scala:28:14
);

  wire [63:0] _rdata_mem_ext_R0_data;	// src/main/scala/device/AXI4RAM.scala:47:18
  reg         r_busy;	// src/main/scala/utils/StopWatch.scala:24:20
  reg         ren_REG;	// src/main/scala/device/AXI4Slave.scala:73:17
  reg         io_in_r_valid_r;	// src/main/scala/utils/StopWatch.scala:24:20
  reg         w_busy;	// src/main/scala/utils/StopWatch.scala:24:20
  wire        io_in_w_ready_0 = io_in_aw_valid | w_busy;	// src/main/scala/device/AXI4Slave.scala:95:30, src/main/scala/utils/StopWatch.scala:24:20
  wire        _wen_T = io_in_w_ready_0 & io_in_w_valid;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/device/AXI4Slave.scala:95:30
  reg         io_in_b_valid_r;	// src/main/scala/utils/StopWatch.scala:24:20
  reg  [63:0] rdata;	// src/main/scala/device/AXI4RAM.scala:52:14
  always @(posedge clock) begin	// src/main/scala/device/AXI4RAM.scala:26:7
    if (reset) begin	// src/main/scala/device/AXI4RAM.scala:26:7
      r_busy <= 1'h0;	// src/main/scala/utils/StopWatch.scala:24:20
      ren_REG <= 1'h0;	// src/main/scala/device/AXI4Slave.scala:73:17
      io_in_r_valid_r <= 1'h0;	// src/main/scala/utils/StopWatch.scala:24:20
      w_busy <= 1'h0;	// src/main/scala/utils/StopWatch.scala:24:20
      io_in_b_valid_r <= 1'h0;	// src/main/scala/utils/StopWatch.scala:24:20
    end
    else begin	// src/main/scala/device/AXI4RAM.scala:26:7
      automatic logic _io_in_b_valid_T_2;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      _io_in_b_valid_T_2 = io_in_b_ready & io_in_b_valid_r;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/utils/StopWatch.scala:24:20
      r_busy <= io_in_ar_valid | ~io_in_r_valid_r & r_busy;	// src/main/scala/utils/StopWatch.scala:24:20, :26:{19,23}, :27:{20,24}
      ren_REG <= io_in_ar_valid;	// src/main/scala/device/AXI4Slave.scala:73:17
      io_in_r_valid_r <= ren_REG & (io_in_ar_valid | r_busy);	// src/main/scala/device/AXI4Slave.scala:73:17, :74:{35,50}, src/main/scala/utils/StopWatch.scala:24:20
      w_busy <= ~w_busy & io_in_aw_valid | ~_io_in_b_valid_T_2 & w_busy;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/device/AXI4Slave.scala:94:18, src/main/scala/utils/StopWatch.scala:24:20, :26:{19,23}, :27:{20,24}
      io_in_b_valid_r <= _wen_T | ~_io_in_b_valid_T_2 & io_in_b_valid_r;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/utils/StopWatch.scala:24:20, :26:{19,23}, :27:{20,24}
    end
    if (ren_REG)	// src/main/scala/device/AXI4Slave.scala:73:17
      rdata <= _rdata_mem_ext_R0_data;	// src/main/scala/device/AXI4RAM.scala:47:18, :52:14
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/device/AXI4RAM.scala:26:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/device/AXI4RAM.scala:26:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/device/AXI4RAM.scala:26:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/device/AXI4RAM.scala:26:7
      automatic logic [31:0] _RANDOM[0:2];	// src/main/scala/device/AXI4RAM.scala:26:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/device/AXI4RAM.scala:26:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/device/AXI4RAM.scala:26:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/device/AXI4RAM.scala:26:7
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/device/AXI4RAM.scala:26:7
        end	// src/main/scala/device/AXI4RAM.scala:26:7
        r_busy = _RANDOM[2'h0][0];	// src/main/scala/device/AXI4RAM.scala:26:7, src/main/scala/utils/StopWatch.scala:24:20
        ren_REG = _RANDOM[2'h0][1];	// src/main/scala/device/AXI4RAM.scala:26:7, src/main/scala/device/AXI4Slave.scala:73:17, src/main/scala/utils/StopWatch.scala:24:20
        io_in_r_valid_r = _RANDOM[2'h0][2];	// src/main/scala/device/AXI4RAM.scala:26:7, src/main/scala/utils/StopWatch.scala:24:20
        w_busy = _RANDOM[2'h0][3];	// src/main/scala/device/AXI4RAM.scala:26:7, src/main/scala/utils/StopWatch.scala:24:20
        io_in_b_valid_r = _RANDOM[2'h0][4];	// src/main/scala/device/AXI4RAM.scala:26:7, src/main/scala/utils/StopWatch.scala:24:20
        rdata = {_RANDOM[2'h0][31:5], _RANDOM[2'h1], _RANDOM[2'h2][4:0]};	// src/main/scala/device/AXI4RAM.scala:26:7, :52:14, src/main/scala/utils/StopWatch.scala:24:20
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/device/AXI4RAM.scala:26:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/device/AXI4RAM.scala:26:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  rdata_mem_60000x64 rdata_mem_ext (	// src/main/scala/device/AXI4RAM.scala:47:18
    .R0_addr (io_in_ar_bits_addr[18:3]),	// src/main/scala/device/AXI4RAM.scala:29:31
    .R0_en   (1'h1),	// src/main/scala/device/AXI4RAM.scala:26:7
    .R0_clk  (clock),
    .R0_data (_rdata_mem_ext_R0_data),
    .W0_addr (io_in_aw_bits_addr[18:3]),	// src/main/scala/device/AXI4RAM.scala:29:31
    .W0_en   (_wen_T & io_in_aw_bits_addr[18:3] < 16'hEA60),	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/device/AXI4RAM.scala:29:31, :30:32, :34:23
    .W0_clk  (clock),
    .W0_data (io_in_w_bits_data),
    .W0_mask (io_in_w_bits_strb)
  );	// src/main/scala/device/AXI4RAM.scala:47:18
  assign io_in_aw_ready = ~w_busy;	// src/main/scala/device/AXI4RAM.scala:26:7, src/main/scala/device/AXI4Slave.scala:94:18, src/main/scala/utils/StopWatch.scala:24:20
  assign io_in_w_ready = io_in_w_ready_0;	// src/main/scala/device/AXI4RAM.scala:26:7, src/main/scala/device/AXI4Slave.scala:95:30
  assign io_in_b_valid = io_in_b_valid_r;	// src/main/scala/device/AXI4RAM.scala:26:7, src/main/scala/utils/StopWatch.scala:24:20
  assign io_in_r_valid = io_in_r_valid_r;	// src/main/scala/device/AXI4RAM.scala:26:7, src/main/scala/utils/StopWatch.scala:24:20
  assign io_in_r_bits_data = rdata;	// src/main/scala/device/AXI4RAM.scala:26:7, :52:14
endmodule

