// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module AXI4MeipGen(	// src/main/scala/sim/MeipGen.scala:30:7
  input         clock,	// src/main/scala/sim/MeipGen.scala:30:7
                reset,	// src/main/scala/sim/MeipGen.scala:30:7
  output        io_in_aw_ready,	// src/main/scala/device/AXI4Slave.scala:28:14
  input         io_in_aw_valid,	// src/main/scala/device/AXI4Slave.scala:28:14
  input  [31:0] io_in_aw_bits_addr,	// src/main/scala/device/AXI4Slave.scala:28:14
  output        io_in_w_ready,	// src/main/scala/device/AXI4Slave.scala:28:14
  input         io_in_w_valid,	// src/main/scala/device/AXI4Slave.scala:28:14
  input  [63:0] io_in_w_bits_data,	// src/main/scala/device/AXI4Slave.scala:28:14
  input  [7:0]  io_in_w_bits_strb,	// src/main/scala/device/AXI4Slave.scala:28:14
  input         io_in_b_ready,	// src/main/scala/device/AXI4Slave.scala:28:14
  output        io_in_b_valid,	// src/main/scala/device/AXI4Slave.scala:28:14
                io_in_ar_ready,	// src/main/scala/device/AXI4Slave.scala:28:14
  input         io_in_ar_valid,	// src/main/scala/device/AXI4Slave.scala:28:14
                io_in_r_ready,	// src/main/scala/device/AXI4Slave.scala:28:14
  output        io_in_r_valid,	// src/main/scala/device/AXI4Slave.scala:28:14
  output [63:0] io_in_r_bits_data,	// src/main/scala/device/AXI4Slave.scala:28:14
  output        io_extra_meip	// src/main/scala/device/AXI4Slave.scala:28:14
);

  reg  r_busy;	// src/main/scala/utils/StopWatch.scala:24:20
  wire io_in_ar_ready_0 = io_in_r_ready | ~r_busy;	// src/main/scala/device/AXI4Slave.scala:71:{29,32}, src/main/scala/utils/StopWatch.scala:24:20
  reg  ren_REG;	// src/main/scala/device/AXI4Slave.scala:73:17
  reg  io_in_r_valid_r;	// src/main/scala/utils/StopWatch.scala:24:20
  reg  w_busy;	// src/main/scala/utils/StopWatch.scala:24:20
  wire io_in_w_ready_0 = io_in_aw_valid | w_busy;	// src/main/scala/device/AXI4Slave.scala:95:30, src/main/scala/utils/StopWatch.scala:24:20
  reg  io_in_b_valid_r;	// src/main/scala/utils/StopWatch.scala:24:20
  reg  meip;	// src/main/scala/sim/MeipGen.scala:31:21
  always @(posedge clock) begin	// src/main/scala/sim/MeipGen.scala:30:7
    if (reset) begin	// src/main/scala/sim/MeipGen.scala:30:7
      r_busy <= 1'h0;	// src/main/scala/sim/MeipGen.scala:30:7, src/main/scala/utils/StopWatch.scala:24:20
      ren_REG <= 1'h0;	// src/main/scala/device/AXI4Slave.scala:73:17, src/main/scala/sim/MeipGen.scala:30:7
      io_in_r_valid_r <= 1'h0;	// src/main/scala/sim/MeipGen.scala:30:7, src/main/scala/utils/StopWatch.scala:24:20
      w_busy <= 1'h0;	// src/main/scala/sim/MeipGen.scala:30:7, src/main/scala/utils/StopWatch.scala:24:20
      io_in_b_valid_r <= 1'h0;	// src/main/scala/sim/MeipGen.scala:30:7, src/main/scala/utils/StopWatch.scala:24:20
      meip <= 1'h0;	// src/main/scala/sim/MeipGen.scala:30:7, :31:21
    end
    else begin	// src/main/scala/sim/MeipGen.scala:30:7
      automatic logic _io_in_r_valid_T = io_in_ar_ready_0 & io_in_ar_valid;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/device/AXI4Slave.scala:71:29
      automatic logic _io_in_r_valid_T_3;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      automatic logic _io_in_b_valid_T_2;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      automatic logic _io_in_b_valid_T_1 = io_in_w_ready_0 & io_in_w_valid;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/device/AXI4Slave.scala:95:30
      _io_in_r_valid_T_3 = io_in_r_ready & io_in_r_valid_r;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/utils/StopWatch.scala:24:20
      _io_in_b_valid_T_2 = io_in_b_ready & io_in_b_valid_r;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/utils/StopWatch.scala:24:20
      r_busy <= _io_in_r_valid_T | ~_io_in_r_valid_T_3 & r_busy;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/utils/StopWatch.scala:24:20, :26:{19,23}, :27:{20,24}
      ren_REG <= _io_in_r_valid_T;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/device/AXI4Slave.scala:73:17
      io_in_r_valid_r <=
        ren_REG & (_io_in_r_valid_T | r_busy) | ~_io_in_r_valid_T_3 & io_in_r_valid_r;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/device/AXI4Slave.scala:73:17, :74:{35,50}, src/main/scala/utils/StopWatch.scala:24:20, :26:{19,23}, :27:{20,24}
      w_busy <= ~w_busy & io_in_aw_valid | ~_io_in_b_valid_T_2 & w_busy;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/device/AXI4Slave.scala:94:18, src/main/scala/utils/StopWatch.scala:24:20, :26:{19,23}, :27:{20,24}
      io_in_b_valid_r <= _io_in_b_valid_T_1 | ~_io_in_b_valid_T_2 & io_in_b_valid_r;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/utils/StopWatch.scala:24:20, :26:{19,23}, :27:{20,24}
      if (_io_in_b_valid_T_1 & io_in_aw_bits_addr[3:0] == 4'h0)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/sim/MeipGen.scala:37:35, src/main/scala/utils/RegMap.scala:32:{32,41}
        meip <=
          io_in_w_bits_data[0] & io_in_w_bits_strb[0] | meip & ~(io_in_w_bits_strb[0]);	// src/main/scala/sim/MeipGen.scala:31:21, :39:48, src/main/scala/utils/BitUtils.scala:27:29, :34:{14,26,37,39}
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/sim/MeipGen.scala:30:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/sim/MeipGen.scala:30:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/sim/MeipGen.scala:30:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/sim/MeipGen.scala:30:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/sim/MeipGen.scala:30:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/sim/MeipGen.scala:30:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/sim/MeipGen.scala:30:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/sim/MeipGen.scala:30:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/sim/MeipGen.scala:30:7
        r_busy = _RANDOM[/*Zero width*/ 1'b0][0];	// src/main/scala/sim/MeipGen.scala:30:7, src/main/scala/utils/StopWatch.scala:24:20
        ren_REG = _RANDOM[/*Zero width*/ 1'b0][1];	// src/main/scala/device/AXI4Slave.scala:73:17, src/main/scala/sim/MeipGen.scala:30:7, src/main/scala/utils/StopWatch.scala:24:20
        io_in_r_valid_r = _RANDOM[/*Zero width*/ 1'b0][2];	// src/main/scala/sim/MeipGen.scala:30:7, src/main/scala/utils/StopWatch.scala:24:20
        w_busy = _RANDOM[/*Zero width*/ 1'b0][3];	// src/main/scala/sim/MeipGen.scala:30:7, src/main/scala/utils/StopWatch.scala:24:20
        io_in_b_valid_r = _RANDOM[/*Zero width*/ 1'b0][4];	// src/main/scala/sim/MeipGen.scala:30:7, src/main/scala/utils/StopWatch.scala:24:20
        meip = _RANDOM[/*Zero width*/ 1'b0][5];	// src/main/scala/sim/MeipGen.scala:30:7, :31:21, src/main/scala/utils/StopWatch.scala:24:20
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/sim/MeipGen.scala:30:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/sim/MeipGen.scala:30:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_in_aw_ready = ~w_busy;	// src/main/scala/device/AXI4Slave.scala:94:18, src/main/scala/sim/MeipGen.scala:30:7, src/main/scala/utils/StopWatch.scala:24:20
  assign io_in_w_ready = io_in_w_ready_0;	// src/main/scala/device/AXI4Slave.scala:95:30, src/main/scala/sim/MeipGen.scala:30:7
  assign io_in_b_valid = io_in_b_valid_r;	// src/main/scala/sim/MeipGen.scala:30:7, src/main/scala/utils/StopWatch.scala:24:20
  assign io_in_ar_ready = io_in_ar_ready_0;	// src/main/scala/device/AXI4Slave.scala:71:29, src/main/scala/sim/MeipGen.scala:30:7
  assign io_in_r_valid = io_in_r_valid_r;	// src/main/scala/sim/MeipGen.scala:30:7, src/main/scala/utils/StopWatch.scala:24:20
  assign io_in_r_bits_data = {63'h0, meip};	// src/main/scala/sim/MeipGen.scala:30:7, :31:21, src/main/scala/utils/RegMap.scala:30:11
  assign io_extra_meip = meip;	// src/main/scala/sim/MeipGen.scala:30:7, :31:21
endmodule

