// Generated by CIRCT firtool-1.135.0
module CacheStage1(	// src/main/scala/nutcore/mem/Cache.scala:126:14
  output        io_in_ready,	// src/main/scala/nutcore/mem/Cache.scala:133:14
  input         io_in_valid,	// src/main/scala/nutcore/mem/Cache.scala:133:14
  input  [31:0] io_in_bits_addr,	// src/main/scala/nutcore/mem/Cache.scala:133:14
  input  [86:0] io_in_bits_user,	// src/main/scala/nutcore/mem/Cache.scala:133:14
  input         io_out_ready,	// src/main/scala/nutcore/mem/Cache.scala:133:14
  output        io_out_valid,	// src/main/scala/nutcore/mem/Cache.scala:133:14
  output [31:0] io_out_bits_req_addr,	// src/main/scala/nutcore/mem/Cache.scala:133:14
  output [86:0] io_out_bits_req_user,	// src/main/scala/nutcore/mem/Cache.scala:133:14
  input         io_metaReadBus_req_ready,	// src/main/scala/nutcore/mem/Cache.scala:133:14
  output        io_metaReadBus_req_valid,	// src/main/scala/nutcore/mem/Cache.scala:133:14
  output [6:0]  io_metaReadBus_req_bits_setIdx,	// src/main/scala/nutcore/mem/Cache.scala:133:14
  input         io_dataReadBus_req_ready,	// src/main/scala/nutcore/mem/Cache.scala:133:14
  output        io_dataReadBus_req_valid,	// src/main/scala/nutcore/mem/Cache.scala:133:14
  output [9:0]  io_dataReadBus_req_bits_setIdx	// src/main/scala/nutcore/mem/Cache.scala:133:14
);

  wire readBusValid = io_in_valid & io_out_ready;	// src/main/scala/nutcore/mem/Cache.scala:139:34
  wire io_out_valid_0 = io_in_valid & io_metaReadBus_req_ready & io_dataReadBus_req_ready;	// src/main/scala/nutcore/mem/Cache.scala:144:{31,59}
  assign io_in_ready =
    (~io_in_valid | io_out_ready & io_out_valid_0) & io_metaReadBus_req_ready
    & io_dataReadBus_req_ready;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/nutcore/mem/Cache.scala:126:14, :144:{31,59}, :145:{19,32,48,76}
  assign io_out_valid = io_out_valid_0;	// src/main/scala/nutcore/mem/Cache.scala:126:14, :144:{31,59}
  assign io_out_bits_req_addr = io_in_bits_addr;	// src/main/scala/nutcore/mem/Cache.scala:126:14
  assign io_out_bits_req_user = io_in_bits_user;	// src/main/scala/nutcore/mem/Cache.scala:126:14
  assign io_metaReadBus_req_valid = readBusValid;	// src/main/scala/nutcore/mem/Cache.scala:126:14, :139:34
  assign io_metaReadBus_req_bits_setIdx = io_in_bits_addr[12:6];	// src/main/scala/nutcore/mem/Cache.scala:77:45, :126:14
  assign io_dataReadBus_req_valid = readBusValid;	// src/main/scala/nutcore/mem/Cache.scala:126:14, :139:34
  assign io_dataReadBus_req_bits_setIdx = io_in_bits_addr[12:3];	// src/main/scala/nutcore/mem/Cache.scala:77:45, :78:35, :126:14
endmodule

