// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module DelayReg(	// difftest/src/main/scala/util/Delayer.scala:27:15
  input         clock,	// difftest/src/main/scala/util/Delayer.scala:27:15
                reset,	// difftest/src/main/scala/util/Delayer.scala:27:15
                i_valid,	// difftest/src/main/scala/util/Delayer.scala:23:13
                i_skip,	// difftest/src/main/scala/util/Delayer.scala:23:13
                i_isRVC,	// difftest/src/main/scala/util/Delayer.scala:23:13
                i_rfwen,	// difftest/src/main/scala/util/Delayer.scala:23:13
                i_fpwen,	// difftest/src/main/scala/util/Delayer.scala:23:13
                i_vecwen,	// difftest/src/main/scala/util/Delayer.scala:23:13
                i_v0wen,	// difftest/src/main/scala/util/Delayer.scala:23:13
  input  [4:0]  i_wpdest,	// difftest/src/main/scala/util/Delayer.scala:23:13
  input  [7:0]  i_wdest,	// difftest/src/main/scala/util/Delayer.scala:23:13
  input  [4:0]  i_otherwpdest_0,	// difftest/src/main/scala/util/Delayer.scala:23:13
                i_otherwpdest_1,	// difftest/src/main/scala/util/Delayer.scala:23:13
                i_otherwpdest_2,	// difftest/src/main/scala/util/Delayer.scala:23:13
                i_otherwpdest_3,	// difftest/src/main/scala/util/Delayer.scala:23:13
                i_otherwpdest_4,	// difftest/src/main/scala/util/Delayer.scala:23:13
                i_otherwpdest_5,	// difftest/src/main/scala/util/Delayer.scala:23:13
                i_otherwpdest_6,	// difftest/src/main/scala/util/Delayer.scala:23:13
                i_otherwpdest_7,	// difftest/src/main/scala/util/Delayer.scala:23:13
                i_otherwpdest_8,	// difftest/src/main/scala/util/Delayer.scala:23:13
                i_otherwpdest_9,	// difftest/src/main/scala/util/Delayer.scala:23:13
                i_otherwpdest_10,	// difftest/src/main/scala/util/Delayer.scala:23:13
                i_otherwpdest_11,	// difftest/src/main/scala/util/Delayer.scala:23:13
                i_otherwpdest_12,	// difftest/src/main/scala/util/Delayer.scala:23:13
                i_otherwpdest_13,	// difftest/src/main/scala/util/Delayer.scala:23:13
                i_otherwpdest_14,	// difftest/src/main/scala/util/Delayer.scala:23:13
                i_otherwpdest_15,	// difftest/src/main/scala/util/Delayer.scala:23:13
  input  [63:0] i_pc,	// difftest/src/main/scala/util/Delayer.scala:23:13
  input  [31:0] i_instr,	// difftest/src/main/scala/util/Delayer.scala:23:13
  input  [9:0]  i_robIdx,	// difftest/src/main/scala/util/Delayer.scala:23:13
  input  [6:0]  i_lqIdx,	// difftest/src/main/scala/util/Delayer.scala:23:13
                i_sqIdx,	// difftest/src/main/scala/util/Delayer.scala:23:13
  input         i_isLoad,	// difftest/src/main/scala/util/Delayer.scala:23:13
                i_isStore,	// difftest/src/main/scala/util/Delayer.scala:23:13
  input  [7:0]  i_nFused,	// difftest/src/main/scala/util/Delayer.scala:23:13
                i_special,	// difftest/src/main/scala/util/Delayer.scala:23:13
                i_coreid,	// difftest/src/main/scala/util/Delayer.scala:23:13
                i_index,	// difftest/src/main/scala/util/Delayer.scala:23:13
  output        o_valid,	// difftest/src/main/scala/util/Delayer.scala:24:13
                o_skip,	// difftest/src/main/scala/util/Delayer.scala:24:13
                o_isRVC,	// difftest/src/main/scala/util/Delayer.scala:24:13
                o_rfwen,	// difftest/src/main/scala/util/Delayer.scala:24:13
                o_fpwen,	// difftest/src/main/scala/util/Delayer.scala:24:13
                o_vecwen,	// difftest/src/main/scala/util/Delayer.scala:24:13
                o_v0wen,	// difftest/src/main/scala/util/Delayer.scala:24:13
  output [4:0]  o_wpdest,	// difftest/src/main/scala/util/Delayer.scala:24:13
  output [7:0]  o_wdest,	// difftest/src/main/scala/util/Delayer.scala:24:13
  output [4:0]  o_otherwpdest_0,	// difftest/src/main/scala/util/Delayer.scala:24:13
                o_otherwpdest_1,	// difftest/src/main/scala/util/Delayer.scala:24:13
                o_otherwpdest_2,	// difftest/src/main/scala/util/Delayer.scala:24:13
                o_otherwpdest_3,	// difftest/src/main/scala/util/Delayer.scala:24:13
                o_otherwpdest_4,	// difftest/src/main/scala/util/Delayer.scala:24:13
                o_otherwpdest_5,	// difftest/src/main/scala/util/Delayer.scala:24:13
                o_otherwpdest_6,	// difftest/src/main/scala/util/Delayer.scala:24:13
                o_otherwpdest_7,	// difftest/src/main/scala/util/Delayer.scala:24:13
                o_otherwpdest_8,	// difftest/src/main/scala/util/Delayer.scala:24:13
                o_otherwpdest_9,	// difftest/src/main/scala/util/Delayer.scala:24:13
                o_otherwpdest_10,	// difftest/src/main/scala/util/Delayer.scala:24:13
                o_otherwpdest_11,	// difftest/src/main/scala/util/Delayer.scala:24:13
                o_otherwpdest_12,	// difftest/src/main/scala/util/Delayer.scala:24:13
                o_otherwpdest_13,	// difftest/src/main/scala/util/Delayer.scala:24:13
                o_otherwpdest_14,	// difftest/src/main/scala/util/Delayer.scala:24:13
                o_otherwpdest_15,	// difftest/src/main/scala/util/Delayer.scala:24:13
  output [63:0] o_pc,	// difftest/src/main/scala/util/Delayer.scala:24:13
  output [31:0] o_instr,	// difftest/src/main/scala/util/Delayer.scala:24:13
  output [9:0]  o_robIdx,	// difftest/src/main/scala/util/Delayer.scala:24:13
  output [6:0]  o_lqIdx,	// difftest/src/main/scala/util/Delayer.scala:24:13
                o_sqIdx,	// difftest/src/main/scala/util/Delayer.scala:24:13
  output        o_isLoad,	// difftest/src/main/scala/util/Delayer.scala:24:13
                o_isStore,	// difftest/src/main/scala/util/Delayer.scala:24:13
  output [7:0]  o_nFused,	// difftest/src/main/scala/util/Delayer.scala:24:13
                o_special,	// difftest/src/main/scala/util/Delayer.scala:24:13
                o_coreid,	// difftest/src/main/scala/util/Delayer.scala:24:13
                o_index	// difftest/src/main/scala/util/Delayer.scala:24:13
);

  reg        REG_valid;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg        REG_skip;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg        REG_isRVC;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg        REG_rfwen;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg        REG_fpwen;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg        REG_vecwen;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg        REG_v0wen;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg [4:0]  REG_wpdest;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg [7:0]  REG_wdest;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg [4:0]  REG_otherwpdest_0;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg [4:0]  REG_otherwpdest_1;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg [4:0]  REG_otherwpdest_2;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg [4:0]  REG_otherwpdest_3;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg [4:0]  REG_otherwpdest_4;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg [4:0]  REG_otherwpdest_5;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg [4:0]  REG_otherwpdest_6;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg [4:0]  REG_otherwpdest_7;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg [4:0]  REG_otherwpdest_8;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg [4:0]  REG_otherwpdest_9;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg [4:0]  REG_otherwpdest_10;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg [4:0]  REG_otherwpdest_11;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg [4:0]  REG_otherwpdest_12;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg [4:0]  REG_otherwpdest_13;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg [4:0]  REG_otherwpdest_14;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg [4:0]  REG_otherwpdest_15;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg [63:0] REG_pc;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg [31:0] REG_instr;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg [9:0]  REG_robIdx;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg [6:0]  REG_lqIdx;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg [6:0]  REG_sqIdx;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg        REG_isLoad;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg        REG_isStore;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg [7:0]  REG_nFused;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg [7:0]  REG_special;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg [7:0]  REG_coreid;	// difftest/src/main/scala/util/Delayer.scala:30:16
  reg [7:0]  REG_index;	// difftest/src/main/scala/util/Delayer.scala:30:16
  always @(posedge clock) begin	// difftest/src/main/scala/util/Delayer.scala:27:15
    if (reset) begin	// difftest/src/main/scala/util/Delayer.scala:27:15
      REG_valid <= 1'h0;	// <stdin>:25962:28, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_skip <= 1'h0;	// <stdin>:25962:28, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_isRVC <= 1'h0;	// <stdin>:25962:28, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_rfwen <= 1'h0;	// <stdin>:25962:28, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_fpwen <= 1'h0;	// <stdin>:25962:28, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_vecwen <= 1'h0;	// <stdin>:25962:28, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_v0wen <= 1'h0;	// <stdin>:25962:28, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_wpdest <= 5'h0;	// <stdin>:25969:35, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_wdest <= 8'h0;	// <stdin>:25958:26, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_otherwpdest_0 <= 5'h0;	// <stdin>:25969:35, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_otherwpdest_1 <= 5'h0;	// <stdin>:25969:35, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_otherwpdest_2 <= 5'h0;	// <stdin>:25969:35, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_otherwpdest_3 <= 5'h0;	// <stdin>:25969:35, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_otherwpdest_4 <= 5'h0;	// <stdin>:25969:35, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_otherwpdest_5 <= 5'h0;	// <stdin>:25969:35, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_otherwpdest_6 <= 5'h0;	// <stdin>:25969:35, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_otherwpdest_7 <= 5'h0;	// <stdin>:25969:35, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_otherwpdest_8 <= 5'h0;	// <stdin>:25969:35, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_otherwpdest_9 <= 5'h0;	// <stdin>:25969:35, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_otherwpdest_10 <= 5'h0;	// <stdin>:25969:35, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_otherwpdest_11 <= 5'h0;	// <stdin>:25969:35, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_otherwpdest_12 <= 5'h0;	// <stdin>:25969:35, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_otherwpdest_13 <= 5'h0;	// <stdin>:25969:35, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_otherwpdest_14 <= 5'h0;	// <stdin>:25969:35, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_otherwpdest_15 <= 5'h0;	// <stdin>:25969:35, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_pc <= 64'h0;	// <stdin>:25968:23, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_instr <= 32'h0;	// <stdin>:25967:26, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_robIdx <= 10'h0;	// <stdin>:25966:27, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_lqIdx <= 7'h0;	// <stdin>:25964:26, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_sqIdx <= 7'h0;	// <stdin>:25964:26, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_isLoad <= 1'h0;	// <stdin>:25962:28, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_isStore <= 1'h0;	// <stdin>:25962:28, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_nFused <= 8'h0;	// <stdin>:25958:26, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_special <= 8'h0;	// <stdin>:25958:26, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_coreid <= 8'h0;	// <stdin>:25958:26, difftest/src/main/scala/util/Delayer.scala:30:16
      REG_index <= 8'h0;	// <stdin>:25958:26, difftest/src/main/scala/util/Delayer.scala:30:16
    end
    else begin	// difftest/src/main/scala/util/Delayer.scala:27:15
      REG_valid <= i_valid;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_skip <= i_skip;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_isRVC <= i_isRVC;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_rfwen <= i_rfwen;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_fpwen <= i_fpwen;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_vecwen <= i_vecwen;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_v0wen <= i_v0wen;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_wpdest <= i_wpdest;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_wdest <= i_wdest;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_otherwpdest_0 <= i_otherwpdest_0;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_otherwpdest_1 <= i_otherwpdest_1;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_otherwpdest_2 <= i_otherwpdest_2;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_otherwpdest_3 <= i_otherwpdest_3;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_otherwpdest_4 <= i_otherwpdest_4;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_otherwpdest_5 <= i_otherwpdest_5;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_otherwpdest_6 <= i_otherwpdest_6;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_otherwpdest_7 <= i_otherwpdest_7;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_otherwpdest_8 <= i_otherwpdest_8;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_otherwpdest_9 <= i_otherwpdest_9;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_otherwpdest_10 <= i_otherwpdest_10;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_otherwpdest_11 <= i_otherwpdest_11;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_otherwpdest_12 <= i_otherwpdest_12;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_otherwpdest_13 <= i_otherwpdest_13;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_otherwpdest_14 <= i_otherwpdest_14;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_otherwpdest_15 <= i_otherwpdest_15;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_pc <= i_pc;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_instr <= i_instr;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_robIdx <= i_robIdx;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_lqIdx <= i_lqIdx;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_sqIdx <= i_sqIdx;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_isLoad <= i_isLoad;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_isStore <= i_isStore;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_nFused <= i_nFused;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_special <= i_special;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_coreid <= i_coreid;	// difftest/src/main/scala/util/Delayer.scala:30:16
      REG_index <= i_index;	// difftest/src/main/scala/util/Delayer.scala:30:16
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// difftest/src/main/scala/util/Delayer.scala:27:15
    `ifdef FIRRTL_BEFORE_INITIAL	// difftest/src/main/scala/util/Delayer.scala:27:15
      `FIRRTL_BEFORE_INITIAL	// difftest/src/main/scala/util/Delayer.scala:27:15
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// difftest/src/main/scala/util/Delayer.scala:27:15
      automatic logic [31:0] _RANDOM[0:7];	// difftest/src/main/scala/util/Delayer.scala:27:15
      `ifdef INIT_RANDOM_PROLOG_	// difftest/src/main/scala/util/Delayer.scala:27:15
        `INIT_RANDOM_PROLOG_	// difftest/src/main/scala/util/Delayer.scala:27:15
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// difftest/src/main/scala/util/Delayer.scala:27:15
        for (logic [3:0] i = 4'h0; i < 4'h8; i += 4'h1) begin
          _RANDOM[i[2:0]] = `RANDOM;	// difftest/src/main/scala/util/Delayer.scala:27:15
        end	// difftest/src/main/scala/util/Delayer.scala:27:15
        REG_valid = _RANDOM[3'h0][0];	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_skip = _RANDOM[3'h0][1];	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_isRVC = _RANDOM[3'h0][2];	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_rfwen = _RANDOM[3'h0][3];	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_fpwen = _RANDOM[3'h0][4];	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_vecwen = _RANDOM[3'h0][5];	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_v0wen = _RANDOM[3'h0][6];	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_wpdest = _RANDOM[3'h0][11:7];	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_wdest = _RANDOM[3'h0][19:12];	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_otherwpdest_0 = _RANDOM[3'h0][24:20];	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_otherwpdest_1 = _RANDOM[3'h0][29:25];	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_otherwpdest_2 = {_RANDOM[3'h0][31:30], _RANDOM[3'h1][2:0]};	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_otherwpdest_3 = _RANDOM[3'h1][7:3];	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_otherwpdest_4 = _RANDOM[3'h1][12:8];	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_otherwpdest_5 = _RANDOM[3'h1][17:13];	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_otherwpdest_6 = _RANDOM[3'h1][22:18];	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_otherwpdest_7 = _RANDOM[3'h1][27:23];	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_otherwpdest_8 = {_RANDOM[3'h1][31:28], _RANDOM[3'h2][0]};	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_otherwpdest_9 = _RANDOM[3'h2][5:1];	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_otherwpdest_10 = _RANDOM[3'h2][10:6];	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_otherwpdest_11 = _RANDOM[3'h2][15:11];	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_otherwpdest_12 = _RANDOM[3'h2][20:16];	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_otherwpdest_13 = _RANDOM[3'h2][25:21];	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_otherwpdest_14 = _RANDOM[3'h2][30:26];	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_otherwpdest_15 = {_RANDOM[3'h2][31], _RANDOM[3'h3][3:0]};	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_pc = {_RANDOM[3'h3][31:4], _RANDOM[3'h4], _RANDOM[3'h5][3:0]};	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_instr = {_RANDOM[3'h5][31:4], _RANDOM[3'h6][3:0]};	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_robIdx = _RANDOM[3'h6][13:4];	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_lqIdx = _RANDOM[3'h6][20:14];	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_sqIdx = _RANDOM[3'h6][27:21];	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_isLoad = _RANDOM[3'h6][28];	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_isStore = _RANDOM[3'h6][29];	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_nFused = {_RANDOM[3'h6][31:30], _RANDOM[3'h7][5:0]};	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_special = _RANDOM[3'h7][13:6];	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_coreid = _RANDOM[3'h7][21:14];	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
        REG_index = _RANDOM[3'h7][29:22];	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// difftest/src/main/scala/util/Delayer.scala:27:15
      `FIRRTL_AFTER_INITIAL	// difftest/src/main/scala/util/Delayer.scala:27:15
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign o_valid = REG_valid;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_skip = REG_skip;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_isRVC = REG_isRVC;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_rfwen = REG_rfwen;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_fpwen = REG_fpwen;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_vecwen = REG_vecwen;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_v0wen = REG_v0wen;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_wpdest = REG_wpdest;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_wdest = REG_wdest;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_otherwpdest_0 = REG_otherwpdest_0;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_otherwpdest_1 = REG_otherwpdest_1;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_otherwpdest_2 = REG_otherwpdest_2;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_otherwpdest_3 = REG_otherwpdest_3;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_otherwpdest_4 = REG_otherwpdest_4;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_otherwpdest_5 = REG_otherwpdest_5;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_otherwpdest_6 = REG_otherwpdest_6;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_otherwpdest_7 = REG_otherwpdest_7;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_otherwpdest_8 = REG_otherwpdest_8;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_otherwpdest_9 = REG_otherwpdest_9;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_otherwpdest_10 = REG_otherwpdest_10;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_otherwpdest_11 = REG_otherwpdest_11;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_otherwpdest_12 = REG_otherwpdest_12;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_otherwpdest_13 = REG_otherwpdest_13;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_otherwpdest_14 = REG_otherwpdest_14;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_otherwpdest_15 = REG_otherwpdest_15;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_pc = REG_pc;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_instr = REG_instr;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_robIdx = REG_robIdx;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_lqIdx = REG_lqIdx;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_sqIdx = REG_sqIdx;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_isLoad = REG_isLoad;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_isStore = REG_isStore;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_nFused = REG_nFused;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_special = REG_special;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_coreid = REG_coreid;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
  assign o_index = REG_index;	// difftest/src/main/scala/util/Delayer.scala:27:15, :30:16
endmodule

