// Generated by CIRCT firtool-1.135.0
module DummyDPICWrapper_TrapEvent(	// difftest/src/main/scala/DPIC.scala:342:15
  input        clock,	// difftest/src/main/scala/DPIC.scala:342:15
               reset,	// difftest/src/main/scala/DPIC.scala:342:15
               io_bits_hasTrap,	// difftest/src/main/scala/DPIC.scala:345:14
  input [63:0] io_bits_cycleCnt,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_instrCnt,	// difftest/src/main/scala/DPIC.scala:345:14
  input        io_bits_hasWFI,	// difftest/src/main/scala/DPIC.scala:345:14
  input [63:0] io_bits_code,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_pc,	// difftest/src/main/scala/DPIC.scala:345:14
  input [7:0]  io_bits_coreid	// difftest/src/main/scala/DPIC.scala:345:14
);

  DiffExtTrapEvent dpic (	// difftest/src/main/scala/DPIC.scala:346:20
    .clock       (clock),
    .enable      (~reset),	// difftest/src/main/scala/DPIC.scala:348:48
    .io_hasTrap  (io_bits_hasTrap),
    .io_cycleCnt (io_bits_cycleCnt),
    .io_instrCnt (io_bits_instrCnt),
    .io_hasWFI   (io_bits_hasWFI),
    .io_code     (io_bits_code),
    .io_pc       (io_bits_pc),
    .io_coreid   (io_bits_coreid)
  );	// difftest/src/main/scala/DPIC.scala:346:20
endmodule

