// Generated by CIRCT firtool-1.135.0
module DummyDPICWrapper_ArchIntRegState(	// difftest/src/main/scala/DPIC.scala:342:15
  input        clock,	// difftest/src/main/scala/DPIC.scala:342:15
               reset,	// difftest/src/main/scala/DPIC.scala:342:15
               io_valid,	// difftest/src/main/scala/DPIC.scala:345:14
  input [63:0] io_bits_value_0,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_value_1,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_value_2,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_value_3,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_value_4,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_value_5,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_value_6,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_value_7,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_value_8,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_value_9,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_value_10,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_value_11,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_value_12,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_value_13,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_value_14,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_value_15,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_value_16,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_value_17,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_value_18,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_value_19,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_value_20,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_value_21,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_value_22,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_value_23,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_value_24,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_value_25,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_value_26,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_value_27,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_value_28,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_value_29,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_value_30,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_value_31,	// difftest/src/main/scala/DPIC.scala:345:14
  input [7:0]  io_bits_coreid	// difftest/src/main/scala/DPIC.scala:345:14
);

  DiffExtArchIntRegState dpic (	// difftest/src/main/scala/DPIC.scala:346:20
    .clock       (clock),
    .enable      (io_valid & ~reset),	// difftest/src/main/scala/DPIC.scala:348:{45,48}
    .io_value_0  (io_bits_value_0),
    .io_value_1  (io_bits_value_1),
    .io_value_2  (io_bits_value_2),
    .io_value_3  (io_bits_value_3),
    .io_value_4  (io_bits_value_4),
    .io_value_5  (io_bits_value_5),
    .io_value_6  (io_bits_value_6),
    .io_value_7  (io_bits_value_7),
    .io_value_8  (io_bits_value_8),
    .io_value_9  (io_bits_value_9),
    .io_value_10 (io_bits_value_10),
    .io_value_11 (io_bits_value_11),
    .io_value_12 (io_bits_value_12),
    .io_value_13 (io_bits_value_13),
    .io_value_14 (io_bits_value_14),
    .io_value_15 (io_bits_value_15),
    .io_value_16 (io_bits_value_16),
    .io_value_17 (io_bits_value_17),
    .io_value_18 (io_bits_value_18),
    .io_value_19 (io_bits_value_19),
    .io_value_20 (io_bits_value_20),
    .io_value_21 (io_bits_value_21),
    .io_value_22 (io_bits_value_22),
    .io_value_23 (io_bits_value_23),
    .io_value_24 (io_bits_value_24),
    .io_value_25 (io_bits_value_25),
    .io_value_26 (io_bits_value_26),
    .io_value_27 (io_bits_value_27),
    .io_value_28 (io_bits_value_28),
    .io_value_29 (io_bits_value_29),
    .io_value_30 (io_bits_value_30),
    .io_value_31 (io_bits_value_31),
    .io_coreid   (io_bits_coreid)
  );	// difftest/src/main/scala/DPIC.scala:346:20
endmodule

