// Generated by CIRCT firtool-1.135.0
module DummyDPICWrapper_CSRState(	// difftest/src/main/scala/DPIC.scala:342:15
  input        clock,	// difftest/src/main/scala/DPIC.scala:342:15
               reset,	// difftest/src/main/scala/DPIC.scala:342:15
               io_valid,	// difftest/src/main/scala/DPIC.scala:345:14
  input [63:0] io_bits_privilegeMode,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_mstatus,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_sstatus,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_mepc,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_sepc,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_mtval,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_stval,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_mtvec,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_stvec,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_mcause,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_scause,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_satp,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_mip,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_mie,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_mscratch,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_sscratch,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_mideleg,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_medeleg,	// difftest/src/main/scala/DPIC.scala:345:14
  input [7:0]  io_bits_coreid	// difftest/src/main/scala/DPIC.scala:345:14
);

  DiffExtCSRState dpic (	// difftest/src/main/scala/DPIC.scala:346:20
    .clock            (clock),
    .enable           (io_valid & ~reset),	// difftest/src/main/scala/DPIC.scala:348:{45,48}
    .io_privilegeMode (io_bits_privilegeMode),
    .io_mstatus       (io_bits_mstatus),
    .io_sstatus       (io_bits_sstatus),
    .io_mepc          (io_bits_mepc),
    .io_sepc          (io_bits_sepc),
    .io_mtval         (io_bits_mtval),
    .io_stval         (io_bits_stval),
    .io_mtvec         (io_bits_mtvec),
    .io_stvec         (io_bits_stvec),
    .io_mcause        (io_bits_mcause),
    .io_scause        (io_bits_scause),
    .io_satp          (io_bits_satp),
    .io_mip           (io_bits_mip),
    .io_mie           (io_bits_mie),
    .io_mscratch      (io_bits_mscratch),
    .io_sscratch      (io_bits_sscratch),
    .io_mideleg       (io_bits_mideleg),
    .io_medeleg       (io_bits_medeleg),
    .io_coreid        (io_bits_coreid)
  );	// difftest/src/main/scala/DPIC.scala:346:20
endmodule

