// Generated by CIRCT firtool-1.135.0
module DummyDPICWrapper_CommitData(	// difftest/src/main/scala/DPIC.scala:342:15
  input        clock,	// difftest/src/main/scala/DPIC.scala:342:15
               reset,	// difftest/src/main/scala/DPIC.scala:342:15
               io_valid,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_valid,	// difftest/src/main/scala/DPIC.scala:345:14
  input [63:0] io_bits_data,	// difftest/src/main/scala/DPIC.scala:345:14
  input [7:0]  io_bits_coreid,	// difftest/src/main/scala/DPIC.scala:345:14
               io_bits_index	// difftest/src/main/scala/DPIC.scala:345:14
);

  DiffExtCommitData dpic (	// difftest/src/main/scala/DPIC.scala:346:20
    .clock     (clock),
    .enable    (io_valid & ~reset),	// difftest/src/main/scala/DPIC.scala:348:{45,48}
    .io_valid  (io_bits_valid),
    .io_data   (io_bits_data),
    .io_coreid (io_bits_coreid),
    .io_index  (io_bits_index)
  );	// difftest/src/main/scala/DPIC.scala:346:20
endmodule

