// Generated by CIRCT firtool-1.135.0
module EmbeddedTLBEmpty_1(	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:404:7
  output        io_in_ready,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:405:14
  input         io_in_valid,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:405:14
  input  [31:0] io_in_bits_addr,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:405:14
  input  [3:0]  io_in_bits_cmd,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:405:14
  input  [7:0]  io_in_bits_wmask,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:405:14
  input  [63:0] io_in_bits_wdata,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:405:14
  input         io_out_ready,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:405:14
  output        io_out_valid,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:405:14
  output [31:0] io_out_bits_addr,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:405:14
  output [3:0]  io_out_bits_cmd,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:405:14
  output [7:0]  io_out_bits_wmask,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:405:14
  output [63:0] io_out_bits_wdata	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:405:14
);

  assign io_in_ready = io_out_ready;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:404:7
  assign io_out_valid = io_in_valid;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:404:7
  assign io_out_bits_addr = io_in_bits_addr;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:404:7
  assign io_out_bits_cmd = io_in_bits_cmd;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:404:7
  assign io_out_bits_wmask = io_in_bits_wmask;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:404:7
  assign io_out_bits_wdata = io_in_bits_wdata;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:404:7
endmodule

