// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module GatewayEndpoint(	// difftest/src/main/scala/Gateway.scala:233:7
  input           clock,	// difftest/src/main/scala/Gateway.scala:233:7
                  reset,	// difftest/src/main/scala/Gateway.scala:233:7
  input  [3908:0] in,	// difftest/src/main/scala/Gateway.scala:234:14
  output          step	// difftest/src/main/scala/Gateway.scala:274:16
);

  wire        _validated_module_out_5_valid;	// difftest/src/main/scala/Validate.scala:26:24
  wire        _validated_module_out_5_bits_valid;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_5_bits_data;	// difftest/src/main/scala/Validate.scala:26:24
  wire [7:0]  _validated_module_out_5_bits_coreid;	// difftest/src/main/scala/Validate.scala:26:24
  wire [7:0]  _validated_module_out_5_bits_index;	// difftest/src/main/scala/Validate.scala:26:24
  wire        _validated_module_out_4_valid;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_4_bits_value_0;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_4_bits_value_1;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_4_bits_value_2;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_4_bits_value_3;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_4_bits_value_4;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_4_bits_value_5;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_4_bits_value_6;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_4_bits_value_7;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_4_bits_value_8;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_4_bits_value_9;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_4_bits_value_10;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_4_bits_value_11;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_4_bits_value_12;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_4_bits_value_13;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_4_bits_value_14;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_4_bits_value_15;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_4_bits_value_16;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_4_bits_value_17;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_4_bits_value_18;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_4_bits_value_19;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_4_bits_value_20;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_4_bits_value_21;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_4_bits_value_22;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_4_bits_value_23;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_4_bits_value_24;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_4_bits_value_25;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_4_bits_value_26;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_4_bits_value_27;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_4_bits_value_28;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_4_bits_value_29;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_4_bits_value_30;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_4_bits_value_31;	// difftest/src/main/scala/Validate.scala:26:24
  wire [7:0]  _validated_module_out_4_bits_coreid;	// difftest/src/main/scala/Validate.scala:26:24
  wire        _validated_module_out_3_valid;	// difftest/src/main/scala/Validate.scala:26:24
  wire        _validated_module_out_3_bits_valid;	// difftest/src/main/scala/Validate.scala:26:24
  wire        _validated_module_out_3_bits_skip;	// difftest/src/main/scala/Validate.scala:26:24
  wire        _validated_module_out_3_bits_isRVC;	// difftest/src/main/scala/Validate.scala:26:24
  wire        _validated_module_out_3_bits_rfwen;	// difftest/src/main/scala/Validate.scala:26:24
  wire        _validated_module_out_3_bits_fpwen;	// difftest/src/main/scala/Validate.scala:26:24
  wire        _validated_module_out_3_bits_vecwen;	// difftest/src/main/scala/Validate.scala:26:24
  wire        _validated_module_out_3_bits_v0wen;	// difftest/src/main/scala/Validate.scala:26:24
  wire [4:0]  _validated_module_out_3_bits_wpdest;	// difftest/src/main/scala/Validate.scala:26:24
  wire [7:0]  _validated_module_out_3_bits_wdest;	// difftest/src/main/scala/Validate.scala:26:24
  wire [4:0]  _validated_module_out_3_bits_otherwpdest_0;	// difftest/src/main/scala/Validate.scala:26:24
  wire [4:0]  _validated_module_out_3_bits_otherwpdest_1;	// difftest/src/main/scala/Validate.scala:26:24
  wire [4:0]  _validated_module_out_3_bits_otherwpdest_2;	// difftest/src/main/scala/Validate.scala:26:24
  wire [4:0]  _validated_module_out_3_bits_otherwpdest_3;	// difftest/src/main/scala/Validate.scala:26:24
  wire [4:0]  _validated_module_out_3_bits_otherwpdest_4;	// difftest/src/main/scala/Validate.scala:26:24
  wire [4:0]  _validated_module_out_3_bits_otherwpdest_5;	// difftest/src/main/scala/Validate.scala:26:24
  wire [4:0]  _validated_module_out_3_bits_otherwpdest_6;	// difftest/src/main/scala/Validate.scala:26:24
  wire [4:0]  _validated_module_out_3_bits_otherwpdest_7;	// difftest/src/main/scala/Validate.scala:26:24
  wire [4:0]  _validated_module_out_3_bits_otherwpdest_8;	// difftest/src/main/scala/Validate.scala:26:24
  wire [4:0]  _validated_module_out_3_bits_otherwpdest_9;	// difftest/src/main/scala/Validate.scala:26:24
  wire [4:0]  _validated_module_out_3_bits_otherwpdest_10;	// difftest/src/main/scala/Validate.scala:26:24
  wire [4:0]  _validated_module_out_3_bits_otherwpdest_11;	// difftest/src/main/scala/Validate.scala:26:24
  wire [4:0]  _validated_module_out_3_bits_otherwpdest_12;	// difftest/src/main/scala/Validate.scala:26:24
  wire [4:0]  _validated_module_out_3_bits_otherwpdest_13;	// difftest/src/main/scala/Validate.scala:26:24
  wire [4:0]  _validated_module_out_3_bits_otherwpdest_14;	// difftest/src/main/scala/Validate.scala:26:24
  wire [4:0]  _validated_module_out_3_bits_otherwpdest_15;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_3_bits_pc;	// difftest/src/main/scala/Validate.scala:26:24
  wire [31:0] _validated_module_out_3_bits_instr;	// difftest/src/main/scala/Validate.scala:26:24
  wire [9:0]  _validated_module_out_3_bits_robIdx;	// difftest/src/main/scala/Validate.scala:26:24
  wire [6:0]  _validated_module_out_3_bits_lqIdx;	// difftest/src/main/scala/Validate.scala:26:24
  wire [6:0]  _validated_module_out_3_bits_sqIdx;	// difftest/src/main/scala/Validate.scala:26:24
  wire        _validated_module_out_3_bits_isLoad;	// difftest/src/main/scala/Validate.scala:26:24
  wire        _validated_module_out_3_bits_isStore;	// difftest/src/main/scala/Validate.scala:26:24
  wire [7:0]  _validated_module_out_3_bits_nFused;	// difftest/src/main/scala/Validate.scala:26:24
  wire [7:0]  _validated_module_out_3_bits_special;	// difftest/src/main/scala/Validate.scala:26:24
  wire [7:0]  _validated_module_out_3_bits_coreid;	// difftest/src/main/scala/Validate.scala:26:24
  wire [7:0]  _validated_module_out_3_bits_index;	// difftest/src/main/scala/Validate.scala:26:24
  wire        _validated_module_out_2_bits_hasTrap;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_2_bits_cycleCnt;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_2_bits_instrCnt;	// difftest/src/main/scala/Validate.scala:26:24
  wire        _validated_module_out_2_bits_hasWFI;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_2_bits_code;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_2_bits_pc;	// difftest/src/main/scala/Validate.scala:26:24
  wire [7:0]  _validated_module_out_2_bits_coreid;	// difftest/src/main/scala/Validate.scala:26:24
  wire        _validated_module_out_1_valid;	// difftest/src/main/scala/Validate.scala:26:24
  wire        _validated_module_out_1_bits_valid;	// difftest/src/main/scala/Validate.scala:26:24
  wire [31:0] _validated_module_out_1_bits_interrupt;	// difftest/src/main/scala/Validate.scala:26:24
  wire [31:0] _validated_module_out_1_bits_exception;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_1_bits_exceptionPC;	// difftest/src/main/scala/Validate.scala:26:24
  wire [31:0] _validated_module_out_1_bits_exceptionInst;	// difftest/src/main/scala/Validate.scala:26:24
  wire        _validated_module_out_1_bits_hasNMI;	// difftest/src/main/scala/Validate.scala:26:24
  wire        _validated_module_out_1_bits_virtualInterruptIsHvictlInject;	// difftest/src/main/scala/Validate.scala:26:24
  wire        _validated_module_out_1_bits_irToHS;	// difftest/src/main/scala/Validate.scala:26:24
  wire        _validated_module_out_1_bits_irToVS;	// difftest/src/main/scala/Validate.scala:26:24
  wire [7:0]  _validated_module_out_1_bits_coreid;	// difftest/src/main/scala/Validate.scala:26:24
  wire        _validated_module_out_0_valid;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_0_bits_privilegeMode;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_0_bits_mstatus;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_0_bits_sstatus;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_0_bits_mepc;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_0_bits_sepc;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_0_bits_mtval;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_0_bits_stval;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_0_bits_mtvec;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_0_bits_stvec;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_0_bits_mcause;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_0_bits_scause;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_0_bits_satp;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_0_bits_mip;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_0_bits_mie;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_0_bits_mscratch;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_0_bits_sscratch;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_0_bits_mideleg;	// difftest/src/main/scala/Validate.scala:26:24
  wire [63:0] _validated_module_out_0_bits_medeleg;	// difftest/src/main/scala/Validate.scala:26:24
  wire [7:0]  _validated_module_out_0_bits_coreid;	// difftest/src/main/scala/Validate.scala:26:24
  wire        _preprocessed_module_out_5_valid;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_5_data;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [7:0]  _preprocessed_module_out_5_coreid;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [7:0]  _preprocessed_module_out_5_index;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_4_value_0;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_4_value_1;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_4_value_2;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_4_value_3;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_4_value_4;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_4_value_5;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_4_value_6;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_4_value_7;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_4_value_8;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_4_value_9;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_4_value_10;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_4_value_11;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_4_value_12;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_4_value_13;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_4_value_14;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_4_value_15;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_4_value_16;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_4_value_17;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_4_value_18;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_4_value_19;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_4_value_20;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_4_value_21;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_4_value_22;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_4_value_23;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_4_value_24;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_4_value_25;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_4_value_26;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_4_value_27;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_4_value_28;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_4_value_29;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_4_value_30;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_4_value_31;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [7:0]  _preprocessed_module_out_4_coreid;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire        _preprocessed_module_out_3_valid;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire        _preprocessed_module_out_3_skip;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire        _preprocessed_module_out_3_isRVC;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire        _preprocessed_module_out_3_rfwen;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire        _preprocessed_module_out_3_fpwen;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire        _preprocessed_module_out_3_vecwen;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire        _preprocessed_module_out_3_v0wen;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [4:0]  _preprocessed_module_out_3_wpdest;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [7:0]  _preprocessed_module_out_3_wdest;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [4:0]  _preprocessed_module_out_3_otherwpdest_0;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [4:0]  _preprocessed_module_out_3_otherwpdest_1;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [4:0]  _preprocessed_module_out_3_otherwpdest_2;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [4:0]  _preprocessed_module_out_3_otherwpdest_3;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [4:0]  _preprocessed_module_out_3_otherwpdest_4;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [4:0]  _preprocessed_module_out_3_otherwpdest_5;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [4:0]  _preprocessed_module_out_3_otherwpdest_6;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [4:0]  _preprocessed_module_out_3_otherwpdest_7;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [4:0]  _preprocessed_module_out_3_otherwpdest_8;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [4:0]  _preprocessed_module_out_3_otherwpdest_9;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [4:0]  _preprocessed_module_out_3_otherwpdest_10;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [4:0]  _preprocessed_module_out_3_otherwpdest_11;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [4:0]  _preprocessed_module_out_3_otherwpdest_12;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [4:0]  _preprocessed_module_out_3_otherwpdest_13;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [4:0]  _preprocessed_module_out_3_otherwpdest_14;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [4:0]  _preprocessed_module_out_3_otherwpdest_15;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_3_pc;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [31:0] _preprocessed_module_out_3_instr;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [9:0]  _preprocessed_module_out_3_robIdx;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [6:0]  _preprocessed_module_out_3_lqIdx;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [6:0]  _preprocessed_module_out_3_sqIdx;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire        _preprocessed_module_out_3_isLoad;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire        _preprocessed_module_out_3_isStore;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [7:0]  _preprocessed_module_out_3_nFused;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [7:0]  _preprocessed_module_out_3_special;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [7:0]  _preprocessed_module_out_3_coreid;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [7:0]  _preprocessed_module_out_3_index;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire        _preprocessed_module_out_2_hasTrap;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_2_cycleCnt;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_2_instrCnt;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire        _preprocessed_module_out_2_hasWFI;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_2_code;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_2_pc;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [7:0]  _preprocessed_module_out_2_coreid;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire        _preprocessed_module_out_1_valid;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [31:0] _preprocessed_module_out_1_interrupt;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [31:0] _preprocessed_module_out_1_exception;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_1_exceptionPC;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [31:0] _preprocessed_module_out_1_exceptionInst;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire        _preprocessed_module_out_1_hasNMI;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire        _preprocessed_module_out_1_virtualInterruptIsHvictlInject;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire        _preprocessed_module_out_1_irToHS;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire        _preprocessed_module_out_1_irToVS;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [7:0]  _preprocessed_module_out_1_coreid;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_0_privilegeMode;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_0_mstatus;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_0_sstatus;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_0_mepc;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_0_sepc;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_0_mtval;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_0_stval;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_0_mtvec;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_0_stvec;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_0_mcause;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_0_scause;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_0_satp;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_0_mip;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_0_mie;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_0_mscratch;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_0_sscratch;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_0_mideleg;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [63:0] _preprocessed_module_out_0_medeleg;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire [7:0]  _preprocessed_module_out_0_coreid;	// difftest/src/main/scala/Preprocess.scala:26:24
  wire        _bundle_delayed_delayer_o_valid;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire        _bundle_delayed_delayer_o_skip;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire        _bundle_delayed_delayer_o_isRVC;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire        _bundle_delayed_delayer_o_rfwen;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire        _bundle_delayed_delayer_o_fpwen;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire        _bundle_delayed_delayer_o_vecwen;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire        _bundle_delayed_delayer_o_v0wen;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire [4:0]  _bundle_delayed_delayer_o_wpdest;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire [7:0]  _bundle_delayed_delayer_o_wdest;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire [4:0]  _bundle_delayed_delayer_o_otherwpdest_0;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire [4:0]  _bundle_delayed_delayer_o_otherwpdest_1;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire [4:0]  _bundle_delayed_delayer_o_otherwpdest_2;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire [4:0]  _bundle_delayed_delayer_o_otherwpdest_3;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire [4:0]  _bundle_delayed_delayer_o_otherwpdest_4;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire [4:0]  _bundle_delayed_delayer_o_otherwpdest_5;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire [4:0]  _bundle_delayed_delayer_o_otherwpdest_6;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire [4:0]  _bundle_delayed_delayer_o_otherwpdest_7;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire [4:0]  _bundle_delayed_delayer_o_otherwpdest_8;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire [4:0]  _bundle_delayed_delayer_o_otherwpdest_9;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire [4:0]  _bundle_delayed_delayer_o_otherwpdest_10;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire [4:0]  _bundle_delayed_delayer_o_otherwpdest_11;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire [4:0]  _bundle_delayed_delayer_o_otherwpdest_12;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire [4:0]  _bundle_delayed_delayer_o_otherwpdest_13;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire [4:0]  _bundle_delayed_delayer_o_otherwpdest_14;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire [4:0]  _bundle_delayed_delayer_o_otherwpdest_15;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire [63:0] _bundle_delayed_delayer_o_pc;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire [31:0] _bundle_delayed_delayer_o_instr;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire [9:0]  _bundle_delayed_delayer_o_robIdx;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire [6:0]  _bundle_delayed_delayer_o_lqIdx;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire [6:0]  _bundle_delayed_delayer_o_sqIdx;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire        _bundle_delayed_delayer_o_isLoad;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire        _bundle_delayed_delayer_o_isStore;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire [7:0]  _bundle_delayed_delayer_o_nFused;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire [7:0]  _bundle_delayed_delayer_o_special;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire [7:0]  _bundle_delayed_delayer_o_coreid;	// difftest/src/main/scala/util/Delayer.scala:54:15
  wire [7:0]  _bundle_delayed_delayer_o_index;	// difftest/src/main/scala/util/Delayer.scala:54:15
  reg         step_REG;	// difftest/src/main/scala/Gateway.scala:290:20
  always @(posedge clock) begin	// difftest/src/main/scala/Gateway.scala:233:7
    if (reset)	// difftest/src/main/scala/Gateway.scala:233:7
      step_REG <= 1'h0;	// difftest/src/main/scala/Gateway.scala:233:7, :290:20
    else	// difftest/src/main/scala/Gateway.scala:233:7
      step_REG <= 1'h1;	// difftest/src/main/scala/Gateway.scala:233:7, :290:20
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// difftest/src/main/scala/Gateway.scala:233:7
    `ifdef FIRRTL_BEFORE_INITIAL	// difftest/src/main/scala/Gateway.scala:233:7
      `FIRRTL_BEFORE_INITIAL	// difftest/src/main/scala/Gateway.scala:233:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// difftest/src/main/scala/Gateway.scala:233:7
      automatic logic [31:0] _RANDOM[0:0];	// difftest/src/main/scala/Gateway.scala:233:7
      `ifdef INIT_RANDOM_PROLOG_	// difftest/src/main/scala/Gateway.scala:233:7
        `INIT_RANDOM_PROLOG_	// difftest/src/main/scala/Gateway.scala:233:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// difftest/src/main/scala/Gateway.scala:233:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// difftest/src/main/scala/Gateway.scala:233:7
        step_REG = _RANDOM[/*Zero width*/ 1'b0][0];	// difftest/src/main/scala/Gateway.scala:233:7, :290:20
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// difftest/src/main/scala/Gateway.scala:233:7
      `FIRRTL_AFTER_INITIAL	// difftest/src/main/scala/Gateway.scala:233:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  DelayReg bundle_delayed_delayer (	// difftest/src/main/scala/util/Delayer.scala:54:15
    .clock            (clock),
    .reset            (reset),
    .i_valid          (in[3908]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_skip           (in[3907]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_isRVC          (in[3906]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_rfwen          (in[3905]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_fpwen          (in[3904]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_vecwen         (in[3903]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_v0wen          (in[3902]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_wpdest         (in[3901:3897]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_wdest          (in[3896:3889]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_otherwpdest_0  (in[3813:3809]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_otherwpdest_1  (in[3818:3814]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_otherwpdest_2  (in[3823:3819]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_otherwpdest_3  (in[3828:3824]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_otherwpdest_4  (in[3833:3829]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_otherwpdest_5  (in[3838:3834]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_otherwpdest_6  (in[3843:3839]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_otherwpdest_7  (in[3848:3844]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_otherwpdest_8  (in[3853:3849]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_otherwpdest_9  (in[3858:3854]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_otherwpdest_10 (in[3863:3859]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_otherwpdest_11 (in[3868:3864]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_otherwpdest_12 (in[3873:3869]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_otherwpdest_13 (in[3878:3874]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_otherwpdest_14 (in[3883:3879]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_otherwpdest_15 (in[3888:3884]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_pc             (in[3808:3745]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_instr          (in[3744:3713]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_robIdx         (in[3712:3703]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_lqIdx          (in[3702:3696]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_sqIdx          (in[3695:3689]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_isLoad         (in[3688]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_isStore        (in[3687]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_nFused         (in[3686:3679]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_special        (in[3678:3671]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_coreid         (in[3670:3663]),	// difftest/src/main/scala/Gateway.scala:235:30
    .i_index          (in[3662:3655]),	// difftest/src/main/scala/Gateway.scala:235:30
    .o_valid          (_bundle_delayed_delayer_o_valid),
    .o_skip           (_bundle_delayed_delayer_o_skip),
    .o_isRVC          (_bundle_delayed_delayer_o_isRVC),
    .o_rfwen          (_bundle_delayed_delayer_o_rfwen),
    .o_fpwen          (_bundle_delayed_delayer_o_fpwen),
    .o_vecwen         (_bundle_delayed_delayer_o_vecwen),
    .o_v0wen          (_bundle_delayed_delayer_o_v0wen),
    .o_wpdest         (_bundle_delayed_delayer_o_wpdest),
    .o_wdest          (_bundle_delayed_delayer_o_wdest),
    .o_otherwpdest_0  (_bundle_delayed_delayer_o_otherwpdest_0),
    .o_otherwpdest_1  (_bundle_delayed_delayer_o_otherwpdest_1),
    .o_otherwpdest_2  (_bundle_delayed_delayer_o_otherwpdest_2),
    .o_otherwpdest_3  (_bundle_delayed_delayer_o_otherwpdest_3),
    .o_otherwpdest_4  (_bundle_delayed_delayer_o_otherwpdest_4),
    .o_otherwpdest_5  (_bundle_delayed_delayer_o_otherwpdest_5),
    .o_otherwpdest_6  (_bundle_delayed_delayer_o_otherwpdest_6),
    .o_otherwpdest_7  (_bundle_delayed_delayer_o_otherwpdest_7),
    .o_otherwpdest_8  (_bundle_delayed_delayer_o_otherwpdest_8),
    .o_otherwpdest_9  (_bundle_delayed_delayer_o_otherwpdest_9),
    .o_otherwpdest_10 (_bundle_delayed_delayer_o_otherwpdest_10),
    .o_otherwpdest_11 (_bundle_delayed_delayer_o_otherwpdest_11),
    .o_otherwpdest_12 (_bundle_delayed_delayer_o_otherwpdest_12),
    .o_otherwpdest_13 (_bundle_delayed_delayer_o_otherwpdest_13),
    .o_otherwpdest_14 (_bundle_delayed_delayer_o_otherwpdest_14),
    .o_otherwpdest_15 (_bundle_delayed_delayer_o_otherwpdest_15),
    .o_pc             (_bundle_delayed_delayer_o_pc),
    .o_instr          (_bundle_delayed_delayer_o_instr),
    .o_robIdx         (_bundle_delayed_delayer_o_robIdx),
    .o_lqIdx          (_bundle_delayed_delayer_o_lqIdx),
    .o_sqIdx          (_bundle_delayed_delayer_o_sqIdx),
    .o_isLoad         (_bundle_delayed_delayer_o_isLoad),
    .o_isStore        (_bundle_delayed_delayer_o_isStore),
    .o_nFused         (_bundle_delayed_delayer_o_nFused),
    .o_special        (_bundle_delayed_delayer_o_special),
    .o_coreid         (_bundle_delayed_delayer_o_coreid),
    .o_index          (_bundle_delayed_delayer_o_index)
  );	// difftest/src/main/scala/util/Delayer.scala:54:15
  PreprocessEndpoint preprocessed_module (	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_4_valid                           (_bundle_delayed_delayer_o_valid),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_skip                            (_bundle_delayed_delayer_o_skip),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_isRVC                           (_bundle_delayed_delayer_o_isRVC),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_rfwen                           (_bundle_delayed_delayer_o_rfwen),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_fpwen                           (_bundle_delayed_delayer_o_fpwen),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_vecwen                          (_bundle_delayed_delayer_o_vecwen),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_v0wen                           (_bundle_delayed_delayer_o_v0wen),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_wpdest                          (_bundle_delayed_delayer_o_wpdest),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_wdest                           (_bundle_delayed_delayer_o_wdest),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_otherwpdest_0                   (_bundle_delayed_delayer_o_otherwpdest_0),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_otherwpdest_1                   (_bundle_delayed_delayer_o_otherwpdest_1),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_otherwpdest_2                   (_bundle_delayed_delayer_o_otherwpdest_2),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_otherwpdest_3                   (_bundle_delayed_delayer_o_otherwpdest_3),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_otherwpdest_4                   (_bundle_delayed_delayer_o_otherwpdest_4),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_otherwpdest_5                   (_bundle_delayed_delayer_o_otherwpdest_5),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_otherwpdest_6                   (_bundle_delayed_delayer_o_otherwpdest_6),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_otherwpdest_7                   (_bundle_delayed_delayer_o_otherwpdest_7),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_otherwpdest_8                   (_bundle_delayed_delayer_o_otherwpdest_8),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_otherwpdest_9                   (_bundle_delayed_delayer_o_otherwpdest_9),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_otherwpdest_10                  (_bundle_delayed_delayer_o_otherwpdest_10),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_otherwpdest_11                  (_bundle_delayed_delayer_o_otherwpdest_11),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_otherwpdest_12                  (_bundle_delayed_delayer_o_otherwpdest_12),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_otherwpdest_13                  (_bundle_delayed_delayer_o_otherwpdest_13),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_otherwpdest_14                  (_bundle_delayed_delayer_o_otherwpdest_14),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_otherwpdest_15                  (_bundle_delayed_delayer_o_otherwpdest_15),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_pc                              (_bundle_delayed_delayer_o_pc),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_instr                           (_bundle_delayed_delayer_o_instr),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_robIdx                          (_bundle_delayed_delayer_o_robIdx),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_lqIdx                           (_bundle_delayed_delayer_o_lqIdx),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_sqIdx                           (_bundle_delayed_delayer_o_sqIdx),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_isLoad                          (_bundle_delayed_delayer_o_isLoad),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_isStore                         (_bundle_delayed_delayer_o_isStore),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_nFused                          (_bundle_delayed_delayer_o_nFused),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_special                         (_bundle_delayed_delayer_o_special),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_coreid                          (_bundle_delayed_delayer_o_coreid),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_4_index                           (_bundle_delayed_delayer_o_index),	// difftest/src/main/scala/util/Delayer.scala:54:15
    .in_3_hasTrap                         (in[3654]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_3_cycleCnt                        (in[3653:3590]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_3_instrCnt                        (in[3589:3526]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_3_hasWFI                          (in[3525]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_3_code                            (in[3524:3461]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_3_pc                              (in[3460:3397]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_3_coreid                          (in[3396:3389]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_2_valid                           (in[3388]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_2_interrupt                       (in[3387:3356]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_2_exception                       (in[3355:3324]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_2_exceptionPC                     (in[3323:3260]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_2_exceptionInst                   (in[3259:3228]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_2_hasNMI                          (in[3227]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_2_virtualInterruptIsHvictlInject  (in[3226]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_2_irToHS                          (in[3225]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_2_irToVS                          (in[3224]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_2_coreid                          (in[3223:3216]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_1_privilegeMode                   (in[3215:3152]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_1_mstatus                         (in[3151:3088]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_1_sstatus                         (in[3087:3024]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_1_mepc                            (in[3023:2960]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_1_sepc                            (in[2959:2896]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_1_mtval                           (in[2895:2832]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_1_stval                           (in[2831:2768]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_1_mtvec                           (in[2767:2704]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_1_stvec                           (in[2703:2640]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_1_mcause                          (in[2639:2576]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_1_scause                          (in[2575:2512]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_1_satp                            (in[2511:2448]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_1_mip                             (in[2447:2384]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_1_mie                             (in[2383:2320]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_1_mscratch                        (in[2319:2256]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_1_sscratch                        (in[2255:2192]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_1_mideleg                         (in[2191:2128]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_1_medeleg                         (in[2127:2064]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_1_coreid                          (in[2063:2056]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_0_value_0                         (in[71:8]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_0_value_1                         (in[135:72]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_0_value_2                         (in[199:136]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_0_value_3                         (in[263:200]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_0_value_4                         (in[327:264]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_0_value_5                         (in[391:328]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_0_value_6                         (in[455:392]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_0_value_7                         (in[519:456]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_0_value_8                         (in[583:520]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_0_value_9                         (in[647:584]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_0_value_10                        (in[711:648]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_0_value_11                        (in[775:712]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_0_value_12                        (in[839:776]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_0_value_13                        (in[903:840]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_0_value_14                        (in[967:904]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_0_value_15                        (in[1031:968]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_0_value_16                        (in[1095:1032]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_0_value_17                        (in[1159:1096]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_0_value_18                        (in[1223:1160]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_0_value_19                        (in[1287:1224]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_0_value_20                        (in[1351:1288]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_0_value_21                        (in[1415:1352]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_0_value_22                        (in[1479:1416]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_0_value_23                        (in[1543:1480]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_0_value_24                        (in[1607:1544]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_0_value_25                        (in[1671:1608]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_0_value_26                        (in[1735:1672]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_0_value_27                        (in[1799:1736]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_0_value_28                        (in[1863:1800]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_0_value_29                        (in[1927:1864]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_0_value_30                        (in[1991:1928]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_0_value_31                        (in[2055:1992]),	// difftest/src/main/scala/Gateway.scala:235:30
    .in_0_coreid                          (in[7:0]),	// difftest/src/main/scala/Gateway.scala:235:30
    .out_5_valid                          (_preprocessed_module_out_5_valid),
    .out_5_data                           (_preprocessed_module_out_5_data),
    .out_5_coreid                         (_preprocessed_module_out_5_coreid),
    .out_5_index                          (_preprocessed_module_out_5_index),
    .out_4_value_0                        (_preprocessed_module_out_4_value_0),
    .out_4_value_1                        (_preprocessed_module_out_4_value_1),
    .out_4_value_2                        (_preprocessed_module_out_4_value_2),
    .out_4_value_3                        (_preprocessed_module_out_4_value_3),
    .out_4_value_4                        (_preprocessed_module_out_4_value_4),
    .out_4_value_5                        (_preprocessed_module_out_4_value_5),
    .out_4_value_6                        (_preprocessed_module_out_4_value_6),
    .out_4_value_7                        (_preprocessed_module_out_4_value_7),
    .out_4_value_8                        (_preprocessed_module_out_4_value_8),
    .out_4_value_9                        (_preprocessed_module_out_4_value_9),
    .out_4_value_10                       (_preprocessed_module_out_4_value_10),
    .out_4_value_11                       (_preprocessed_module_out_4_value_11),
    .out_4_value_12                       (_preprocessed_module_out_4_value_12),
    .out_4_value_13                       (_preprocessed_module_out_4_value_13),
    .out_4_value_14                       (_preprocessed_module_out_4_value_14),
    .out_4_value_15                       (_preprocessed_module_out_4_value_15),
    .out_4_value_16                       (_preprocessed_module_out_4_value_16),
    .out_4_value_17                       (_preprocessed_module_out_4_value_17),
    .out_4_value_18                       (_preprocessed_module_out_4_value_18),
    .out_4_value_19                       (_preprocessed_module_out_4_value_19),
    .out_4_value_20                       (_preprocessed_module_out_4_value_20),
    .out_4_value_21                       (_preprocessed_module_out_4_value_21),
    .out_4_value_22                       (_preprocessed_module_out_4_value_22),
    .out_4_value_23                       (_preprocessed_module_out_4_value_23),
    .out_4_value_24                       (_preprocessed_module_out_4_value_24),
    .out_4_value_25                       (_preprocessed_module_out_4_value_25),
    .out_4_value_26                       (_preprocessed_module_out_4_value_26),
    .out_4_value_27                       (_preprocessed_module_out_4_value_27),
    .out_4_value_28                       (_preprocessed_module_out_4_value_28),
    .out_4_value_29                       (_preprocessed_module_out_4_value_29),
    .out_4_value_30                       (_preprocessed_module_out_4_value_30),
    .out_4_value_31                       (_preprocessed_module_out_4_value_31),
    .out_4_coreid                         (_preprocessed_module_out_4_coreid),
    .out_3_valid                          (_preprocessed_module_out_3_valid),
    .out_3_skip                           (_preprocessed_module_out_3_skip),
    .out_3_isRVC                          (_preprocessed_module_out_3_isRVC),
    .out_3_rfwen                          (_preprocessed_module_out_3_rfwen),
    .out_3_fpwen                          (_preprocessed_module_out_3_fpwen),
    .out_3_vecwen                         (_preprocessed_module_out_3_vecwen),
    .out_3_v0wen                          (_preprocessed_module_out_3_v0wen),
    .out_3_wpdest                         (_preprocessed_module_out_3_wpdest),
    .out_3_wdest                          (_preprocessed_module_out_3_wdest),
    .out_3_otherwpdest_0                  (_preprocessed_module_out_3_otherwpdest_0),
    .out_3_otherwpdest_1                  (_preprocessed_module_out_3_otherwpdest_1),
    .out_3_otherwpdest_2                  (_preprocessed_module_out_3_otherwpdest_2),
    .out_3_otherwpdest_3                  (_preprocessed_module_out_3_otherwpdest_3),
    .out_3_otherwpdest_4                  (_preprocessed_module_out_3_otherwpdest_4),
    .out_3_otherwpdest_5                  (_preprocessed_module_out_3_otherwpdest_5),
    .out_3_otherwpdest_6                  (_preprocessed_module_out_3_otherwpdest_6),
    .out_3_otherwpdest_7                  (_preprocessed_module_out_3_otherwpdest_7),
    .out_3_otherwpdest_8                  (_preprocessed_module_out_3_otherwpdest_8),
    .out_3_otherwpdest_9                  (_preprocessed_module_out_3_otherwpdest_9),
    .out_3_otherwpdest_10                 (_preprocessed_module_out_3_otherwpdest_10),
    .out_3_otherwpdest_11                 (_preprocessed_module_out_3_otherwpdest_11),
    .out_3_otherwpdest_12                 (_preprocessed_module_out_3_otherwpdest_12),
    .out_3_otherwpdest_13                 (_preprocessed_module_out_3_otherwpdest_13),
    .out_3_otherwpdest_14                 (_preprocessed_module_out_3_otherwpdest_14),
    .out_3_otherwpdest_15                 (_preprocessed_module_out_3_otherwpdest_15),
    .out_3_pc                             (_preprocessed_module_out_3_pc),
    .out_3_instr                          (_preprocessed_module_out_3_instr),
    .out_3_robIdx                         (_preprocessed_module_out_3_robIdx),
    .out_3_lqIdx                          (_preprocessed_module_out_3_lqIdx),
    .out_3_sqIdx                          (_preprocessed_module_out_3_sqIdx),
    .out_3_isLoad                         (_preprocessed_module_out_3_isLoad),
    .out_3_isStore                        (_preprocessed_module_out_3_isStore),
    .out_3_nFused                         (_preprocessed_module_out_3_nFused),
    .out_3_special                        (_preprocessed_module_out_3_special),
    .out_3_coreid                         (_preprocessed_module_out_3_coreid),
    .out_3_index                          (_preprocessed_module_out_3_index),
    .out_2_hasTrap                        (_preprocessed_module_out_2_hasTrap),
    .out_2_cycleCnt                       (_preprocessed_module_out_2_cycleCnt),
    .out_2_instrCnt                       (_preprocessed_module_out_2_instrCnt),
    .out_2_hasWFI                         (_preprocessed_module_out_2_hasWFI),
    .out_2_code                           (_preprocessed_module_out_2_code),
    .out_2_pc                             (_preprocessed_module_out_2_pc),
    .out_2_coreid                         (_preprocessed_module_out_2_coreid),
    .out_1_valid                          (_preprocessed_module_out_1_valid),
    .out_1_interrupt                      (_preprocessed_module_out_1_interrupt),
    .out_1_exception                      (_preprocessed_module_out_1_exception),
    .out_1_exceptionPC                    (_preprocessed_module_out_1_exceptionPC),
    .out_1_exceptionInst                  (_preprocessed_module_out_1_exceptionInst),
    .out_1_hasNMI                         (_preprocessed_module_out_1_hasNMI),
    .out_1_virtualInterruptIsHvictlInject
      (_preprocessed_module_out_1_virtualInterruptIsHvictlInject),
    .out_1_irToHS                         (_preprocessed_module_out_1_irToHS),
    .out_1_irToVS                         (_preprocessed_module_out_1_irToVS),
    .out_1_coreid                         (_preprocessed_module_out_1_coreid),
    .out_0_privilegeMode                  (_preprocessed_module_out_0_privilegeMode),
    .out_0_mstatus                        (_preprocessed_module_out_0_mstatus),
    .out_0_sstatus                        (_preprocessed_module_out_0_sstatus),
    .out_0_mepc                           (_preprocessed_module_out_0_mepc),
    .out_0_sepc                           (_preprocessed_module_out_0_sepc),
    .out_0_mtval                          (_preprocessed_module_out_0_mtval),
    .out_0_stval                          (_preprocessed_module_out_0_stval),
    .out_0_mtvec                          (_preprocessed_module_out_0_mtvec),
    .out_0_stvec                          (_preprocessed_module_out_0_stvec),
    .out_0_mcause                         (_preprocessed_module_out_0_mcause),
    .out_0_scause                         (_preprocessed_module_out_0_scause),
    .out_0_satp                           (_preprocessed_module_out_0_satp),
    .out_0_mip                            (_preprocessed_module_out_0_mip),
    .out_0_mie                            (_preprocessed_module_out_0_mie),
    .out_0_mscratch                       (_preprocessed_module_out_0_mscratch),
    .out_0_sscratch                       (_preprocessed_module_out_0_sscratch),
    .out_0_mideleg                        (_preprocessed_module_out_0_mideleg),
    .out_0_medeleg                        (_preprocessed_module_out_0_medeleg),
    .out_0_coreid                         (_preprocessed_module_out_0_coreid)
  );	// difftest/src/main/scala/Preprocess.scala:26:24
  Validator validated_module (	// difftest/src/main/scala/Validate.scala:26:24
    .in_5_valid                                (_preprocessed_module_out_5_valid),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_5_data                                 (_preprocessed_module_out_5_data),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_5_coreid                               (_preprocessed_module_out_5_coreid),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_5_index                                (_preprocessed_module_out_5_index),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_4_value_0                              (_preprocessed_module_out_4_value_0),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_4_value_1                              (_preprocessed_module_out_4_value_1),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_4_value_2                              (_preprocessed_module_out_4_value_2),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_4_value_3                              (_preprocessed_module_out_4_value_3),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_4_value_4                              (_preprocessed_module_out_4_value_4),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_4_value_5                              (_preprocessed_module_out_4_value_5),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_4_value_6                              (_preprocessed_module_out_4_value_6),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_4_value_7                              (_preprocessed_module_out_4_value_7),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_4_value_8                              (_preprocessed_module_out_4_value_8),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_4_value_9                              (_preprocessed_module_out_4_value_9),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_4_value_10                             (_preprocessed_module_out_4_value_10),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_4_value_11                             (_preprocessed_module_out_4_value_11),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_4_value_12                             (_preprocessed_module_out_4_value_12),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_4_value_13                             (_preprocessed_module_out_4_value_13),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_4_value_14                             (_preprocessed_module_out_4_value_14),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_4_value_15                             (_preprocessed_module_out_4_value_15),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_4_value_16                             (_preprocessed_module_out_4_value_16),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_4_value_17                             (_preprocessed_module_out_4_value_17),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_4_value_18                             (_preprocessed_module_out_4_value_18),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_4_value_19                             (_preprocessed_module_out_4_value_19),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_4_value_20                             (_preprocessed_module_out_4_value_20),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_4_value_21                             (_preprocessed_module_out_4_value_21),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_4_value_22                             (_preprocessed_module_out_4_value_22),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_4_value_23                             (_preprocessed_module_out_4_value_23),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_4_value_24                             (_preprocessed_module_out_4_value_24),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_4_value_25                             (_preprocessed_module_out_4_value_25),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_4_value_26                             (_preprocessed_module_out_4_value_26),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_4_value_27                             (_preprocessed_module_out_4_value_27),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_4_value_28                             (_preprocessed_module_out_4_value_28),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_4_value_29                             (_preprocessed_module_out_4_value_29),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_4_value_30                             (_preprocessed_module_out_4_value_30),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_4_value_31                             (_preprocessed_module_out_4_value_31),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_4_coreid                               (_preprocessed_module_out_4_coreid),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_valid                                (_preprocessed_module_out_3_valid),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_skip                                 (_preprocessed_module_out_3_skip),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_isRVC                                (_preprocessed_module_out_3_isRVC),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_rfwen                                (_preprocessed_module_out_3_rfwen),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_fpwen                                (_preprocessed_module_out_3_fpwen),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_vecwen                               (_preprocessed_module_out_3_vecwen),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_v0wen                                (_preprocessed_module_out_3_v0wen),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_wpdest                               (_preprocessed_module_out_3_wpdest),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_wdest                                (_preprocessed_module_out_3_wdest),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_otherwpdest_0                        (_preprocessed_module_out_3_otherwpdest_0),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_otherwpdest_1                        (_preprocessed_module_out_3_otherwpdest_1),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_otherwpdest_2                        (_preprocessed_module_out_3_otherwpdest_2),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_otherwpdest_3                        (_preprocessed_module_out_3_otherwpdest_3),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_otherwpdest_4                        (_preprocessed_module_out_3_otherwpdest_4),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_otherwpdest_5                        (_preprocessed_module_out_3_otherwpdest_5),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_otherwpdest_6                        (_preprocessed_module_out_3_otherwpdest_6),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_otherwpdest_7                        (_preprocessed_module_out_3_otherwpdest_7),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_otherwpdest_8                        (_preprocessed_module_out_3_otherwpdest_8),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_otherwpdest_9                        (_preprocessed_module_out_3_otherwpdest_9),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_otherwpdest_10
      (_preprocessed_module_out_3_otherwpdest_10),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_otherwpdest_11
      (_preprocessed_module_out_3_otherwpdest_11),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_otherwpdest_12
      (_preprocessed_module_out_3_otherwpdest_12),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_otherwpdest_13
      (_preprocessed_module_out_3_otherwpdest_13),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_otherwpdest_14
      (_preprocessed_module_out_3_otherwpdest_14),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_otherwpdest_15
      (_preprocessed_module_out_3_otherwpdest_15),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_pc                                   (_preprocessed_module_out_3_pc),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_instr                                (_preprocessed_module_out_3_instr),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_robIdx                               (_preprocessed_module_out_3_robIdx),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_lqIdx                                (_preprocessed_module_out_3_lqIdx),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_sqIdx                                (_preprocessed_module_out_3_sqIdx),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_isLoad                               (_preprocessed_module_out_3_isLoad),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_isStore                              (_preprocessed_module_out_3_isStore),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_nFused                               (_preprocessed_module_out_3_nFused),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_special                              (_preprocessed_module_out_3_special),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_coreid                               (_preprocessed_module_out_3_coreid),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_3_index                                (_preprocessed_module_out_3_index),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_2_hasTrap                              (_preprocessed_module_out_2_hasTrap),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_2_cycleCnt                             (_preprocessed_module_out_2_cycleCnt),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_2_instrCnt                             (_preprocessed_module_out_2_instrCnt),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_2_hasWFI                               (_preprocessed_module_out_2_hasWFI),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_2_code                                 (_preprocessed_module_out_2_code),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_2_pc                                   (_preprocessed_module_out_2_pc),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_2_coreid                               (_preprocessed_module_out_2_coreid),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_1_valid                                (_preprocessed_module_out_1_valid),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_1_interrupt                            (_preprocessed_module_out_1_interrupt),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_1_exception                            (_preprocessed_module_out_1_exception),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_1_exceptionPC                          (_preprocessed_module_out_1_exceptionPC),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_1_exceptionInst                        (_preprocessed_module_out_1_exceptionInst),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_1_hasNMI                               (_preprocessed_module_out_1_hasNMI),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_1_virtualInterruptIsHvictlInject
      (_preprocessed_module_out_1_virtualInterruptIsHvictlInject),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_1_irToHS                               (_preprocessed_module_out_1_irToHS),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_1_irToVS                               (_preprocessed_module_out_1_irToVS),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_1_coreid                               (_preprocessed_module_out_1_coreid),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_0_privilegeMode                        (_preprocessed_module_out_0_privilegeMode),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_0_mstatus                              (_preprocessed_module_out_0_mstatus),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_0_sstatus                              (_preprocessed_module_out_0_sstatus),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_0_mepc                                 (_preprocessed_module_out_0_mepc),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_0_sepc                                 (_preprocessed_module_out_0_sepc),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_0_mtval                                (_preprocessed_module_out_0_mtval),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_0_stval                                (_preprocessed_module_out_0_stval),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_0_mtvec                                (_preprocessed_module_out_0_mtvec),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_0_stvec                                (_preprocessed_module_out_0_stvec),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_0_mcause                               (_preprocessed_module_out_0_mcause),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_0_scause                               (_preprocessed_module_out_0_scause),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_0_satp                                 (_preprocessed_module_out_0_satp),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_0_mip                                  (_preprocessed_module_out_0_mip),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_0_mie                                  (_preprocessed_module_out_0_mie),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_0_mscratch                             (_preprocessed_module_out_0_mscratch),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_0_sscratch                             (_preprocessed_module_out_0_sscratch),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_0_mideleg                              (_preprocessed_module_out_0_mideleg),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_0_medeleg                              (_preprocessed_module_out_0_medeleg),	// difftest/src/main/scala/Preprocess.scala:26:24
    .in_0_coreid                               (_preprocessed_module_out_0_coreid),	// difftest/src/main/scala/Preprocess.scala:26:24
    .out_5_valid                               (_validated_module_out_5_valid),
    .out_5_bits_valid                          (_validated_module_out_5_bits_valid),
    .out_5_bits_data                           (_validated_module_out_5_bits_data),
    .out_5_bits_coreid                         (_validated_module_out_5_bits_coreid),
    .out_5_bits_index                          (_validated_module_out_5_bits_index),
    .out_4_valid                               (_validated_module_out_4_valid),
    .out_4_bits_value_0                        (_validated_module_out_4_bits_value_0),
    .out_4_bits_value_1                        (_validated_module_out_4_bits_value_1),
    .out_4_bits_value_2                        (_validated_module_out_4_bits_value_2),
    .out_4_bits_value_3                        (_validated_module_out_4_bits_value_3),
    .out_4_bits_value_4                        (_validated_module_out_4_bits_value_4),
    .out_4_bits_value_5                        (_validated_module_out_4_bits_value_5),
    .out_4_bits_value_6                        (_validated_module_out_4_bits_value_6),
    .out_4_bits_value_7                        (_validated_module_out_4_bits_value_7),
    .out_4_bits_value_8                        (_validated_module_out_4_bits_value_8),
    .out_4_bits_value_9                        (_validated_module_out_4_bits_value_9),
    .out_4_bits_value_10                       (_validated_module_out_4_bits_value_10),
    .out_4_bits_value_11                       (_validated_module_out_4_bits_value_11),
    .out_4_bits_value_12                       (_validated_module_out_4_bits_value_12),
    .out_4_bits_value_13                       (_validated_module_out_4_bits_value_13),
    .out_4_bits_value_14                       (_validated_module_out_4_bits_value_14),
    .out_4_bits_value_15                       (_validated_module_out_4_bits_value_15),
    .out_4_bits_value_16                       (_validated_module_out_4_bits_value_16),
    .out_4_bits_value_17                       (_validated_module_out_4_bits_value_17),
    .out_4_bits_value_18                       (_validated_module_out_4_bits_value_18),
    .out_4_bits_value_19                       (_validated_module_out_4_bits_value_19),
    .out_4_bits_value_20                       (_validated_module_out_4_bits_value_20),
    .out_4_bits_value_21                       (_validated_module_out_4_bits_value_21),
    .out_4_bits_value_22                       (_validated_module_out_4_bits_value_22),
    .out_4_bits_value_23                       (_validated_module_out_4_bits_value_23),
    .out_4_bits_value_24                       (_validated_module_out_4_bits_value_24),
    .out_4_bits_value_25                       (_validated_module_out_4_bits_value_25),
    .out_4_bits_value_26                       (_validated_module_out_4_bits_value_26),
    .out_4_bits_value_27                       (_validated_module_out_4_bits_value_27),
    .out_4_bits_value_28                       (_validated_module_out_4_bits_value_28),
    .out_4_bits_value_29                       (_validated_module_out_4_bits_value_29),
    .out_4_bits_value_30                       (_validated_module_out_4_bits_value_30),
    .out_4_bits_value_31                       (_validated_module_out_4_bits_value_31),
    .out_4_bits_coreid                         (_validated_module_out_4_bits_coreid),
    .out_3_valid                               (_validated_module_out_3_valid),
    .out_3_bits_valid                          (_validated_module_out_3_bits_valid),
    .out_3_bits_skip                           (_validated_module_out_3_bits_skip),
    .out_3_bits_isRVC                          (_validated_module_out_3_bits_isRVC),
    .out_3_bits_rfwen                          (_validated_module_out_3_bits_rfwen),
    .out_3_bits_fpwen                          (_validated_module_out_3_bits_fpwen),
    .out_3_bits_vecwen                         (_validated_module_out_3_bits_vecwen),
    .out_3_bits_v0wen                          (_validated_module_out_3_bits_v0wen),
    .out_3_bits_wpdest                         (_validated_module_out_3_bits_wpdest),
    .out_3_bits_wdest                          (_validated_module_out_3_bits_wdest),
    .out_3_bits_otherwpdest_0
      (_validated_module_out_3_bits_otherwpdest_0),
    .out_3_bits_otherwpdest_1
      (_validated_module_out_3_bits_otherwpdest_1),
    .out_3_bits_otherwpdest_2
      (_validated_module_out_3_bits_otherwpdest_2),
    .out_3_bits_otherwpdest_3
      (_validated_module_out_3_bits_otherwpdest_3),
    .out_3_bits_otherwpdest_4
      (_validated_module_out_3_bits_otherwpdest_4),
    .out_3_bits_otherwpdest_5
      (_validated_module_out_3_bits_otherwpdest_5),
    .out_3_bits_otherwpdest_6
      (_validated_module_out_3_bits_otherwpdest_6),
    .out_3_bits_otherwpdest_7
      (_validated_module_out_3_bits_otherwpdest_7),
    .out_3_bits_otherwpdest_8
      (_validated_module_out_3_bits_otherwpdest_8),
    .out_3_bits_otherwpdest_9
      (_validated_module_out_3_bits_otherwpdest_9),
    .out_3_bits_otherwpdest_10
      (_validated_module_out_3_bits_otherwpdest_10),
    .out_3_bits_otherwpdest_11
      (_validated_module_out_3_bits_otherwpdest_11),
    .out_3_bits_otherwpdest_12
      (_validated_module_out_3_bits_otherwpdest_12),
    .out_3_bits_otherwpdest_13
      (_validated_module_out_3_bits_otherwpdest_13),
    .out_3_bits_otherwpdest_14
      (_validated_module_out_3_bits_otherwpdest_14),
    .out_3_bits_otherwpdest_15
      (_validated_module_out_3_bits_otherwpdest_15),
    .out_3_bits_pc                             (_validated_module_out_3_bits_pc),
    .out_3_bits_instr                          (_validated_module_out_3_bits_instr),
    .out_3_bits_robIdx                         (_validated_module_out_3_bits_robIdx),
    .out_3_bits_lqIdx                          (_validated_module_out_3_bits_lqIdx),
    .out_3_bits_sqIdx                          (_validated_module_out_3_bits_sqIdx),
    .out_3_bits_isLoad                         (_validated_module_out_3_bits_isLoad),
    .out_3_bits_isStore                        (_validated_module_out_3_bits_isStore),
    .out_3_bits_nFused                         (_validated_module_out_3_bits_nFused),
    .out_3_bits_special                        (_validated_module_out_3_bits_special),
    .out_3_bits_coreid                         (_validated_module_out_3_bits_coreid),
    .out_3_bits_index                          (_validated_module_out_3_bits_index),
    .out_2_bits_hasTrap                        (_validated_module_out_2_bits_hasTrap),
    .out_2_bits_cycleCnt                       (_validated_module_out_2_bits_cycleCnt),
    .out_2_bits_instrCnt                       (_validated_module_out_2_bits_instrCnt),
    .out_2_bits_hasWFI                         (_validated_module_out_2_bits_hasWFI),
    .out_2_bits_code                           (_validated_module_out_2_bits_code),
    .out_2_bits_pc                             (_validated_module_out_2_bits_pc),
    .out_2_bits_coreid                         (_validated_module_out_2_bits_coreid),
    .out_1_valid                               (_validated_module_out_1_valid),
    .out_1_bits_valid                          (_validated_module_out_1_bits_valid),
    .out_1_bits_interrupt                      (_validated_module_out_1_bits_interrupt),
    .out_1_bits_exception                      (_validated_module_out_1_bits_exception),
    .out_1_bits_exceptionPC                    (_validated_module_out_1_bits_exceptionPC),
    .out_1_bits_exceptionInst
      (_validated_module_out_1_bits_exceptionInst),
    .out_1_bits_hasNMI                         (_validated_module_out_1_bits_hasNMI),
    .out_1_bits_virtualInterruptIsHvictlInject
      (_validated_module_out_1_bits_virtualInterruptIsHvictlInject),
    .out_1_bits_irToHS                         (_validated_module_out_1_bits_irToHS),
    .out_1_bits_irToVS                         (_validated_module_out_1_bits_irToVS),
    .out_1_bits_coreid                         (_validated_module_out_1_bits_coreid),
    .out_0_valid                               (_validated_module_out_0_valid),
    .out_0_bits_privilegeMode
      (_validated_module_out_0_bits_privilegeMode),
    .out_0_bits_mstatus                        (_validated_module_out_0_bits_mstatus),
    .out_0_bits_sstatus                        (_validated_module_out_0_bits_sstatus),
    .out_0_bits_mepc                           (_validated_module_out_0_bits_mepc),
    .out_0_bits_sepc                           (_validated_module_out_0_bits_sepc),
    .out_0_bits_mtval                          (_validated_module_out_0_bits_mtval),
    .out_0_bits_stval                          (_validated_module_out_0_bits_stval),
    .out_0_bits_mtvec                          (_validated_module_out_0_bits_mtvec),
    .out_0_bits_stvec                          (_validated_module_out_0_bits_stvec),
    .out_0_bits_mcause                         (_validated_module_out_0_bits_mcause),
    .out_0_bits_scause                         (_validated_module_out_0_bits_scause),
    .out_0_bits_satp                           (_validated_module_out_0_bits_satp),
    .out_0_bits_mip                            (_validated_module_out_0_bits_mip),
    .out_0_bits_mie                            (_validated_module_out_0_bits_mie),
    .out_0_bits_mscratch                       (_validated_module_out_0_bits_mscratch),
    .out_0_bits_sscratch                       (_validated_module_out_0_bits_sscratch),
    .out_0_bits_mideleg                        (_validated_module_out_0_bits_mideleg),
    .out_0_bits_medeleg                        (_validated_module_out_0_bits_medeleg),
    .out_0_bits_coreid                         (_validated_module_out_0_bits_coreid)
  );	// difftest/src/main/scala/Validate.scala:26:24
  DummyDPICWrapper_CSRState csr (	// difftest/src/main/scala/DPIC.scala:375:24
    .clock                 (clock),
    .reset                 (reset),
    .io_valid              (_validated_module_out_0_valid),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_privilegeMode (_validated_module_out_0_bits_privilegeMode),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_mstatus       (_validated_module_out_0_bits_mstatus),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_sstatus       (_validated_module_out_0_bits_sstatus),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_mepc          (_validated_module_out_0_bits_mepc),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_sepc          (_validated_module_out_0_bits_sepc),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_mtval         (_validated_module_out_0_bits_mtval),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_stval         (_validated_module_out_0_bits_stval),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_mtvec         (_validated_module_out_0_bits_mtvec),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_stvec         (_validated_module_out_0_bits_stvec),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_mcause        (_validated_module_out_0_bits_mcause),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_scause        (_validated_module_out_0_bits_scause),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_satp          (_validated_module_out_0_bits_satp),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_mip           (_validated_module_out_0_bits_mip),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_mie           (_validated_module_out_0_bits_mie),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_mscratch      (_validated_module_out_0_bits_mscratch),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_sscratch      (_validated_module_out_0_bits_sscratch),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_mideleg       (_validated_module_out_0_bits_mideleg),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_medeleg       (_validated_module_out_0_bits_medeleg),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_coreid        (_validated_module_out_0_bits_coreid)	// difftest/src/main/scala/Validate.scala:26:24
  );	// difftest/src/main/scala/DPIC.scala:375:24
  DummyDPICWrapper_ArchEvent event_0 (	// difftest/src/main/scala/DPIC.scala:375:24
    .clock                                  (clock),
    .reset                                  (reset),
    .io_valid                               (_validated_module_out_1_valid),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_valid                          (_validated_module_out_1_bits_valid),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_interrupt                      (_validated_module_out_1_bits_interrupt),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_exception                      (_validated_module_out_1_bits_exception),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_exceptionPC                    (_validated_module_out_1_bits_exceptionPC),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_exceptionInst                  (_validated_module_out_1_bits_exceptionInst),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_hasNMI                         (_validated_module_out_1_bits_hasNMI),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_virtualInterruptIsHvictlInject
      (_validated_module_out_1_bits_virtualInterruptIsHvictlInject),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_irToHS                         (_validated_module_out_1_bits_irToHS),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_irToVS                         (_validated_module_out_1_bits_irToVS),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_coreid                         (_validated_module_out_1_bits_coreid)	// difftest/src/main/scala/Validate.scala:26:24
  );	// difftest/src/main/scala/DPIC.scala:375:24
  DummyDPICWrapper_TrapEvent trap (	// difftest/src/main/scala/DPIC.scala:375:24
    .clock            (clock),
    .reset            (reset),
    .io_bits_hasTrap  (_validated_module_out_2_bits_hasTrap),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_cycleCnt (_validated_module_out_2_bits_cycleCnt),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_instrCnt (_validated_module_out_2_bits_instrCnt),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_hasWFI   (_validated_module_out_2_bits_hasWFI),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_code     (_validated_module_out_2_bits_code),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_pc       (_validated_module_out_2_bits_pc),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_coreid   (_validated_module_out_2_bits_coreid)	// difftest/src/main/scala/Validate.scala:26:24
  );	// difftest/src/main/scala/DPIC.scala:375:24
  DummyDPICWrapper_InstrCommit commit (	// difftest/src/main/scala/DPIC.scala:375:24
    .clock                  (clock),
    .reset                  (reset),
    .io_valid               (_validated_module_out_3_valid),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_valid          (_validated_module_out_3_bits_valid),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_skip           (_validated_module_out_3_bits_skip),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_isRVC          (_validated_module_out_3_bits_isRVC),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_rfwen          (_validated_module_out_3_bits_rfwen),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_fpwen          (_validated_module_out_3_bits_fpwen),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_vecwen         (_validated_module_out_3_bits_vecwen),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_v0wen          (_validated_module_out_3_bits_v0wen),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_wpdest         (_validated_module_out_3_bits_wpdest),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_wdest          (_validated_module_out_3_bits_wdest),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_otherwpdest_0  (_validated_module_out_3_bits_otherwpdest_0),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_otherwpdest_1  (_validated_module_out_3_bits_otherwpdest_1),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_otherwpdest_2  (_validated_module_out_3_bits_otherwpdest_2),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_otherwpdest_3  (_validated_module_out_3_bits_otherwpdest_3),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_otherwpdest_4  (_validated_module_out_3_bits_otherwpdest_4),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_otherwpdest_5  (_validated_module_out_3_bits_otherwpdest_5),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_otherwpdest_6  (_validated_module_out_3_bits_otherwpdest_6),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_otherwpdest_7  (_validated_module_out_3_bits_otherwpdest_7),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_otherwpdest_8  (_validated_module_out_3_bits_otherwpdest_8),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_otherwpdest_9  (_validated_module_out_3_bits_otherwpdest_9),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_otherwpdest_10 (_validated_module_out_3_bits_otherwpdest_10),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_otherwpdest_11 (_validated_module_out_3_bits_otherwpdest_11),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_otherwpdest_12 (_validated_module_out_3_bits_otherwpdest_12),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_otherwpdest_13 (_validated_module_out_3_bits_otherwpdest_13),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_otherwpdest_14 (_validated_module_out_3_bits_otherwpdest_14),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_otherwpdest_15 (_validated_module_out_3_bits_otherwpdest_15),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_pc             (_validated_module_out_3_bits_pc),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_instr          (_validated_module_out_3_bits_instr),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_robIdx         (_validated_module_out_3_bits_robIdx),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_lqIdx          (_validated_module_out_3_bits_lqIdx),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_sqIdx          (_validated_module_out_3_bits_sqIdx),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_isLoad         (_validated_module_out_3_bits_isLoad),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_isStore        (_validated_module_out_3_bits_isStore),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_nFused         (_validated_module_out_3_bits_nFused),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_special        (_validated_module_out_3_bits_special),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_coreid         (_validated_module_out_3_bits_coreid),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_index          (_validated_module_out_3_bits_index)	// difftest/src/main/scala/Validate.scala:26:24
  );	// difftest/src/main/scala/DPIC.scala:375:24
  DummyDPICWrapper_ArchIntRegState xrf (	// difftest/src/main/scala/DPIC.scala:375:24
    .clock            (clock),
    .reset            (reset),
    .io_valid         (_validated_module_out_4_valid),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_value_0  (_validated_module_out_4_bits_value_0),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_value_1  (_validated_module_out_4_bits_value_1),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_value_2  (_validated_module_out_4_bits_value_2),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_value_3  (_validated_module_out_4_bits_value_3),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_value_4  (_validated_module_out_4_bits_value_4),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_value_5  (_validated_module_out_4_bits_value_5),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_value_6  (_validated_module_out_4_bits_value_6),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_value_7  (_validated_module_out_4_bits_value_7),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_value_8  (_validated_module_out_4_bits_value_8),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_value_9  (_validated_module_out_4_bits_value_9),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_value_10 (_validated_module_out_4_bits_value_10),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_value_11 (_validated_module_out_4_bits_value_11),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_value_12 (_validated_module_out_4_bits_value_12),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_value_13 (_validated_module_out_4_bits_value_13),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_value_14 (_validated_module_out_4_bits_value_14),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_value_15 (_validated_module_out_4_bits_value_15),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_value_16 (_validated_module_out_4_bits_value_16),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_value_17 (_validated_module_out_4_bits_value_17),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_value_18 (_validated_module_out_4_bits_value_18),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_value_19 (_validated_module_out_4_bits_value_19),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_value_20 (_validated_module_out_4_bits_value_20),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_value_21 (_validated_module_out_4_bits_value_21),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_value_22 (_validated_module_out_4_bits_value_22),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_value_23 (_validated_module_out_4_bits_value_23),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_value_24 (_validated_module_out_4_bits_value_24),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_value_25 (_validated_module_out_4_bits_value_25),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_value_26 (_validated_module_out_4_bits_value_26),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_value_27 (_validated_module_out_4_bits_value_27),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_value_28 (_validated_module_out_4_bits_value_28),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_value_29 (_validated_module_out_4_bits_value_29),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_value_30 (_validated_module_out_4_bits_value_30),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_value_31 (_validated_module_out_4_bits_value_31),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_coreid   (_validated_module_out_4_bits_coreid)	// difftest/src/main/scala/Validate.scala:26:24
  );	// difftest/src/main/scala/DPIC.scala:375:24
  DummyDPICWrapper_CommitData commit_data (	// difftest/src/main/scala/DPIC.scala:375:24
    .clock          (clock),
    .reset          (reset),
    .io_valid       (_validated_module_out_5_valid),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_valid  (_validated_module_out_5_bits_valid),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_data   (_validated_module_out_5_bits_data),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_coreid (_validated_module_out_5_bits_coreid),	// difftest/src/main/scala/Validate.scala:26:24
    .io_bits_index  (_validated_module_out_5_bits_index)	// difftest/src/main/scala/Validate.scala:26:24
  );	// difftest/src/main/scala/DPIC.scala:375:24
  assign step = step_REG;	// difftest/src/main/scala/Gateway.scala:233:7, :290:20
endmodule

