// Generated by CIRCT firtool-1.135.0
module IDU(	// src/main/scala/nutcore/frontend/IDU.scala:193:7
  output        io_in_0_ready,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
  input         io_in_0_valid,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
  input  [63:0] io_in_0_bits_instr,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
  input  [38:0] io_in_0_bits_pc,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_in_0_bits_pnpc,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
  input         io_in_0_bits_exceptionVec_12,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
  input  [3:0]  io_in_0_bits_brIdx,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
  input         io_in_0_bits_crossPageIPFFix,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_0_ready,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
  output        io_out_0_valid,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
  output [63:0] io_out_0_bits_cf_instr,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
  output [38:0] io_out_0_bits_cf_pc,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_0_bits_cf_pnpc,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
  output        io_out_0_bits_cf_exceptionVec_1,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_0_bits_cf_exceptionVec_2,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_0_bits_cf_exceptionVec_12,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_0_bits_cf_intrVec_0,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_0_bits_cf_intrVec_1,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_0_bits_cf_intrVec_2,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_0_bits_cf_intrVec_3,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_0_bits_cf_intrVec_4,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_0_bits_cf_intrVec_5,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_0_bits_cf_intrVec_6,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_0_bits_cf_intrVec_7,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_0_bits_cf_intrVec_8,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_0_bits_cf_intrVec_9,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_0_bits_cf_intrVec_10,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_0_bits_cf_intrVec_11,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
  output [3:0]  io_out_0_bits_cf_brIdx,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
  output        io_out_0_bits_cf_crossPageIPFFix,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_0_bits_ctrl_src1Type,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_0_bits_ctrl_src2Type,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
  output [2:0]  io_out_0_bits_ctrl_fuType,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
  output [6:0]  io_out_0_bits_ctrl_fuOpType,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
  output [4:0]  io_out_0_bits_ctrl_rfSrc1,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_0_bits_ctrl_rfSrc2,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
  output        io_out_0_bits_ctrl_rfWen,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
  output [4:0]  io_out_0_bits_ctrl_rfDest,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
  output        io_out_0_bits_ctrl_isNutCoreTrap,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
  output [63:0] io_out_0_bits_data_imm,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
  input         io_out_1_ready,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
  output        io_out_1_valid,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
  output [63:0] io_out_1_bits_cf_instr,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
  output [38:0] io_out_1_bits_cf_pc,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_1_bits_cf_pnpc,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
  output        io_out_1_bits_cf_exceptionVec_1,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_1_bits_cf_exceptionVec_2,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_1_bits_cf_exceptionVec_12,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_1_bits_cf_intrVec_0,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_1_bits_cf_intrVec_1,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_1_bits_cf_intrVec_2,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_1_bits_cf_intrVec_3,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_1_bits_cf_intrVec_4,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_1_bits_cf_intrVec_5,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_1_bits_cf_intrVec_6,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_1_bits_cf_intrVec_7,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_1_bits_cf_intrVec_8,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_1_bits_cf_intrVec_9,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_1_bits_cf_intrVec_10,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_1_bits_cf_intrVec_11,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
  output [3:0]  io_out_1_bits_cf_brIdx,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
  output        io_out_1_bits_cf_crossPageIPFFix,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_1_bits_ctrl_src1Type,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_1_bits_ctrl_src2Type,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
  output [2:0]  io_out_1_bits_ctrl_fuType,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
  output [6:0]  io_out_1_bits_ctrl_fuOpType,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
  output [4:0]  io_out_1_bits_ctrl_rfSrc1,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
                io_out_1_bits_ctrl_rfSrc2,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
  output        io_out_1_bits_ctrl_rfWen,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
  output [4:0]  io_out_1_bits_ctrl_rfDest,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
  output        io_out_1_bits_ctrl_isNutCoreTrap,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
  output [63:0] io_out_1_bits_data_imm,	// src/main/scala/nutcore/frontend/IDU.scala:194:14
  input  [11:0] decoder1_intrVec__bore,
                decoder2_intrVec__bore,
  input         decoder1_vmEnable__bore,
                decoder2_vmEnable__bore,
  output        _WIRE__bore
);

  wire _decoder2_io_isWFI;	// src/main/scala/nutcore/frontend/IDU.scala:199:25
  wire _decoder1_io_isWFI;	// src/main/scala/nutcore/frontend/IDU.scala:198:25
  wire _GEN = _decoder1_io_isWFI | _decoder2_io_isWFI;	// src/main/scala/nutcore/frontend/IDU.scala:198:25, :199:25, :219:{35,54}
  Decoder decoder1 (	// src/main/scala/nutcore/frontend/IDU.scala:198:25
    .io_in_ready                    (io_in_0_ready),
    .io_in_valid                    (io_in_0_valid),
    .io_in_bits_instr               (io_in_0_bits_instr),
    .io_in_bits_pc                  (io_in_0_bits_pc),
    .io_in_bits_pnpc                (io_in_0_bits_pnpc),
    .io_in_bits_exceptionVec_12     (io_in_0_bits_exceptionVec_12),
    .io_in_bits_brIdx               (io_in_0_bits_brIdx),
    .io_in_bits_crossPageIPFFix     (io_in_0_bits_crossPageIPFFix),
    .io_out_ready                   (io_out_0_ready),
    .io_out_valid                   (io_out_0_valid),
    .io_out_bits_cf_instr           (io_out_0_bits_cf_instr),
    .io_out_bits_cf_pc              (io_out_0_bits_cf_pc),
    .io_out_bits_cf_pnpc            (io_out_0_bits_cf_pnpc),
    .io_out_bits_cf_exceptionVec_1  (io_out_0_bits_cf_exceptionVec_1),
    .io_out_bits_cf_exceptionVec_2  (io_out_0_bits_cf_exceptionVec_2),
    .io_out_bits_cf_exceptionVec_12 (io_out_0_bits_cf_exceptionVec_12),
    .io_out_bits_cf_intrVec_0       (io_out_0_bits_cf_intrVec_0),
    .io_out_bits_cf_intrVec_1       (io_out_0_bits_cf_intrVec_1),
    .io_out_bits_cf_intrVec_2       (io_out_0_bits_cf_intrVec_2),
    .io_out_bits_cf_intrVec_3       (io_out_0_bits_cf_intrVec_3),
    .io_out_bits_cf_intrVec_4       (io_out_0_bits_cf_intrVec_4),
    .io_out_bits_cf_intrVec_5       (io_out_0_bits_cf_intrVec_5),
    .io_out_bits_cf_intrVec_6       (io_out_0_bits_cf_intrVec_6),
    .io_out_bits_cf_intrVec_7       (io_out_0_bits_cf_intrVec_7),
    .io_out_bits_cf_intrVec_8       (io_out_0_bits_cf_intrVec_8),
    .io_out_bits_cf_intrVec_9       (io_out_0_bits_cf_intrVec_9),
    .io_out_bits_cf_intrVec_10      (io_out_0_bits_cf_intrVec_10),
    .io_out_bits_cf_intrVec_11      (io_out_0_bits_cf_intrVec_11),
    .io_out_bits_cf_brIdx           (io_out_0_bits_cf_brIdx),
    .io_out_bits_cf_crossPageIPFFix (io_out_0_bits_cf_crossPageIPFFix),
    .io_out_bits_ctrl_src1Type      (io_out_0_bits_ctrl_src1Type),
    .io_out_bits_ctrl_src2Type      (io_out_0_bits_ctrl_src2Type),
    .io_out_bits_ctrl_fuType        (io_out_0_bits_ctrl_fuType),
    .io_out_bits_ctrl_fuOpType      (io_out_0_bits_ctrl_fuOpType),
    .io_out_bits_ctrl_rfSrc1        (io_out_0_bits_ctrl_rfSrc1),
    .io_out_bits_ctrl_rfSrc2        (io_out_0_bits_ctrl_rfSrc2),
    .io_out_bits_ctrl_rfWen         (io_out_0_bits_ctrl_rfWen),
    .io_out_bits_ctrl_rfDest        (io_out_0_bits_ctrl_rfDest),
    .io_out_bits_ctrl_isNutCoreTrap (io_out_0_bits_ctrl_isNutCoreTrap),
    .io_out_bits_data_imm           (io_out_0_bits_data_imm),
    .io_isWFI                       (_decoder1_io_isWFI),
    .intrVec__bore                  (decoder1_intrVec__bore),
    .vmEnable__bore                 (decoder1_vmEnable__bore)
  );	// src/main/scala/nutcore/frontend/IDU.scala:198:25
  Decoder decoder2 (	// src/main/scala/nutcore/frontend/IDU.scala:199:25
    .io_in_ready                    (/* unused */),
    .io_in_valid                    (1'h0),
    .io_in_bits_instr               (64'h0),
    .io_in_bits_pc                  (39'h0),
    .io_in_bits_pnpc                (39'h0),
    .io_in_bits_exceptionVec_12     (1'h0),
    .io_in_bits_brIdx               (4'h0),	// src/main/scala/nutcore/frontend/IDU.scala:194:14, :199:25
    .io_in_bits_crossPageIPFFix     (1'h0),
    .io_out_ready                   (io_out_1_ready),
    .io_out_valid                   (io_out_1_valid),
    .io_out_bits_cf_instr           (io_out_1_bits_cf_instr),
    .io_out_bits_cf_pc              (io_out_1_bits_cf_pc),
    .io_out_bits_cf_pnpc            (io_out_1_bits_cf_pnpc),
    .io_out_bits_cf_exceptionVec_1  (io_out_1_bits_cf_exceptionVec_1),
    .io_out_bits_cf_exceptionVec_2  (io_out_1_bits_cf_exceptionVec_2),
    .io_out_bits_cf_exceptionVec_12 (io_out_1_bits_cf_exceptionVec_12),
    .io_out_bits_cf_intrVec_0       (io_out_1_bits_cf_intrVec_0),
    .io_out_bits_cf_intrVec_1       (io_out_1_bits_cf_intrVec_1),
    .io_out_bits_cf_intrVec_2       (io_out_1_bits_cf_intrVec_2),
    .io_out_bits_cf_intrVec_3       (io_out_1_bits_cf_intrVec_3),
    .io_out_bits_cf_intrVec_4       (io_out_1_bits_cf_intrVec_4),
    .io_out_bits_cf_intrVec_5       (io_out_1_bits_cf_intrVec_5),
    .io_out_bits_cf_intrVec_6       (io_out_1_bits_cf_intrVec_6),
    .io_out_bits_cf_intrVec_7       (io_out_1_bits_cf_intrVec_7),
    .io_out_bits_cf_intrVec_8       (io_out_1_bits_cf_intrVec_8),
    .io_out_bits_cf_intrVec_9       (io_out_1_bits_cf_intrVec_9),
    .io_out_bits_cf_intrVec_10      (io_out_1_bits_cf_intrVec_10),
    .io_out_bits_cf_intrVec_11      (io_out_1_bits_cf_intrVec_11),
    .io_out_bits_cf_brIdx           (io_out_1_bits_cf_brIdx),
    .io_out_bits_cf_crossPageIPFFix (io_out_1_bits_cf_crossPageIPFFix),
    .io_out_bits_ctrl_src1Type      (io_out_1_bits_ctrl_src1Type),
    .io_out_bits_ctrl_src2Type      (io_out_1_bits_ctrl_src2Type),
    .io_out_bits_ctrl_fuType        (io_out_1_bits_ctrl_fuType),
    .io_out_bits_ctrl_fuOpType      (io_out_1_bits_ctrl_fuOpType),
    .io_out_bits_ctrl_rfSrc1        (io_out_1_bits_ctrl_rfSrc1),
    .io_out_bits_ctrl_rfSrc2        (io_out_1_bits_ctrl_rfSrc2),
    .io_out_bits_ctrl_rfWen         (io_out_1_bits_ctrl_rfWen),
    .io_out_bits_ctrl_rfDest        (io_out_1_bits_ctrl_rfDest),
    .io_out_bits_ctrl_isNutCoreTrap (io_out_1_bits_ctrl_isNutCoreTrap),
    .io_out_bits_data_imm           (io_out_1_bits_data_imm),
    .io_isWFI                       (_decoder2_io_isWFI),
    .intrVec__bore                  (decoder2_intrVec__bore),
    .vmEnable__bore                 (decoder2_vmEnable__bore)
  );	// src/main/scala/nutcore/frontend/IDU.scala:199:25
  assign _WIRE__bore = _GEN;	// src/main/scala/nutcore/frontend/IDU.scala:193:7, :219:35
endmodule

