// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module LSExecUnit(	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7
  input         clock,	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7
                reset,	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7
                io_in_valid,	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:290:14
  input  [63:0] io_in_bits_src1,	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:290:14
  input  [6:0]  io_in_bits_func,	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:290:14
  output        io_out_valid,	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:290:14
  output [63:0] io_out_bits,	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:290:14
  input  [63:0] io_wdata,	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:290:14
  input         io_dmem_req_ready,	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:290:14
  output        io_dmem_req_valid,	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:290:14
  output [38:0] io_dmem_req_bits_addr,	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:290:14
  output [3:0]  io_dmem_req_bits_cmd,	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:290:14
  output [7:0]  io_dmem_req_bits_wmask,	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:290:14
  output [63:0] io_dmem_req_bits_wdata,	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:290:14
  input         io_dmem_resp_valid,	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:290:14
  input  [63:0] io_dmem_resp_bits_rdata,	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:290:14
  output        io_isMMIO,	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:290:14
                io_dtlbPF,	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:290:14
                io_loadAddrMisaligned,	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:290:14
                io_storeAddrMisaligned,	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:290:14
                r_1__bore,
                r__bore,
                _WIRE__bore,
  output [63:0] io_in_bits_src1__bore,
  input         dtlbEnable__bore,
                isAMO__bore,
                dtlbPF__bore,
                dtlbFinish__bore
);

  wire        io_storeAddrMisaligned_0;	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:430:{35,57}
  wire        io_loadAddrMisaligned_0;	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:429:{35,47,57}
  wire        io_dmem_req_valid_0;	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:379:{27,49,75}
  reg  [63:0] addrLatch;	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:333:26
  wire        x5 = io_in_valid & io_in_bits_func[3];	// src/main/scala/nutcore/backend/fu/LSU.scala:55:39, src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:334:23
  wire        partialLoad = ~x5 & io_in_bits_func != 7'h3;	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:334:23, :335:{21,30,39}
  reg  [1:0]  state;	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:338:22
  wire        _GEN = io_dmem_req_ready & io_dmem_req_valid_0;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:379:{27,49,75}
  wire        _reqWmask_T_1 = io_in_bits_func[1:0] == 2'h1;	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:353:51, :365:83, src/main/scala/utils/LookupTree.scala:24:34
  wire        _reqWmask_T_2 = io_in_bits_func[1:0] == 2'h2;	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:354:51, :365:83, src/main/scala/utils/LookupTree.scala:24:34
  wire [14:0] reqWmask =
    {7'h0,
     {4'h0,
      {2'h0, {1'h0, ~(|(io_in_bits_func[1:0]))} | {2{_reqWmask_T_1}}}
        | {4{_reqWmask_T_2}}} | {8{&(io_in_bits_func[1:0])}}} << io_in_bits_src1[2:0];	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:306:{8,15}, :365:83, src/main/scala/utils/LookupTree.scala:24:{10,34}
  assign io_dmem_req_valid_0 =
    io_in_valid & state == 2'h0 & ~io_loadAddrMisaligned_0 & ~io_storeAddrMisaligned_0;	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:338:22, :351:18, :379:{27,49,52,75,78}, :429:{35,47,57}, :430:{35,57}
  reg  [63:0] rdataLatch;	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:388:27
  wire [31:0] _GEN_0 =
    (addrLatch[2:0] == 3'h0 ? rdataLatch[31:0] : 32'h0)
    | (addrLatch[2:0] == 3'h1 ? rdataLatch[39:8] : 32'h0)
    | (addrLatch[2:0] == 3'h2 ? rdataLatch[47:16] : 32'h0)
    | (addrLatch[2:0] == 3'h3 ? rdataLatch[55:24] : 32'h0)
    | (addrLatch[2:0] == 3'h4 ? rdataLatch[63:32] : 32'h0);	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7, :333:26, :388:27, :389:40, :391:27, :392:27, :393:27, :394:27, src/main/scala/utils/LookupTree.scala:24:{10,34}
  wire [23:0] _GEN_1 =
    _GEN_0[23:0] | (addrLatch[2:0] == 3'h5 ? rdataLatch[63:40] : 24'h0);	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7, :333:26, :388:27, :389:40, :395:27, src/main/scala/utils/LookupTree.scala:24:{10,34}
  wire [15:0] _GEN_2 =
    _GEN_1[15:0] | (addrLatch[2:0] == 3'h6 ? rdataLatch[63:48] : 16'h0);	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:333:26, :388:27, :389:40, :396:27, src/main/scala/utils/LookupTree.scala:24:{10,34}
  wire [7:0]  _rdataPartialLoad_T_9 =
    _GEN_2[7:0] | ((&(addrLatch[2:0])) ? rdataLatch[63:56] : 8'h0);	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:333:26, :388:27, :389:40, :397:27, src/main/scala/utils/LookupTree.scala:24:{10,34}
  wire        addrAligned =
    ~(|(io_in_bits_func[1:0])) | io_in_bits_func[1:0] == 2'h1 & ~(io_in_bits_src1[0])
    | io_in_bits_func[1:0] == 2'h2 & io_in_bits_src1[1:0] == 2'h0
    | (&(io_in_bits_func[1:0])) & io_in_bits_src1[2:0] == 3'h0;	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7, :306:15, :353:51, :354:51, :365:83, :416:{23,27}, :417:{23,29}, :418:29, src/main/scala/utils/LookupTree.scala:24:{10,34}
  assign io_loadAddrMisaligned_0 = io_in_valid & ~x5 & ~isAMO__bore & ~addrAligned;	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:334:23, :335:21, :429:{35,47,50,57,60}, src/main/scala/utils/LookupTree.scala:24:10
  assign io_storeAddrMisaligned_0 = io_in_valid & (x5 | isAMO__bore) & ~addrAligned;	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:334:23, :429:60, :430:{35,47,57}, src/main/scala/utils/LookupTree.scala:24:10
  wire        _GEN_3 = io_dmem_req_valid_0 & ~x5;	// src/main/scala/bus/simplebus/SimpleBus.scala:73:18, :104:27, src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:334:23, :379:{27,49,75}
  wire        _GEN_4 = _GEN_3 & _GEN;	// src/main/scala/bus/simplebus/SimpleBus.scala:104:27, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:434:{33,46}
  reg         r;	// src/main/scala/utils/StopWatch.scala:24:20
  reg         r_1;	// src/main/scala/utils/StopWatch.scala:24:20
  always @(posedge clock) begin	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7
    addrLatch <= io_in_bits_src1;	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:333:26
    rdataLatch <= io_dmem_resp_bits_rdata;	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:388:27
    if (reset) begin	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7
      state <= 2'h0;	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:338:22
      r <= 1'h0;	// src/main/scala/utils/StopWatch.scala:24:20
      r_1 <= 1'h0;	// src/main/scala/utils/StopWatch.scala:24:20
    end
    else begin	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7
      automatic logic [3:0][1:0] _GEN_5;	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:338:22, :351:18, :354:43, :359:36, :361:46, :362:32
      _GEN_5 =
        {{2'h0},
         {io_dmem_resp_valid ? {2{partialLoad}} : state},
         {dtlbFinish__bore & ~dtlbPF__bore
            ? 2'h2
            : dtlbFinish__bore & dtlbPF__bore ? 2'h0 : state},
         {_GEN & ~dtlbEnable__bore ? 2'h2 : _GEN & dtlbEnable__bore ? 2'h1 : state}};	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:335:30, :338:22, :351:18, :353:{27,43,51}, :354:{27,30,43,51}, :358:{24,36,44}, :359:{24,27,36,44}, :361:{46,54,60}, :362:32
      state <= _GEN_5[state];	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:338:22, :351:18, :354:43, :359:36, :361:46, :362:32
      r <= ~io_dmem_resp_valid & (_GEN_3 | r);	// src/main/scala/bus/simplebus/SimpleBus.scala:104:27, src/main/scala/utils/StopWatch.scala:24:20, :30:{20,24}, :31:{19,23}
      r_1 <= ~io_dmem_resp_valid & (io_dmem_req_valid_0 & x5 | r_1);	// src/main/scala/bus/simplebus/SimpleBus.scala:103:27, src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:334:23, :379:{27,49,75}, src/main/scala/utils/StopWatch.scala:24:20, :30:{20,24}, :31:{19,23}
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7
      automatic logic [31:0] _RANDOM[0:4];	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7
        for (logic [2:0] i = 3'h0; i < 3'h5; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7
        end	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7
        addrLatch = {_RANDOM[3'h0], _RANDOM[3'h1]};	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7, :333:26
        state = _RANDOM[3'h2][1:0];	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7, :338:22
        rdataLatch = {_RANDOM[3'h2][31:2], _RANDOM[3'h3], _RANDOM[3'h4][1:0]};	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7, :338:22, :388:27
        r = _RANDOM[3'h4][2];	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7, :388:27, src/main/scala/utils/StopWatch.scala:24:20
        r_1 = _RANDOM[3'h4][3];	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7, :388:27, src/main/scala/utils/StopWatch.scala:24:20
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out_valid =
    dtlbPF__bore & (|state) | io_loadAddrMisaligned_0 | io_storeAddrMisaligned_0
    | (partialLoad ? (&state) : io_dmem_resp_valid & state == 2'h2);	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7, :335:30, :338:22, :354:51, :382:{22,31,40,51,76,114,134,168,178}, :429:{35,47,57}, :430:{35,57}
  assign io_out_bits =
    partialLoad
      ? (io_in_bits_func == 7'h0
           ? {{56{_rdataPartialLoad_T_9[7]}}, _rdataPartialLoad_T_9}
           : 64'h0)
        | (io_in_bits_func == 7'h1
             ? {{48{_GEN_2[15]}}, _GEN_2[15:8], _rdataPartialLoad_T_9}
             : 64'h0)
        | (io_in_bits_func == 7'h2
             ? {{32{_GEN_0[31]}},
                _GEN_0[31:24],
                _GEN_1[23:16],
                _GEN_2[15:8],
                _rdataPartialLoad_T_9}
             : 64'h0) | (io_in_bits_func == 7'h4 ? {56'h0, _rdataPartialLoad_T_9} : 64'h0)
        | (io_in_bits_func == 7'h5 ? {48'h0, _GEN_2[15:8], _rdataPartialLoad_T_9} : 64'h0)
        | (io_in_bits_func == 7'h6
             ? {32'h0, _GEN_0[31:24], _GEN_1[23:16], _GEN_2[15:8], _rdataPartialLoad_T_9}
             : 64'h0)
      : io_dmem_resp_bits_rdata;	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7, :306:8, :335:30, :408:41, :409:41, :421:21, src/main/scala/utils/BitUtils.scala:41:20, :42:{41,46}, :49:41, src/main/scala/utils/LookupTree.scala:24:{10,34}
  assign io_dmem_req_valid = io_dmem_req_valid_0;	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7, :379:{27,49,75}
  assign io_dmem_req_bits_addr = io_in_bits_src1[38:0];	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7, :370:68
  assign io_dmem_req_bits_cmd = {3'h0, x5};	// src/main/scala/bus/simplebus/SimpleBus.scala:65:14, src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7, :334:23
  assign io_dmem_req_bits_wmask = reqWmask[7:0];	// src/main/scala/bus/simplebus/SimpleBus.scala:68:16, src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7, :306:8
  assign io_dmem_req_bits_wdata =
    ((|(io_in_bits_func[1:0])) ? 64'h0 : {8{io_wdata[7:0]}})
    | (_reqWmask_T_1 ? {4{io_wdata[15:0]}} : 64'h0)
    | (_reqWmask_T_2 ? {2{io_wdata[31:0]}} : 64'h0)
    | ((&(io_in_bits_func[1:0])) ? io_wdata : 64'h0);	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7, :310:{22,30}, :311:{22,30}, :312:{22,30}, :365:83, src/main/scala/utils/LookupTree.scala:24:{10,34}
  assign io_isMMIO = 1'h0;	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7
  assign io_dtlbPF = dtlbPF__bore;	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7
  assign io_loadAddrMisaligned = io_loadAddrMisaligned_0;	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7, :429:{35,47,57}
  assign io_storeAddrMisaligned = io_storeAddrMisaligned_0;	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7, :430:{35,57}
  assign r_1__bore = r_1;	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7, src/main/scala/utils/StopWatch.scala:24:20
  assign r__bore = r;	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7, src/main/scala/utils/StopWatch.scala:24:20
  assign _WIRE__bore = _GEN_4;	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7, :434:33
  assign io_in_bits_src1__bore = io_in_bits_src1;	// src/main/scala/nutcore/backend/fu/UnpipelinedLSU.scala:289:7
endmodule

