// Generated by CIRCT firtool-1.135.0
module NutShellSim(	// src/main/scala/sim/NutShellSim.scala:26:7
  input           clock,	// src/main/scala/sim/NutShellSim.scala:26:7
                  reset,	// src/main/scala/sim/NutShellSim.scala:26:7
  output          uart_out_valid,	// src/main/scala/sim/NutShellSim.scala:46:16
  output [7:0]    uart_out_ch,	// src/main/scala/sim/NutShellSim.scala:46:16
  output          uart_in_valid,	// src/main/scala/sim/NutShellSim.scala:46:16
  input  [7:0]    uart_in_ch,	// src/main/scala/sim/NutShellSim.scala:46:16
  output [2055:0] gatewayIn_packed_0_bore,	// difftest/src/main/scala/common/WiringControl.scala:30:55
  output [1159:0] gatewayIn_packed_1_bore,	// difftest/src/main/scala/common/WiringControl.scala:30:55
  output [172:0]  gatewayIn_packed_2_bore,	// difftest/src/main/scala/common/WiringControl.scala:30:55
  output [265:0]  gatewayIn_packed_3_bore,	// difftest/src/main/scala/common/WiringControl.scala:30:55
  output [253:0]  gatewayIn_packed_4_bore	// difftest/src/main/scala/common/WiringControl.scala:30:55
);

  wire        _mmio_io_rw_req_ready;	// src/main/scala/sim/NutShellSim.scala:33:20
  wire        _mmio_io_rw_resp_valid;	// src/main/scala/sim/NutShellSim.scala:33:20
  wire [3:0]  _mmio_io_rw_resp_bits_cmd;	// src/main/scala/sim/NutShellSim.scala:33:20
  wire [63:0] _mmio_io_rw_resp_bits_rdata;	// src/main/scala/sim/NutShellSim.scala:33:20
  wire        _mmio_io_meip;	// src/main/scala/sim/NutShellSim.scala:33:20
  wire        _mmio_io_dma_aw_valid;	// src/main/scala/sim/NutShellSim.scala:33:20
  wire [31:0] _mmio_io_dma_aw_bits_addr;	// src/main/scala/sim/NutShellSim.scala:33:20
  wire        _mmio_io_dma_w_valid;	// src/main/scala/sim/NutShellSim.scala:33:20
  wire [63:0] _mmio_io_dma_w_bits_data;	// src/main/scala/sim/NutShellSim.scala:33:20
  wire [7:0]  _mmio_io_dma_w_bits_strb;	// src/main/scala/sim/NutShellSim.scala:33:20
  wire        _mmio_io_dma_b_ready;	// src/main/scala/sim/NutShellSim.scala:33:20
  wire        _mmio_io_dma_ar_valid;	// src/main/scala/sim/NutShellSim.scala:33:20
  wire [31:0] _mmio_io_dma_ar_bits_addr;	// src/main/scala/sim/NutShellSim.scala:33:20
  wire        _mmio_io_dma_r_ready;	// src/main/scala/sim/NutShellSim.scala:33:20
  wire        _memdelay_io_in_aw_ready;	// src/main/scala/sim/NutShellSim.scala:32:24
  wire        _memdelay_io_in_w_ready;	// src/main/scala/sim/NutShellSim.scala:32:24
  wire        _memdelay_io_in_b_valid;	// src/main/scala/sim/NutShellSim.scala:32:24
  wire        _memdelay_io_in_ar_ready;	// src/main/scala/sim/NutShellSim.scala:32:24
  wire        _memdelay_io_in_r_valid;	// src/main/scala/sim/NutShellSim.scala:32:24
  wire [63:0] _memdelay_io_in_r_bits_data;	// src/main/scala/sim/NutShellSim.scala:32:24
  wire        _memdelay_io_in_r_bits_last;	// src/main/scala/sim/NutShellSim.scala:32:24
  wire        _memdelay_io_out_aw_valid;	// src/main/scala/sim/NutShellSim.scala:32:24
  wire [31:0] _memdelay_io_out_aw_bits_addr;	// src/main/scala/sim/NutShellSim.scala:32:24
  wire        _memdelay_io_out_w_valid;	// src/main/scala/sim/NutShellSim.scala:32:24
  wire [63:0] _memdelay_io_out_w_bits_data;	// src/main/scala/sim/NutShellSim.scala:32:24
  wire        _memdelay_io_out_w_bits_last;	// src/main/scala/sim/NutShellSim.scala:32:24
  wire        _memdelay_io_out_ar_valid;	// src/main/scala/sim/NutShellSim.scala:32:24
  wire [31:0] _memdelay_io_out_ar_bits_addr;	// src/main/scala/sim/NutShellSim.scala:32:24
  wire [7:0]  _memdelay_io_out_ar_bits_len;	// src/main/scala/sim/NutShellSim.scala:32:24
  wire        _mem_io_in_aw_ready;	// src/main/scala/sim/NutShellSim.scala:29:19
  wire        _mem_io_in_w_ready;	// src/main/scala/sim/NutShellSim.scala:29:19
  wire        _mem_io_in_b_valid;	// src/main/scala/sim/NutShellSim.scala:29:19
  wire        _mem_io_in_r_valid;	// src/main/scala/sim/NutShellSim.scala:29:19
  wire [63:0] _mem_io_in_r_bits_data;	// src/main/scala/sim/NutShellSim.scala:29:19
  wire        _mem_io_in_r_bits_last;	// src/main/scala/sim/NutShellSim.scala:29:19
  wire        _soc_io_mem_aw_valid;	// src/main/scala/sim/NutShellSim.scala:28:19
  wire [31:0] _soc_io_mem_aw_bits_addr;	// src/main/scala/sim/NutShellSim.scala:28:19
  wire [7:0]  _soc_io_mem_aw_bits_len;	// src/main/scala/sim/NutShellSim.scala:28:19
  wire        _soc_io_mem_w_valid;	// src/main/scala/sim/NutShellSim.scala:28:19
  wire [63:0] _soc_io_mem_w_bits_data;	// src/main/scala/sim/NutShellSim.scala:28:19
  wire        _soc_io_mem_w_bits_last;	// src/main/scala/sim/NutShellSim.scala:28:19
  wire        _soc_io_mem_ar_valid;	// src/main/scala/sim/NutShellSim.scala:28:19
  wire [31:0] _soc_io_mem_ar_bits_addr;	// src/main/scala/sim/NutShellSim.scala:28:19
  wire [7:0]  _soc_io_mem_ar_bits_len;	// src/main/scala/sim/NutShellSim.scala:28:19
  wire        _soc_io_mmio_req_valid;	// src/main/scala/sim/NutShellSim.scala:28:19
  wire [31:0] _soc_io_mmio_req_bits_addr;	// src/main/scala/sim/NutShellSim.scala:28:19
  wire [3:0]  _soc_io_mmio_req_bits_cmd;	// src/main/scala/sim/NutShellSim.scala:28:19
  wire [7:0]  _soc_io_mmio_req_bits_wmask;	// src/main/scala/sim/NutShellSim.scala:28:19
  wire [63:0] _soc_io_mmio_req_bits_wdata;	// src/main/scala/sim/NutShellSim.scala:28:19
  wire        _soc_io_mmio_resp_ready;	// src/main/scala/sim/NutShellSim.scala:28:19
  wire        _soc_io_frontend_aw_ready;	// src/main/scala/sim/NutShellSim.scala:28:19
  wire        _soc_io_frontend_w_ready;	// src/main/scala/sim/NutShellSim.scala:28:19
  wire        _soc_io_frontend_b_valid;	// src/main/scala/sim/NutShellSim.scala:28:19
  wire        _soc_io_frontend_ar_ready;	// src/main/scala/sim/NutShellSim.scala:28:19
  wire        _soc_io_frontend_r_valid;	// src/main/scala/sim/NutShellSim.scala:28:19
  wire [63:0] _soc_io_frontend_r_bits_data;	// src/main/scala/sim/NutShellSim.scala:28:19
  NutShell soc (	// src/main/scala/sim/NutShellSim.scala:28:19
    .clock                    (clock),
    .reset                    (reset),
    .io_mem_aw_ready          (_memdelay_io_in_aw_ready),	// src/main/scala/sim/NutShellSim.scala:32:24
    .io_mem_aw_valid          (_soc_io_mem_aw_valid),
    .io_mem_aw_bits_addr      (_soc_io_mem_aw_bits_addr),
    .io_mem_aw_bits_len       (_soc_io_mem_aw_bits_len),
    .io_mem_w_ready           (_memdelay_io_in_w_ready),	// src/main/scala/sim/NutShellSim.scala:32:24
    .io_mem_w_valid           (_soc_io_mem_w_valid),
    .io_mem_w_bits_data       (_soc_io_mem_w_bits_data),
    .io_mem_w_bits_last       (_soc_io_mem_w_bits_last),
    .io_mem_b_valid           (_memdelay_io_in_b_valid),	// src/main/scala/sim/NutShellSim.scala:32:24
    .io_mem_ar_ready          (_memdelay_io_in_ar_ready),	// src/main/scala/sim/NutShellSim.scala:32:24
    .io_mem_ar_valid          (_soc_io_mem_ar_valid),
    .io_mem_ar_bits_addr      (_soc_io_mem_ar_bits_addr),
    .io_mem_ar_bits_len       (_soc_io_mem_ar_bits_len),
    .io_mem_r_valid           (_memdelay_io_in_r_valid),	// src/main/scala/sim/NutShellSim.scala:32:24
    .io_mem_r_bits_data       (_memdelay_io_in_r_bits_data),	// src/main/scala/sim/NutShellSim.scala:32:24
    .io_mem_r_bits_last       (_memdelay_io_in_r_bits_last),	// src/main/scala/sim/NutShellSim.scala:32:24
    .io_mmio_req_ready        (_mmio_io_rw_req_ready),	// src/main/scala/sim/NutShellSim.scala:33:20
    .io_mmio_req_valid        (_soc_io_mmio_req_valid),
    .io_mmio_req_bits_addr    (_soc_io_mmio_req_bits_addr),
    .io_mmio_req_bits_cmd     (_soc_io_mmio_req_bits_cmd),
    .io_mmio_req_bits_wmask   (_soc_io_mmio_req_bits_wmask),
    .io_mmio_req_bits_wdata   (_soc_io_mmio_req_bits_wdata),
    .io_mmio_resp_ready       (_soc_io_mmio_resp_ready),
    .io_mmio_resp_valid       (_mmio_io_rw_resp_valid),	// src/main/scala/sim/NutShellSim.scala:33:20
    .io_mmio_resp_bits_cmd    (_mmio_io_rw_resp_bits_cmd),	// src/main/scala/sim/NutShellSim.scala:33:20
    .io_mmio_resp_bits_rdata  (_mmio_io_rw_resp_bits_rdata),	// src/main/scala/sim/NutShellSim.scala:33:20
    .io_frontend_aw_ready     (_soc_io_frontend_aw_ready),
    .io_frontend_aw_valid     (_mmio_io_dma_aw_valid),	// src/main/scala/sim/NutShellSim.scala:33:20
    .io_frontend_aw_bits_addr (_mmio_io_dma_aw_bits_addr),	// src/main/scala/sim/NutShellSim.scala:33:20
    .io_frontend_w_ready      (_soc_io_frontend_w_ready),
    .io_frontend_w_valid      (_mmio_io_dma_w_valid),	// src/main/scala/sim/NutShellSim.scala:33:20
    .io_frontend_w_bits_data  (_mmio_io_dma_w_bits_data),	// src/main/scala/sim/NutShellSim.scala:33:20
    .io_frontend_w_bits_strb  (_mmio_io_dma_w_bits_strb),	// src/main/scala/sim/NutShellSim.scala:33:20
    .io_frontend_b_ready      (_mmio_io_dma_b_ready),	// src/main/scala/sim/NutShellSim.scala:33:20
    .io_frontend_b_valid      (_soc_io_frontend_b_valid),
    .io_frontend_ar_ready     (_soc_io_frontend_ar_ready),
    .io_frontend_ar_valid     (_mmio_io_dma_ar_valid),	// src/main/scala/sim/NutShellSim.scala:33:20
    .io_frontend_ar_bits_addr (_mmio_io_dma_ar_bits_addr),	// src/main/scala/sim/NutShellSim.scala:33:20
    .io_frontend_r_ready      (_mmio_io_dma_r_ready),	// src/main/scala/sim/NutShellSim.scala:33:20
    .io_frontend_r_valid      (_soc_io_frontend_r_valid),
    .io_frontend_r_bits_data  (_soc_io_frontend_r_bits_data),
    .io_meip                  (_mmio_io_meip),	// src/main/scala/sim/NutShellSim.scala:33:20
    .gatewayIn_packed_0_bore  (gatewayIn_packed_0_bore),
    .gatewayIn_packed_1_bore  (gatewayIn_packed_1_bore),
    .gatewayIn_packed_2_bore  (gatewayIn_packed_2_bore),
    .gatewayIn_packed_3_bore  (gatewayIn_packed_3_bore),
    .gatewayIn_packed_4_bore  (gatewayIn_packed_4_bore)
  );	// src/main/scala/sim/NutShellSim.scala:28:19
  AXI4RAM mem (	// src/main/scala/sim/NutShellSim.scala:29:19
    .clock              (clock),
    .reset              (reset),
    .io_in_aw_ready     (_mem_io_in_aw_ready),
    .io_in_aw_valid     (_memdelay_io_out_aw_valid),	// src/main/scala/sim/NutShellSim.scala:32:24
    .io_in_aw_bits_addr (_memdelay_io_out_aw_bits_addr),	// src/main/scala/sim/NutShellSim.scala:32:24
    .io_in_w_ready      (_mem_io_in_w_ready),
    .io_in_w_valid      (_memdelay_io_out_w_valid),	// src/main/scala/sim/NutShellSim.scala:32:24
    .io_in_w_bits_data  (_memdelay_io_out_w_bits_data),	// src/main/scala/sim/NutShellSim.scala:32:24
    .io_in_w_bits_last  (_memdelay_io_out_w_bits_last),	// src/main/scala/sim/NutShellSim.scala:32:24
    .io_in_b_valid      (_mem_io_in_b_valid),
    .io_in_ar_valid     (_memdelay_io_out_ar_valid),	// src/main/scala/sim/NutShellSim.scala:32:24
    .io_in_ar_bits_addr (_memdelay_io_out_ar_bits_addr),	// src/main/scala/sim/NutShellSim.scala:32:24
    .io_in_ar_bits_len  (_memdelay_io_out_ar_bits_len),	// src/main/scala/sim/NutShellSim.scala:32:24
    .io_in_r_valid      (_mem_io_in_r_valid),
    .io_in_r_bits_data  (_mem_io_in_r_bits_data),
    .io_in_r_bits_last  (_mem_io_in_r_bits_last)
  );	// src/main/scala/sim/NutShellSim.scala:29:19
  AXI4Delayer memdelay (	// src/main/scala/sim/NutShellSim.scala:32:24
    .io_in_aw_ready      (_memdelay_io_in_aw_ready),
    .io_in_aw_valid      (_soc_io_mem_aw_valid),	// src/main/scala/sim/NutShellSim.scala:28:19
    .io_in_aw_bits_addr  (_soc_io_mem_aw_bits_addr),	// src/main/scala/sim/NutShellSim.scala:28:19
    .io_in_aw_bits_len   (_soc_io_mem_aw_bits_len),	// src/main/scala/sim/NutShellSim.scala:28:19
    .io_in_w_ready       (_memdelay_io_in_w_ready),
    .io_in_w_valid       (_soc_io_mem_w_valid),	// src/main/scala/sim/NutShellSim.scala:28:19
    .io_in_w_bits_data   (_soc_io_mem_w_bits_data),	// src/main/scala/sim/NutShellSim.scala:28:19
    .io_in_w_bits_last   (_soc_io_mem_w_bits_last),	// src/main/scala/sim/NutShellSim.scala:28:19
    .io_in_b_valid       (_memdelay_io_in_b_valid),
    .io_in_ar_ready      (_memdelay_io_in_ar_ready),
    .io_in_ar_valid      (_soc_io_mem_ar_valid),	// src/main/scala/sim/NutShellSim.scala:28:19
    .io_in_ar_bits_addr  (_soc_io_mem_ar_bits_addr),	// src/main/scala/sim/NutShellSim.scala:28:19
    .io_in_ar_bits_len   (_soc_io_mem_ar_bits_len),	// src/main/scala/sim/NutShellSim.scala:28:19
    .io_in_r_valid       (_memdelay_io_in_r_valid),
    .io_in_r_bits_data   (_memdelay_io_in_r_bits_data),
    .io_in_r_bits_last   (_memdelay_io_in_r_bits_last),
    .io_out_aw_ready     (_mem_io_in_aw_ready),	// src/main/scala/sim/NutShellSim.scala:29:19
    .io_out_aw_valid     (_memdelay_io_out_aw_valid),
    .io_out_aw_bits_addr (_memdelay_io_out_aw_bits_addr),
    .io_out_w_ready      (_mem_io_in_w_ready),	// src/main/scala/sim/NutShellSim.scala:29:19
    .io_out_w_valid      (_memdelay_io_out_w_valid),
    .io_out_w_bits_data  (_memdelay_io_out_w_bits_data),
    .io_out_w_bits_last  (_memdelay_io_out_w_bits_last),
    .io_out_b_valid      (_mem_io_in_b_valid),	// src/main/scala/sim/NutShellSim.scala:29:19
    .io_out_ar_valid     (_memdelay_io_out_ar_valid),
    .io_out_ar_bits_addr (_memdelay_io_out_ar_bits_addr),
    .io_out_ar_bits_len  (_memdelay_io_out_ar_bits_len),
    .io_out_r_valid      (_mem_io_in_r_valid),	// src/main/scala/sim/NutShellSim.scala:29:19
    .io_out_r_bits_data  (_mem_io_in_r_bits_data),	// src/main/scala/sim/NutShellSim.scala:29:19
    .io_out_r_bits_last  (_mem_io_in_r_bits_last)	// src/main/scala/sim/NutShellSim.scala:29:19
  );	// src/main/scala/sim/NutShellSim.scala:32:24
  SimMMIO mmio (	// src/main/scala/sim/NutShellSim.scala:33:20
    .clock                 (clock),
    .reset                 (reset),
    .io_rw_req_ready       (_mmio_io_rw_req_ready),
    .io_rw_req_valid       (_soc_io_mmio_req_valid),	// src/main/scala/sim/NutShellSim.scala:28:19
    .io_rw_req_bits_addr   (_soc_io_mmio_req_bits_addr),	// src/main/scala/sim/NutShellSim.scala:28:19
    .io_rw_req_bits_cmd    (_soc_io_mmio_req_bits_cmd),	// src/main/scala/sim/NutShellSim.scala:28:19
    .io_rw_req_bits_wmask  (_soc_io_mmio_req_bits_wmask),	// src/main/scala/sim/NutShellSim.scala:28:19
    .io_rw_req_bits_wdata  (_soc_io_mmio_req_bits_wdata),	// src/main/scala/sim/NutShellSim.scala:28:19
    .io_rw_resp_ready      (_soc_io_mmio_resp_ready),	// src/main/scala/sim/NutShellSim.scala:28:19
    .io_rw_resp_valid      (_mmio_io_rw_resp_valid),
    .io_rw_resp_bits_cmd   (_mmio_io_rw_resp_bits_cmd),
    .io_rw_resp_bits_rdata (_mmio_io_rw_resp_bits_rdata),
    .io_meip               (_mmio_io_meip),
    .io_dma_aw_ready       (_soc_io_frontend_aw_ready),	// src/main/scala/sim/NutShellSim.scala:28:19
    .io_dma_aw_valid       (_mmio_io_dma_aw_valid),
    .io_dma_aw_bits_addr   (_mmio_io_dma_aw_bits_addr),
    .io_dma_w_ready        (_soc_io_frontend_w_ready),	// src/main/scala/sim/NutShellSim.scala:28:19
    .io_dma_w_valid        (_mmio_io_dma_w_valid),
    .io_dma_w_bits_data    (_mmio_io_dma_w_bits_data),
    .io_dma_w_bits_strb    (_mmio_io_dma_w_bits_strb),
    .io_dma_b_ready        (_mmio_io_dma_b_ready),
    .io_dma_b_valid        (_soc_io_frontend_b_valid),	// src/main/scala/sim/NutShellSim.scala:28:19
    .io_dma_ar_ready       (_soc_io_frontend_ar_ready),	// src/main/scala/sim/NutShellSim.scala:28:19
    .io_dma_ar_valid       (_mmio_io_dma_ar_valid),
    .io_dma_ar_bits_addr   (_mmio_io_dma_ar_bits_addr),
    .io_dma_r_ready        (_mmio_io_dma_r_ready),
    .io_dma_r_valid        (_soc_io_frontend_r_valid),	// src/main/scala/sim/NutShellSim.scala:28:19
    .io_dma_r_bits_data    (_soc_io_frontend_r_bits_data),	// src/main/scala/sim/NutShellSim.scala:28:19
    .io_uart_out_valid     (uart_out_valid),
    .io_uart_out_ch        (uart_out_ch),
    .io_uart_in_valid      (uart_in_valid),
    .io_uart_in_ch         (uart_in_ch)
  );	// src/main/scala/sim/NutShellSim.scala:33:20
endmodule

