// Generated by CIRCT firtool-1.135.0
module PreprocessEndpoint(	// difftest/src/main/scala/Preprocess.scala:102:7
  input         in_4_valid,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_4_skip,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_4_isRVC,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_4_rfwen,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_4_fpwen,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_4_vecwen,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_4_v0wen,	// difftest/src/main/scala/Preprocess.scala:103:14
  input  [4:0]  in_4_wpdest,	// difftest/src/main/scala/Preprocess.scala:103:14
  input  [7:0]  in_4_wdest,	// difftest/src/main/scala/Preprocess.scala:103:14
  input  [4:0]  in_4_otherwpdest_0,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_4_otherwpdest_1,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_4_otherwpdest_2,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_4_otherwpdest_3,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_4_otherwpdest_4,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_4_otherwpdest_5,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_4_otherwpdest_6,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_4_otherwpdest_7,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_4_otherwpdest_8,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_4_otherwpdest_9,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_4_otherwpdest_10,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_4_otherwpdest_11,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_4_otherwpdest_12,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_4_otherwpdest_13,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_4_otherwpdest_14,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_4_otherwpdest_15,	// difftest/src/main/scala/Preprocess.scala:103:14
  input  [63:0] in_4_pc,	// difftest/src/main/scala/Preprocess.scala:103:14
  input  [31:0] in_4_instr,	// difftest/src/main/scala/Preprocess.scala:103:14
  input  [9:0]  in_4_robIdx,	// difftest/src/main/scala/Preprocess.scala:103:14
  input  [6:0]  in_4_lqIdx,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_4_sqIdx,	// difftest/src/main/scala/Preprocess.scala:103:14
  input         in_4_isLoad,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_4_isStore,	// difftest/src/main/scala/Preprocess.scala:103:14
  input  [7:0]  in_4_nFused,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_4_special,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_4_coreid,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_4_index,	// difftest/src/main/scala/Preprocess.scala:103:14
  input         in_3_hasTrap,	// difftest/src/main/scala/Preprocess.scala:103:14
  input  [63:0] in_3_cycleCnt,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_3_instrCnt,	// difftest/src/main/scala/Preprocess.scala:103:14
  input         in_3_hasWFI,	// difftest/src/main/scala/Preprocess.scala:103:14
  input  [63:0] in_3_code,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_3_pc,	// difftest/src/main/scala/Preprocess.scala:103:14
  input  [7:0]  in_3_coreid,	// difftest/src/main/scala/Preprocess.scala:103:14
  input         in_2_valid,	// difftest/src/main/scala/Preprocess.scala:103:14
  input  [31:0] in_2_interrupt,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_2_exception,	// difftest/src/main/scala/Preprocess.scala:103:14
  input  [63:0] in_2_exceptionPC,	// difftest/src/main/scala/Preprocess.scala:103:14
  input  [31:0] in_2_exceptionInst,	// difftest/src/main/scala/Preprocess.scala:103:14
  input         in_2_hasNMI,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_2_virtualInterruptIsHvictlInject,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_2_irToHS,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_2_irToVS,	// difftest/src/main/scala/Preprocess.scala:103:14
  input  [7:0]  in_2_coreid,	// difftest/src/main/scala/Preprocess.scala:103:14
  input  [63:0] in_1_privilegeMode,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_1_mstatus,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_1_sstatus,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_1_mepc,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_1_sepc,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_1_mtval,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_1_stval,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_1_mtvec,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_1_stvec,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_1_mcause,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_1_scause,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_1_satp,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_1_mip,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_1_mie,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_1_mscratch,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_1_sscratch,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_1_mideleg,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_1_medeleg,	// difftest/src/main/scala/Preprocess.scala:103:14
  input  [7:0]  in_1_coreid,	// difftest/src/main/scala/Preprocess.scala:103:14
  input  [63:0] in_0_value_0,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_0_value_1,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_0_value_2,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_0_value_3,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_0_value_4,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_0_value_5,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_0_value_6,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_0_value_7,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_0_value_8,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_0_value_9,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_0_value_10,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_0_value_11,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_0_value_12,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_0_value_13,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_0_value_14,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_0_value_15,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_0_value_16,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_0_value_17,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_0_value_18,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_0_value_19,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_0_value_20,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_0_value_21,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_0_value_22,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_0_value_23,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_0_value_24,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_0_value_25,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_0_value_26,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_0_value_27,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_0_value_28,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_0_value_29,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_0_value_30,	// difftest/src/main/scala/Preprocess.scala:103:14
                in_0_value_31,	// difftest/src/main/scala/Preprocess.scala:103:14
  input  [7:0]  in_0_coreid,	// difftest/src/main/scala/Preprocess.scala:103:14
  output        out_5_valid,	// difftest/src/main/scala/Preprocess.scala:120:15
  output [63:0] out_5_data,	// difftest/src/main/scala/Preprocess.scala:120:15
  output [7:0]  out_5_coreid,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_5_index,	// difftest/src/main/scala/Preprocess.scala:120:15
  output [63:0] out_4_value_0,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_4_value_1,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_4_value_2,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_4_value_3,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_4_value_4,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_4_value_5,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_4_value_6,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_4_value_7,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_4_value_8,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_4_value_9,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_4_value_10,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_4_value_11,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_4_value_12,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_4_value_13,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_4_value_14,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_4_value_15,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_4_value_16,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_4_value_17,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_4_value_18,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_4_value_19,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_4_value_20,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_4_value_21,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_4_value_22,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_4_value_23,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_4_value_24,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_4_value_25,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_4_value_26,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_4_value_27,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_4_value_28,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_4_value_29,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_4_value_30,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_4_value_31,	// difftest/src/main/scala/Preprocess.scala:120:15
  output [7:0]  out_4_coreid,	// difftest/src/main/scala/Preprocess.scala:120:15
  output        out_3_valid,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_3_skip,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_3_isRVC,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_3_rfwen,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_3_fpwen,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_3_vecwen,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_3_v0wen,	// difftest/src/main/scala/Preprocess.scala:120:15
  output [4:0]  out_3_wpdest,	// difftest/src/main/scala/Preprocess.scala:120:15
  output [7:0]  out_3_wdest,	// difftest/src/main/scala/Preprocess.scala:120:15
  output [4:0]  out_3_otherwpdest_0,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_3_otherwpdest_1,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_3_otherwpdest_2,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_3_otherwpdest_3,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_3_otherwpdest_4,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_3_otherwpdest_5,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_3_otherwpdest_6,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_3_otherwpdest_7,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_3_otherwpdest_8,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_3_otherwpdest_9,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_3_otherwpdest_10,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_3_otherwpdest_11,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_3_otherwpdest_12,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_3_otherwpdest_13,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_3_otherwpdest_14,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_3_otherwpdest_15,	// difftest/src/main/scala/Preprocess.scala:120:15
  output [63:0] out_3_pc,	// difftest/src/main/scala/Preprocess.scala:120:15
  output [31:0] out_3_instr,	// difftest/src/main/scala/Preprocess.scala:120:15
  output [9:0]  out_3_robIdx,	// difftest/src/main/scala/Preprocess.scala:120:15
  output [6:0]  out_3_lqIdx,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_3_sqIdx,	// difftest/src/main/scala/Preprocess.scala:120:15
  output        out_3_isLoad,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_3_isStore,	// difftest/src/main/scala/Preprocess.scala:120:15
  output [7:0]  out_3_nFused,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_3_special,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_3_coreid,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_3_index,	// difftest/src/main/scala/Preprocess.scala:120:15
  output        out_2_hasTrap,	// difftest/src/main/scala/Preprocess.scala:120:15
  output [63:0] out_2_cycleCnt,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_2_instrCnt,	// difftest/src/main/scala/Preprocess.scala:120:15
  output        out_2_hasWFI,	// difftest/src/main/scala/Preprocess.scala:120:15
  output [63:0] out_2_code,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_2_pc,	// difftest/src/main/scala/Preprocess.scala:120:15
  output [7:0]  out_2_coreid,	// difftest/src/main/scala/Preprocess.scala:120:15
  output        out_1_valid,	// difftest/src/main/scala/Preprocess.scala:120:15
  output [31:0] out_1_interrupt,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_1_exception,	// difftest/src/main/scala/Preprocess.scala:120:15
  output [63:0] out_1_exceptionPC,	// difftest/src/main/scala/Preprocess.scala:120:15
  output [31:0] out_1_exceptionInst,	// difftest/src/main/scala/Preprocess.scala:120:15
  output        out_1_hasNMI,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_1_virtualInterruptIsHvictlInject,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_1_irToHS,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_1_irToVS,	// difftest/src/main/scala/Preprocess.scala:120:15
  output [7:0]  out_1_coreid,	// difftest/src/main/scala/Preprocess.scala:120:15
  output [63:0] out_0_privilegeMode,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_0_mstatus,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_0_sstatus,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_0_mepc,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_0_sepc,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_0_mtval,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_0_stval,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_0_mtvec,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_0_stvec,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_0_mcause,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_0_scause,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_0_satp,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_0_mip,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_0_mie,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_0_mscratch,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_0_sscratch,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_0_mideleg,	// difftest/src/main/scala/Preprocess.scala:120:15
                out_0_medeleg,	// difftest/src/main/scala/Preprocess.scala:120:15
  output [7:0]  out_0_coreid	// difftest/src/main/scala/Preprocess.scala:120:15
);

  wire [31:0][63:0] _GEN =
    {{in_0_value_31},
     {in_0_value_30},
     {in_0_value_29},
     {in_0_value_28},
     {in_0_value_27},
     {in_0_value_26},
     {in_0_value_25},
     {in_0_value_24},
     {in_0_value_23},
     {in_0_value_22},
     {in_0_value_21},
     {in_0_value_20},
     {in_0_value_19},
     {in_0_value_18},
     {in_0_value_17},
     {in_0_value_16},
     {in_0_value_15},
     {in_0_value_14},
     {in_0_value_13},
     {in_0_value_12},
     {in_0_value_11},
     {in_0_value_10},
     {in_0_value_9},
     {in_0_value_8},
     {in_0_value_7},
     {in_0_value_6},
     {in_0_value_5},
     {in_0_value_4},
     {in_0_value_3},
     {in_0_value_2},
     {in_0_value_1},
     {in_0_value_0}};	// difftest/src/main/scala/Preprocess.scala:83:21
  assign out_5_valid = in_4_valid & (in_4_rfwen | in_4_fpwen);	// difftest/src/main/scala/Preprocess.scala:82:{27,39}, :102:7
  assign out_5_data = in_4_fpwen ? 64'h0 : _GEN[in_4_wpdest];	// difftest/src/main/scala/Preprocess.scala:83:21, :102:7
  assign out_5_coreid = in_4_coreid;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_5_index = in_4_index;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_4_value_0 = in_0_value_0;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_4_value_1 = in_0_value_1;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_4_value_2 = in_0_value_2;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_4_value_3 = in_0_value_3;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_4_value_4 = in_0_value_4;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_4_value_5 = in_0_value_5;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_4_value_6 = in_0_value_6;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_4_value_7 = in_0_value_7;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_4_value_8 = in_0_value_8;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_4_value_9 = in_0_value_9;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_4_value_10 = in_0_value_10;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_4_value_11 = in_0_value_11;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_4_value_12 = in_0_value_12;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_4_value_13 = in_0_value_13;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_4_value_14 = in_0_value_14;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_4_value_15 = in_0_value_15;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_4_value_16 = in_0_value_16;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_4_value_17 = in_0_value_17;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_4_value_18 = in_0_value_18;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_4_value_19 = in_0_value_19;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_4_value_20 = in_0_value_20;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_4_value_21 = in_0_value_21;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_4_value_22 = in_0_value_22;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_4_value_23 = in_0_value_23;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_4_value_24 = in_0_value_24;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_4_value_25 = in_0_value_25;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_4_value_26 = in_0_value_26;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_4_value_27 = in_0_value_27;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_4_value_28 = in_0_value_28;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_4_value_29 = in_0_value_29;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_4_value_30 = in_0_value_30;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_4_value_31 = in_0_value_31;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_4_coreid = in_0_coreid;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_valid = in_4_valid;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_skip = in_4_skip;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_isRVC = in_4_isRVC;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_rfwen = in_4_rfwen;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_fpwen = in_4_fpwen;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_vecwen = in_4_vecwen;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_v0wen = in_4_v0wen;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_wpdest = in_4_wpdest;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_wdest = in_4_wdest;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_otherwpdest_0 = in_4_otherwpdest_0;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_otherwpdest_1 = in_4_otherwpdest_1;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_otherwpdest_2 = in_4_otherwpdest_2;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_otherwpdest_3 = in_4_otherwpdest_3;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_otherwpdest_4 = in_4_otherwpdest_4;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_otherwpdest_5 = in_4_otherwpdest_5;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_otherwpdest_6 = in_4_otherwpdest_6;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_otherwpdest_7 = in_4_otherwpdest_7;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_otherwpdest_8 = in_4_otherwpdest_8;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_otherwpdest_9 = in_4_otherwpdest_9;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_otherwpdest_10 = in_4_otherwpdest_10;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_otherwpdest_11 = in_4_otherwpdest_11;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_otherwpdest_12 = in_4_otherwpdest_12;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_otherwpdest_13 = in_4_otherwpdest_13;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_otherwpdest_14 = in_4_otherwpdest_14;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_otherwpdest_15 = in_4_otherwpdest_15;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_pc = in_4_pc;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_instr = in_4_instr;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_robIdx = in_4_robIdx;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_lqIdx = in_4_lqIdx;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_sqIdx = in_4_sqIdx;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_isLoad = in_4_isLoad;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_isStore = in_4_isStore;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_nFused = in_4_nFused;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_special = in_4_special;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_coreid = in_4_coreid;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_3_index = in_4_index;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_2_hasTrap = in_3_hasTrap;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_2_cycleCnt = in_3_cycleCnt;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_2_instrCnt = in_3_instrCnt;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_2_hasWFI = in_3_hasWFI;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_2_code = in_3_code;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_2_pc = in_3_pc;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_2_coreid = in_3_coreid;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_1_valid = in_2_valid;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_1_interrupt = in_2_interrupt;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_1_exception = in_2_exception;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_1_exceptionPC = in_2_exceptionPC;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_1_exceptionInst = in_2_exceptionInst;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_1_hasNMI = in_2_hasNMI;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_1_virtualInterruptIsHvictlInject = in_2_virtualInterruptIsHvictlInject;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_1_irToHS = in_2_irToHS;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_1_irToVS = in_2_irToVS;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_1_coreid = in_2_coreid;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_0_privilegeMode = in_1_privilegeMode;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_0_mstatus = in_1_mstatus;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_0_sstatus = in_1_sstatus;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_0_mepc = in_1_mepc;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_0_sepc = in_1_sepc;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_0_mtval = in_1_mtval;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_0_stval = in_1_stval;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_0_mtvec = in_1_mtvec;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_0_stvec = in_1_stvec;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_0_mcause = in_1_mcause;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_0_scause = in_1_scause;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_0_satp = in_1_satp;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_0_mip = in_1_mip;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_0_mie = in_1_mie;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_0_mscratch = in_1_mscratch;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_0_sscratch = in_1_sscratch;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_0_mideleg = in_1_mideleg;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_0_medeleg = in_1_medeleg;	// difftest/src/main/scala/Preprocess.scala:102:7
  assign out_0_coreid = in_1_coreid;	// difftest/src/main/scala/Preprocess.scala:102:7
endmodule

