// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS


// Include rmemory initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
// VCS coverage exclude_file
module ram_4x147(	// src/main/scala/utils/FlushableQueue.scala:23:24
  input  [1:0]   R0_addr,
  input          R0_en,
                 R0_clk,
  output [146:0] R0_data,
  input  [1:0]   W0_addr,
  input          W0_en,
                 W0_clk,
  input  [146:0] W0_data
);

  reg [146:0] Memory[0:3];	// src/main/scala/utils/FlushableQueue.scala:23:24
  always @(posedge W0_clk) begin	// src/main/scala/utils/FlushableQueue.scala:23:24
    if (W0_en)	// src/main/scala/utils/FlushableQueue.scala:23:24
      Memory[W0_addr] <= W0_data;	// src/main/scala/utils/FlushableQueue.scala:23:24
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/utils/FlushableQueue.scala:23:24
    reg [159:0] _RANDOM_MEM;	// src/main/scala/utils/FlushableQueue.scala:23:24
    initial begin	// src/main/scala/utils/FlushableQueue.scala:23:24
      `INIT_RANDOM_PROLOG_	// src/main/scala/utils/FlushableQueue.scala:23:24
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/utils/FlushableQueue.scala:23:24
        for (logic [2:0] i = 3'h0; i < 3'h4; i += 3'h1) begin
          for (logic [7:0] j = 8'h0; j < 8'hA0; j += 8'h20) begin
            _RANDOM_MEM[j +: 32] = `RANDOM;	// src/main/scala/utils/FlushableQueue.scala:23:24
          end
          Memory[i[1:0]] = _RANDOM_MEM[146:0];	// src/main/scala/utils/FlushableQueue.scala:23:24
        end
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 147'bx;	// src/main/scala/utils/FlushableQueue.scala:23:24
endmodule

