// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS


// Include rmemory initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
// VCS coverage exclude_file
module rf_32x64(	// src/main/scala/nutcore/RF.scala:30:15
  input  [4:0]  R0_addr,
  input         R0_en,
                R0_clk,
  output [63:0] R0_data,
  input  [4:0]  R1_addr,
  input         R1_en,
                R1_clk,
  output [63:0] R1_data,
  input  [4:0]  R2_addr,
  input         R2_en,
                R2_clk,
  output [63:0] R2_data,
  input  [4:0]  R3_addr,
  input         R3_en,
                R3_clk,
  output [63:0] R3_data,
  input  [4:0]  R4_addr,
  input         R4_en,
                R4_clk,
  output [63:0] R4_data,
  input  [4:0]  R5_addr,
  input         R5_en,
                R5_clk,
  output [63:0] R5_data,
  input  [4:0]  R6_addr,
  input         R6_en,
                R6_clk,
  output [63:0] R6_data,
  input  [4:0]  R7_addr,
  input         R7_en,
                R7_clk,
  output [63:0] R7_data,
  input  [4:0]  R8_addr,
  input         R8_en,
                R8_clk,
  output [63:0] R8_data,
  input  [4:0]  R9_addr,
  input         R9_en,
                R9_clk,
  output [63:0] R9_data,
  input  [4:0]  R10_addr,
  input         R10_en,
                R10_clk,
  output [63:0] R10_data,
  input  [4:0]  R11_addr,
  input         R11_en,
                R11_clk,
  output [63:0] R11_data,
  input  [4:0]  R12_addr,
  input         R12_en,
                R12_clk,
  output [63:0] R12_data,
  input  [4:0]  R13_addr,
  input         R13_en,
                R13_clk,
  output [63:0] R13_data,
  input  [4:0]  R14_addr,
  input         R14_en,
                R14_clk,
  output [63:0] R14_data,
  input  [4:0]  R15_addr,
  input         R15_en,
                R15_clk,
  output [63:0] R15_data,
  input  [4:0]  R16_addr,
  input         R16_en,
                R16_clk,
  output [63:0] R16_data,
  input  [4:0]  R17_addr,
  input         R17_en,
                R17_clk,
  output [63:0] R17_data,
  input  [4:0]  R18_addr,
  input         R18_en,
                R18_clk,
  output [63:0] R18_data,
  input  [4:0]  R19_addr,
  input         R19_en,
                R19_clk,
  output [63:0] R19_data,
  input  [4:0]  R20_addr,
  input         R20_en,
                R20_clk,
  output [63:0] R20_data,
  input  [4:0]  R21_addr,
  input         R21_en,
                R21_clk,
  output [63:0] R21_data,
  input  [4:0]  R22_addr,
  input         R22_en,
                R22_clk,
  output [63:0] R22_data,
  input  [4:0]  R23_addr,
  input         R23_en,
                R23_clk,
  output [63:0] R23_data,
  input  [4:0]  R24_addr,
  input         R24_en,
                R24_clk,
  output [63:0] R24_data,
  input  [4:0]  R25_addr,
  input         R25_en,
                R25_clk,
  output [63:0] R25_data,
  input  [4:0]  R26_addr,
  input         R26_en,
                R26_clk,
  output [63:0] R26_data,
  input  [4:0]  R27_addr,
  input         R27_en,
                R27_clk,
  output [63:0] R27_data,
  input  [4:0]  R28_addr,
  input         R28_en,
                R28_clk,
  output [63:0] R28_data,
  input  [4:0]  R29_addr,
  input         R29_en,
                R29_clk,
  output [63:0] R29_data,
  input  [4:0]  R30_addr,
  input         R30_en,
                R30_clk,
  output [63:0] R30_data,
  input  [4:0]  R31_addr,
  input         R31_en,
                R31_clk,
  output [63:0] R31_data,
  input  [4:0]  R32_addr,
  input         R32_en,
                R32_clk,
  output [63:0] R32_data,
  input  [4:0]  W0_addr,
  input         W0_en,
                W0_clk,
  input  [63:0] W0_data
);

  reg [63:0] Memory[0:31];	// src/main/scala/nutcore/RF.scala:30:15
  always @(posedge W0_clk) begin	// src/main/scala/nutcore/RF.scala:30:15
    if (W0_en)	// src/main/scala/nutcore/RF.scala:30:15
      Memory[W0_addr] <= W0_data;	// src/main/scala/nutcore/RF.scala:30:15
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/nutcore/RF.scala:30:15
    reg [63:0] _RANDOM_MEM;	// src/main/scala/nutcore/RF.scala:30:15
    initial begin	// src/main/scala/nutcore/RF.scala:30:15
      `INIT_RANDOM_PROLOG_	// src/main/scala/nutcore/RF.scala:30:15
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/nutcore/RF.scala:30:15
        for (logic [5:0] i = 6'h0; i < 6'h20; i += 6'h1) begin
          for (logic [6:0] j = 7'h0; j < 7'h40; j += 7'h20) begin
            _RANDOM_MEM[j[5:0] +: 32] = `RANDOM;	// src/main/scala/nutcore/RF.scala:30:15
          end
          Memory[i[4:0]] = _RANDOM_MEM;	// src/main/scala/nutcore/RF.scala:30:15
        end
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 64'bx;	// src/main/scala/nutcore/RF.scala:30:15
  assign R1_data = R1_en ? Memory[R1_addr] : 64'bx;	// src/main/scala/nutcore/RF.scala:30:15
  assign R2_data = R2_en ? Memory[R2_addr] : 64'bx;	// src/main/scala/nutcore/RF.scala:30:15
  assign R3_data = R3_en ? Memory[R3_addr] : 64'bx;	// src/main/scala/nutcore/RF.scala:30:15
  assign R4_data = R4_en ? Memory[R4_addr] : 64'bx;	// src/main/scala/nutcore/RF.scala:30:15
  assign R5_data = R5_en ? Memory[R5_addr] : 64'bx;	// src/main/scala/nutcore/RF.scala:30:15
  assign R6_data = R6_en ? Memory[R6_addr] : 64'bx;	// src/main/scala/nutcore/RF.scala:30:15
  assign R7_data = R7_en ? Memory[R7_addr] : 64'bx;	// src/main/scala/nutcore/RF.scala:30:15
  assign R8_data = R8_en ? Memory[R8_addr] : 64'bx;	// src/main/scala/nutcore/RF.scala:30:15
  assign R9_data = R9_en ? Memory[R9_addr] : 64'bx;	// src/main/scala/nutcore/RF.scala:30:15
  assign R10_data = R10_en ? Memory[R10_addr] : 64'bx;	// src/main/scala/nutcore/RF.scala:30:15
  assign R11_data = R11_en ? Memory[R11_addr] : 64'bx;	// src/main/scala/nutcore/RF.scala:30:15
  assign R12_data = R12_en ? Memory[R12_addr] : 64'bx;	// src/main/scala/nutcore/RF.scala:30:15
  assign R13_data = R13_en ? Memory[R13_addr] : 64'bx;	// src/main/scala/nutcore/RF.scala:30:15
  assign R14_data = R14_en ? Memory[R14_addr] : 64'bx;	// src/main/scala/nutcore/RF.scala:30:15
  assign R15_data = R15_en ? Memory[R15_addr] : 64'bx;	// src/main/scala/nutcore/RF.scala:30:15
  assign R16_data = R16_en ? Memory[R16_addr] : 64'bx;	// src/main/scala/nutcore/RF.scala:30:15
  assign R17_data = R17_en ? Memory[R17_addr] : 64'bx;	// src/main/scala/nutcore/RF.scala:30:15
  assign R18_data = R18_en ? Memory[R18_addr] : 64'bx;	// src/main/scala/nutcore/RF.scala:30:15
  assign R19_data = R19_en ? Memory[R19_addr] : 64'bx;	// src/main/scala/nutcore/RF.scala:30:15
  assign R20_data = R20_en ? Memory[R20_addr] : 64'bx;	// src/main/scala/nutcore/RF.scala:30:15
  assign R21_data = R21_en ? Memory[R21_addr] : 64'bx;	// src/main/scala/nutcore/RF.scala:30:15
  assign R22_data = R22_en ? Memory[R22_addr] : 64'bx;	// src/main/scala/nutcore/RF.scala:30:15
  assign R23_data = R23_en ? Memory[R23_addr] : 64'bx;	// src/main/scala/nutcore/RF.scala:30:15
  assign R24_data = R24_en ? Memory[R24_addr] : 64'bx;	// src/main/scala/nutcore/RF.scala:30:15
  assign R25_data = R25_en ? Memory[R25_addr] : 64'bx;	// src/main/scala/nutcore/RF.scala:30:15
  assign R26_data = R26_en ? Memory[R26_addr] : 64'bx;	// src/main/scala/nutcore/RF.scala:30:15
  assign R27_data = R27_en ? Memory[R27_addr] : 64'bx;	// src/main/scala/nutcore/RF.scala:30:15
  assign R28_data = R28_en ? Memory[R28_addr] : 64'bx;	// src/main/scala/nutcore/RF.scala:30:15
  assign R29_data = R29_en ? Memory[R29_addr] : 64'bx;	// src/main/scala/nutcore/RF.scala:30:15
  assign R30_data = R30_en ? Memory[R30_addr] : 64'bx;	// src/main/scala/nutcore/RF.scala:30:15
  assign R31_data = R31_en ? Memory[R31_addr] : 64'bx;	// src/main/scala/nutcore/RF.scala:30:15
  assign R32_data = R32_en ? Memory[R32_addr] : 64'bx;	// src/main/scala/nutcore/RF.scala:30:15
endmodule

