// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module SimpleBus2AXI4Converter(	// src/main/scala/bus/simplebus/ToAXI4.scala:145:7
  input         clock,	// src/main/scala/bus/simplebus/ToAXI4.scala:145:7
                reset,	// src/main/scala/bus/simplebus/ToAXI4.scala:145:7
  output        io_in_req_ready,	// src/main/scala/bus/simplebus/ToAXI4.scala:146:14
  input         io_in_req_valid,	// src/main/scala/bus/simplebus/ToAXI4.scala:146:14
  input  [31:0] io_in_req_bits_addr,	// src/main/scala/bus/simplebus/ToAXI4.scala:146:14
  input  [3:0]  io_in_req_bits_cmd,	// src/main/scala/bus/simplebus/ToAXI4.scala:146:14
  input  [63:0] io_in_req_bits_wdata,	// src/main/scala/bus/simplebus/ToAXI4.scala:146:14
  output        io_in_resp_valid,	// src/main/scala/bus/simplebus/ToAXI4.scala:146:14
  output [3:0]  io_in_resp_bits_cmd,	// src/main/scala/bus/simplebus/ToAXI4.scala:146:14
  output [63:0] io_in_resp_bits_rdata,	// src/main/scala/bus/simplebus/ToAXI4.scala:146:14
  input         io_out_aw_ready,	// src/main/scala/bus/simplebus/ToAXI4.scala:146:14
  output        io_out_aw_valid,	// src/main/scala/bus/simplebus/ToAXI4.scala:146:14
  output [31:0] io_out_aw_bits_addr,	// src/main/scala/bus/simplebus/ToAXI4.scala:146:14
  output [7:0]  io_out_aw_bits_len,	// src/main/scala/bus/simplebus/ToAXI4.scala:146:14
  input         io_out_w_ready,	// src/main/scala/bus/simplebus/ToAXI4.scala:146:14
  output        io_out_w_valid,	// src/main/scala/bus/simplebus/ToAXI4.scala:146:14
  output [63:0] io_out_w_bits_data,	// src/main/scala/bus/simplebus/ToAXI4.scala:146:14
  output        io_out_w_bits_last,	// src/main/scala/bus/simplebus/ToAXI4.scala:146:14
  input         io_out_b_valid,	// src/main/scala/bus/simplebus/ToAXI4.scala:146:14
                io_out_ar_ready,	// src/main/scala/bus/simplebus/ToAXI4.scala:146:14
  output        io_out_ar_valid,	// src/main/scala/bus/simplebus/ToAXI4.scala:146:14
  output [31:0] io_out_ar_bits_addr,	// src/main/scala/bus/simplebus/ToAXI4.scala:146:14
  output [7:0]  io_out_ar_bits_len,	// src/main/scala/bus/simplebus/ToAXI4.scala:146:14
  input         io_out_r_valid,	// src/main/scala/bus/simplebus/ToAXI4.scala:146:14
  input  [63:0] io_out_r_bits_data,	// src/main/scala/bus/simplebus/ToAXI4.scala:146:14
  input         io_out_r_bits_last	// src/main/scala/bus/simplebus/ToAXI4.scala:146:14
);

  wire       io_out_w_valid_0;	// src/main/scala/bus/simplebus/SimpleBus.scala:103:27, src/main/scala/bus/simplebus/ToAXI4.scala:194:31
  wire       io_out_aw_valid_0;	// src/main/scala/bus/simplebus/SimpleBus.scala:103:27, src/main/scala/bus/simplebus/ToAXI4.scala:193:31
  wire [7:0] io_out_ar_bits_len_0 = {5'h0, {3{io_in_req_bits_cmd[1]}}};	// src/main/scala/bus/simplebus/SimpleBus.scala:75:22, src/main/scala/bus/simplebus/ToAXI4.scala:169:{24,30}
  wire       wlast = io_in_req_bits_cmd == 4'h7 | io_in_req_bits_cmd == 4'h1;	// src/main/scala/bus/simplebus/SimpleBus.scala:77:29, :78:27, src/main/scala/bus/simplebus/ToAXI4.scala:177:54
  wire       _wSend_T = io_out_aw_ready & io_out_aw_valid_0;	// src/main/scala/bus/simplebus/SimpleBus.scala:103:27, src/main/scala/bus/simplebus/ToAXI4.scala:193:31, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  reg        awAck;	// src/main/scala/utils/StopWatch.scala:24:20
  wire       _wSend_T_1 = io_out_w_ready & io_out_w_valid_0;	// src/main/scala/bus/simplebus/SimpleBus.scala:103:27, src/main/scala/bus/simplebus/ToAXI4.scala:194:31, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  reg        wAck;	// src/main/scala/utils/StopWatch.scala:24:20
  wire       wSend = _wSend_T & _wSend_T_1 & wlast | awAck & wAck;	// src/main/scala/bus/simplebus/ToAXI4.scala:177:54, :189:{25,39,49,59}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/utils/StopWatch.scala:24:20
  reg        wen;	// src/main/scala/bus/simplebus/ToAXI4.scala:190:22
  assign io_out_aw_valid_0 = io_in_req_valid & io_in_req_bits_cmd[0] & ~awAck;	// src/main/scala/bus/simplebus/SimpleBus.scala:74:22, :103:27, src/main/scala/bus/simplebus/ToAXI4.scala:193:{31,34}, src/main/scala/utils/StopWatch.scala:24:20
  assign io_out_w_valid_0 = io_in_req_valid & io_in_req_bits_cmd[0] & ~wAck;	// src/main/scala/bus/simplebus/SimpleBus.scala:74:22, :103:27, src/main/scala/bus/simplebus/ToAXI4.scala:194:{31,34}, src/main/scala/utils/StopWatch.scala:24:20
  wire       io_in_req_ready_0 =
    io_in_req_bits_cmd[0] ? ~wAck & io_out_w_ready : io_out_ar_ready;	// src/main/scala/bus/simplebus/SimpleBus.scala:74:22, src/main/scala/bus/simplebus/ToAXI4.scala:194:34, :195:{24,55}, src/main/scala/utils/StopWatch.scala:24:20
  always @(posedge clock) begin	// src/main/scala/bus/simplebus/ToAXI4.scala:145:7
    if (reset) begin	// src/main/scala/bus/simplebus/ToAXI4.scala:145:7
      awAck <= 1'h0;	// src/main/scala/bus/simplebus/ToAXI4.scala:145:7, src/main/scala/utils/StopWatch.scala:24:20
      wAck <= 1'h0;	// src/main/scala/bus/simplebus/ToAXI4.scala:145:7, src/main/scala/utils/StopWatch.scala:24:20
    end
    else begin	// src/main/scala/bus/simplebus/ToAXI4.scala:145:7
      awAck <= ~wSend & (_wSend_T | awAck);	// src/main/scala/bus/simplebus/ToAXI4.scala:189:49, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/utils/StopWatch.scala:24:20, :30:{20,24}, :31:{19,23}
      wAck <= ~wSend & (_wSend_T_1 & wlast | wAck);	// src/main/scala/bus/simplebus/ToAXI4.scala:177:54, :188:39, :189:49, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/utils/StopWatch.scala:24:20, :30:{20,24}, :31:{19,23}
    end
    if (io_in_req_ready_0 & io_in_req_valid)	// src/main/scala/bus/simplebus/ToAXI4.scala:195:24, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      wen <= io_in_req_bits_cmd[0];	// src/main/scala/bus/simplebus/SimpleBus.scala:74:22, src/main/scala/bus/simplebus/ToAXI4.scala:190:22
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/bus/simplebus/ToAXI4.scala:145:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/bus/simplebus/ToAXI4.scala:145:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/bus/simplebus/ToAXI4.scala:145:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/bus/simplebus/ToAXI4.scala:145:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/bus/simplebus/ToAXI4.scala:145:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/bus/simplebus/ToAXI4.scala:145:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/bus/simplebus/ToAXI4.scala:145:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/bus/simplebus/ToAXI4.scala:145:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/bus/simplebus/ToAXI4.scala:145:7
        awAck = _RANDOM[/*Zero width*/ 1'b0][0];	// src/main/scala/bus/simplebus/ToAXI4.scala:145:7, src/main/scala/utils/StopWatch.scala:24:20
        wAck = _RANDOM[/*Zero width*/ 1'b0][1];	// src/main/scala/bus/simplebus/ToAXI4.scala:145:7, src/main/scala/utils/StopWatch.scala:24:20
        wen = _RANDOM[/*Zero width*/ 1'b0][2];	// src/main/scala/bus/simplebus/ToAXI4.scala:145:7, :190:22, src/main/scala/utils/StopWatch.scala:24:20
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/bus/simplebus/ToAXI4.scala:145:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/bus/simplebus/ToAXI4.scala:145:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_in_req_ready = io_in_req_ready_0;	// src/main/scala/bus/simplebus/ToAXI4.scala:145:7, :195:24
  assign io_in_resp_valid = wen ? io_out_b_valid : io_out_r_valid;	// src/main/scala/bus/simplebus/ToAXI4.scala:145:7, :190:22, :199:25
  assign io_in_resp_bits_cmd = {1'h0, io_out_r_bits_last ? 3'h6 : 3'h0};	// src/main/scala/bus/simplebus/ToAXI4.scala:145:7, :184:{22,28}
  assign io_in_resp_bits_rdata = io_out_r_bits_data;	// src/main/scala/bus/simplebus/ToAXI4.scala:145:7
  assign io_out_aw_valid = io_out_aw_valid_0;	// src/main/scala/bus/simplebus/SimpleBus.scala:103:27, src/main/scala/bus/simplebus/ToAXI4.scala:145:7, :193:31
  assign io_out_aw_bits_addr = io_in_req_bits_addr;	// src/main/scala/bus/simplebus/ToAXI4.scala:145:7
  assign io_out_aw_bits_len = io_out_ar_bits_len_0;	// src/main/scala/bus/simplebus/ToAXI4.scala:145:7, :169:24
  assign io_out_w_valid = io_out_w_valid_0;	// src/main/scala/bus/simplebus/SimpleBus.scala:103:27, src/main/scala/bus/simplebus/ToAXI4.scala:145:7, :194:31
  assign io_out_w_bits_data = io_in_req_bits_wdata;	// src/main/scala/bus/simplebus/ToAXI4.scala:145:7
  assign io_out_w_bits_last = wlast;	// src/main/scala/bus/simplebus/ToAXI4.scala:145:7, :177:54
  assign io_out_ar_valid =
    io_in_req_valid & ~(io_in_req_bits_cmd[0]) & ~(io_in_req_bits_cmd[3]);	// src/main/scala/bus/simplebus/SimpleBus.scala:73:{18,26,29,33}, :74:22, :104:27, src/main/scala/bus/simplebus/ToAXI4.scala:145:7
  assign io_out_ar_bits_addr = io_in_req_bits_addr;	// src/main/scala/bus/simplebus/ToAXI4.scala:145:7
  assign io_out_ar_bits_len = io_out_ar_bits_len_0;	// src/main/scala/bus/simplebus/ToAXI4.scala:145:7, :169:24
endmodule

