// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module SRAMTemplate(	// src/main/scala/utils/SRAMTemplate.scala:68:7
  input         clock,	// src/main/scala/utils/SRAMTemplate.scala:68:7
                reset,	// src/main/scala/utils/SRAMTemplate.scala:68:7
  output        io_r_req_ready,	// src/main/scala/utils/SRAMTemplate.scala:70:14
  input         io_r_req_valid,	// src/main/scala/utils/SRAMTemplate.scala:70:14
  input  [8:0]  io_r_req_bits_setIdx,	// src/main/scala/utils/SRAMTemplate.scala:70:14
  output [27:0] io_r_resp_data_0_tag,	// src/main/scala/utils/SRAMTemplate.scala:70:14
  output [1:0]  io_r_resp_data_0__type,	// src/main/scala/utils/SRAMTemplate.scala:70:14
  output [38:0] io_r_resp_data_0_target,	// src/main/scala/utils/SRAMTemplate.scala:70:14
  output [2:0]  io_r_resp_data_0_brIdx,	// src/main/scala/utils/SRAMTemplate.scala:70:14
  output        io_r_resp_data_0_valid,	// src/main/scala/utils/SRAMTemplate.scala:70:14
  input         io_w_req_valid,	// src/main/scala/utils/SRAMTemplate.scala:70:14
  input  [8:0]  io_w_req_bits_setIdx,	// src/main/scala/utils/SRAMTemplate.scala:70:14
  input  [27:0] io_w_req_bits_data_tag,	// src/main/scala/utils/SRAMTemplate.scala:70:14
  input  [1:0]  io_w_req_bits_data__type,	// src/main/scala/utils/SRAMTemplate.scala:70:14
  input  [38:0] io_w_req_bits_data_target,	// src/main/scala/utils/SRAMTemplate.scala:70:14
  input  [2:0]  io_w_req_bits_data_brIdx	// src/main/scala/utils/SRAMTemplate.scala:70:14
);

  wire [8:0]  setIdx;	// src/main/scala/utils/SRAMTemplate.scala:91:19
  wire        realRen;	// src/main/scala/utils/SRAMTemplate.scala:89:38
  wire        wen;	// src/main/scala/utils/SRAMTemplate.scala:88:52
  wire [72:0] _array_0_ext_RW0_rdata;	// src/main/scala/utils/SRAMTemplate.scala:76:26
  reg         _resetState;	// src/main/scala/utils/SRAMTemplate.scala:80:30
  reg  [8:0]  _resetSet;	// src/main/scala/chisel3/util/Counter.scala:61:40
  assign wen = io_w_req_valid | _resetState;	// src/main/scala/utils/SRAMTemplate.scala:80:30, :88:52
  assign realRen = io_r_req_valid & ~wen;	// src/main/scala/utils/SRAMTemplate.scala:88:52, :89:{38,41}
  assign setIdx = _resetState ? _resetSet : io_w_req_bits_setIdx;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/utils/SRAMTemplate.scala:80:30, :91:19
  reg         rdata_REG;	// src/main/scala/utils/Hold.scala:28:106
  reg  [72:0] rdata_r_0;	// src/main/scala/utils/Hold.scala:23:65
  wire [72:0] _rdata_T_0 = rdata_REG ? _array_0_ext_RW0_rdata : rdata_r_0;	// src/main/scala/utils/Hold.scala:23:{48,65}, :28:106, src/main/scala/utils/SRAMTemplate.scala:76:26
  always @(posedge clock) begin	// src/main/scala/utils/SRAMTemplate.scala:68:7
    if (reset) begin	// src/main/scala/utils/SRAMTemplate.scala:68:7
      _resetState <= 1'h1;	// src/main/scala/utils/SRAMTemplate.scala:80:30
      _resetSet <= 9'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
      rdata_r_0 <= 73'h0;	// src/main/scala/utils/Hold.scala:23:65, src/main/scala/utils/SRAMTemplate.scala:92:22
    end
    else begin	// src/main/scala/utils/SRAMTemplate.scala:68:7
      _resetState <= ~(_resetState & (&_resetSet)) & _resetState;	// src/main/scala/chisel3/util/Counter.scala:61:40, :73:24, :117:24, :118:{16,23}, src/main/scala/utils/SRAMTemplate.scala:80:30, :82:{24,38}
      if (_resetState)	// src/main/scala/utils/SRAMTemplate.scala:80:30
        _resetSet <= _resetSet + 9'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (rdata_REG)	// src/main/scala/utils/Hold.scala:28:106
        rdata_r_0 <= _array_0_ext_RW0_rdata;	// src/main/scala/utils/Hold.scala:23:65, src/main/scala/utils/SRAMTemplate.scala:76:26
    end
    rdata_REG <= realRen;	// src/main/scala/utils/Hold.scala:28:106, src/main/scala/utils/SRAMTemplate.scala:89:38
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/utils/SRAMTemplate.scala:68:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/utils/SRAMTemplate.scala:68:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/utils/SRAMTemplate.scala:68:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/utils/SRAMTemplate.scala:68:7
      automatic logic [31:0] _RANDOM[0:2];	// src/main/scala/utils/SRAMTemplate.scala:68:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/utils/SRAMTemplate.scala:68:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/utils/SRAMTemplate.scala:68:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/utils/SRAMTemplate.scala:68:7
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/utils/SRAMTemplate.scala:68:7
        end	// src/main/scala/utils/SRAMTemplate.scala:68:7
        _resetState = _RANDOM[2'h0][0];	// src/main/scala/utils/SRAMTemplate.scala:68:7, :80:30
        _resetSet = _RANDOM[2'h0][9:1];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/utils/SRAMTemplate.scala:68:7, :80:30
        rdata_REG = _RANDOM[2'h0][10];	// src/main/scala/utils/Hold.scala:28:106, src/main/scala/utils/SRAMTemplate.scala:68:7, :80:30
        rdata_r_0 = {_RANDOM[2'h0][31:11], _RANDOM[2'h1], _RANDOM[2'h2][19:0]};	// src/main/scala/utils/Hold.scala:23:65, src/main/scala/utils/SRAMTemplate.scala:68:7, :80:30
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/utils/SRAMTemplate.scala:68:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/utils/SRAMTemplate.scala:68:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  array_0_512x73 array_0_ext (	// src/main/scala/utils/SRAMTemplate.scala:76:26
    .RW0_addr  (wen ? setIdx : io_r_req_bits_setIdx),	// src/main/scala/utils/SRAMTemplate.scala:76:26, :88:52, :91:19
    .RW0_en    (realRen | wen),	// src/main/scala/utils/SRAMTemplate.scala:76:26, :88:52, :89:38
    .RW0_clk   (clock),
    .RW0_wmode (wen),	// src/main/scala/utils/SRAMTemplate.scala:88:52
    .RW0_wdata
      (_resetState
         ? 73'h0
         : {io_w_req_bits_data_tag,
            io_w_req_bits_data__type,
            io_w_req_bits_data_target,
            io_w_req_bits_data_brIdx,
            1'h1}),	// src/main/scala/utils/SRAMTemplate.scala:80:30, :92:{22,78}
    .RW0_rdata (_array_0_ext_RW0_rdata)
  );	// src/main/scala/utils/SRAMTemplate.scala:76:26
  assign io_r_req_ready = ~_resetState & ~wen;	// src/main/scala/utils/SRAMTemplate.scala:68:7, :80:30, :88:52, :89:41, :101:{21,33}
  assign io_r_resp_data_0_tag = _rdata_T_0[72:45];	// src/main/scala/utils/Hold.scala:23:48, src/main/scala/utils/SRAMTemplate.scala:68:7, :98:78
  assign io_r_resp_data_0__type = _rdata_T_0[44:43];	// src/main/scala/utils/Hold.scala:23:48, src/main/scala/utils/SRAMTemplate.scala:68:7, :98:78
  assign io_r_resp_data_0_target = _rdata_T_0[42:4];	// src/main/scala/utils/Hold.scala:23:48, src/main/scala/utils/SRAMTemplate.scala:68:7, :98:78
  assign io_r_resp_data_0_brIdx = _rdata_T_0[3:1];	// src/main/scala/utils/Hold.scala:23:48, src/main/scala/utils/SRAMTemplate.scala:68:7, :98:78
  assign io_r_resp_data_0_valid = _rdata_T_0[0];	// src/main/scala/utils/Hold.scala:23:48, src/main/scala/utils/SRAMTemplate.scala:68:7, :98:78
endmodule

