// Generated by CIRCT firtool-1.135.0
module WBU(	// src/main/scala/nutcore/backend/seq/WBU.scala:25:7
  input          io_in_valid,	// src/main/scala/nutcore/backend/seq/WBU.scala:26:14
  input  [63:0]  io_in_bits_decode_cf_instr,	// src/main/scala/nutcore/backend/seq/WBU.scala:26:14
  input  [38:0]  io_in_bits_decode_cf_pc,	// src/main/scala/nutcore/backend/seq/WBU.scala:26:14
                 io_in_bits_decode_cf_redirect_target,	// src/main/scala/nutcore/backend/seq/WBU.scala:26:14
  input          io_in_bits_decode_cf_redirect_valid,	// src/main/scala/nutcore/backend/seq/WBU.scala:26:14
  input  [2:0]   io_in_bits_decode_ctrl_fuType,	// src/main/scala/nutcore/backend/seq/WBU.scala:26:14
  input          io_in_bits_decode_ctrl_rfWen,	// src/main/scala/nutcore/backend/seq/WBU.scala:26:14
  input  [4:0]   io_in_bits_decode_ctrl_rfDest,	// src/main/scala/nutcore/backend/seq/WBU.scala:26:14
  input          io_in_bits_isMMIO,	// src/main/scala/nutcore/backend/seq/WBU.scala:26:14
  input  [63:0]  io_in_bits_commits_0,	// src/main/scala/nutcore/backend/seq/WBU.scala:26:14
                 io_in_bits_commits_1,	// src/main/scala/nutcore/backend/seq/WBU.scala:26:14
                 io_in_bits_commits_2,	// src/main/scala/nutcore/backend/seq/WBU.scala:26:14
                 io_in_bits_commits_3,	// src/main/scala/nutcore/backend/seq/WBU.scala:26:14
  output         io_wb_rfWen,	// src/main/scala/nutcore/backend/seq/WBU.scala:26:14
  output [4:0]   io_wb_rfDest,	// src/main/scala/nutcore/backend/seq/WBU.scala:26:14
  output [63:0]  io_wb_rfData,	// src/main/scala/nutcore/backend/seq/WBU.scala:26:14
  output [38:0]  io_redirect_target,	// src/main/scala/nutcore/backend/seq/WBU.scala:26:14
  output         io_redirect_valid,	// src/main/scala/nutcore/backend/seq/WBU.scala:26:14
  output [253:0] gatewayIn_packed_4_bore,	// difftest/src/main/scala/common/WiringControl.scala:30:55
  output         io_in_valid__bore,
                 falseWire__bore
);

  wire             difftest_commit_rfwen;	// src/main/scala/nutcore/backend/seq/WBU.scala:56:43
  wire             difftest_commit_isRVC;	// src/main/scala/nutcore/backend/seq/WBU.scala:55:62
  wire [31:0]      difftest_commit_instr;	// src/main/scala/nutcore/backend/seq/WBU.scala:53:28
  wire [24:0]      _difftest_commit_pc_T;	// src/main/scala/utils/BitUtils.scala:42:46
  wire             falseWire = 1'h0;	// src/main/scala/nutcore/backend/seq/WBU.scala:43:27
  wire             io_wb_rfWen_0 = io_in_bits_decode_ctrl_rfWen & io_in_valid;	// src/main/scala/nutcore/backend/seq/WBU.scala:32:47
  wire [7:0][63:0] _GEN =
    {{io_in_bits_commits_0},
     {io_in_bits_commits_0},
     {io_in_bits_commits_0},
     {64'h0},
     {io_in_bits_commits_3},
     {io_in_bits_commits_2},
     {io_in_bits_commits_1},
     {io_in_bits_commits_0}};	// src/main/scala/nutcore/backend/seq/WBU.scala:26:14, :34:16
  assign _difftest_commit_pc_T = {25{io_in_bits_decode_cf_pc[38]}};	// src/main/scala/utils/BitUtils.scala:41:20, :42:46
  assign difftest_commit_instr = io_in_bits_decode_cf_instr[31:0];	// src/main/scala/nutcore/backend/seq/WBU.scala:53:28
  assign difftest_commit_isRVC = io_in_bits_decode_cf_instr[1:0] != 2'h3;	// src/main/scala/nutcore/backend/seq/WBU.scala:55:{57,62}
  assign difftest_commit_rfwen = io_wb_rfWen_0 & (|io_in_bits_decode_ctrl_rfDest);	// src/main/scala/nutcore/backend/seq/WBU.scala:32:47, :56:{43,59}
  assign io_wb_rfWen = io_wb_rfWen_0;	// src/main/scala/nutcore/backend/seq/WBU.scala:25:7, :32:47
  assign io_wb_rfDest = io_in_bits_decode_ctrl_rfDest;	// src/main/scala/nutcore/backend/seq/WBU.scala:25:7
  assign io_wb_rfData = _GEN[io_in_bits_decode_ctrl_fuType];	// src/main/scala/nutcore/backend/seq/WBU.scala:25:7, :34:16
  assign io_redirect_target = io_in_bits_decode_cf_redirect_target;	// src/main/scala/nutcore/backend/seq/WBU.scala:25:7
  assign io_redirect_valid = io_in_bits_decode_cf_redirect_valid & io_in_valid;	// src/main/scala/nutcore/backend/seq/WBU.scala:25:7, :39:60
  assign gatewayIn_packed_4_bore =
    {io_in_valid,
     io_in_bits_isMMIO,
     difftest_commit_isRVC,
     difftest_commit_rfwen,
     3'h0,
     io_in_bits_decode_ctrl_rfDest,
     3'h0,
     io_in_bits_decode_ctrl_rfDest,
     80'h0,
     _difftest_commit_pc_T,
     io_in_bits_decode_cf_pc,
     difftest_commit_instr,
     58'h0};	// difftest/src/main/scala/Gateway.scala:177:63, src/main/scala/nutcore/backend/seq/WBU.scala:25:7, :53:28, :55:62, :56:43, src/main/scala/utils/BitUtils.scala:42:46
  assign io_in_valid__bore = io_in_valid;	// src/main/scala/nutcore/backend/seq/WBU.scala:25:7
  assign falseWire__bore = falseWire;	// src/main/scala/nutcore/backend/seq/WBU.scala:25:7, :43:27
endmodule

