`timescale 1ns/1ps

// Full-shape sampled VGG-16 conv1_1 GEMM test.
//
// VGG conv1_1 shape:
//   Input feature map = 224 x 224 x 3
//   Weight            = 3 x 3 x 3 x 64
//   GEMM A(im2col)    = 50176 x 27
//   GEMM B(weight)    = 27 x 64
//   GEMM C(output)    = 50176 x 64
//
// Exhaustively simulating every 2x2 C tile would require:
//   M tiles = 50176 / 2 = 25088
//   N tiles = 64 / 2 = 32
//   K chunks = ceil(27 / 4) = 7
//   total chunk runs = 25088 * 32 * 7 = 5,619,712
//
// That is too slow for a normal RTL regression, so this TB samples M/N tiles
// across the full address range while preserving the real layer dimensions.
// Activation and weight values are generated by deterministic functions from
// global row/column/k indices.  Each fiber has at most one nonzero per K chunk
// so every chunk stays within LANES=4.

module tb_trip_vgg_conv1_1_sampled;

    // 0: fast sampled regression.
    // 1: exhaustive full C matrix check.  Full mode is intentionally quiet:
    //    it prints progress and failures, but not every passing C element.
    parameter FULL_RUN = 0;
    parameter PROGRESS_STEP_TILES = 4096;

    // Hardware tile parameters.
    localparam NUM_ROWS       = 2;
    localparam NUM_COLS       = 2;
    localparam K_BITS         = 4;
    localparam LANES          = 4;
    localparam DATA_WIDTH     = 16;
    localparam ID_WIDTH       = 4;
    localparam ADDR_W_A       = 1;
    localparam ADDR_W_B       = 1;
    localparam CNT_W          = 3;
    localparam PRODUCT_WIDTH  = DATA_WIDTH * 2;
    localparam ACC_WIDTH      = PRODUCT_WIDTH + CNT_W;
    localparam TILE_ACC_WIDTH = ACC_WIDTH + 8;
    localparam NUM_OUTPUTS    = NUM_ROWS * NUM_COLS;
    localparam VAL_W          = K_BITS * DATA_WIDTH;

    // VGG conv1_1 full GEMM shape.
    localparam IFMAP_H    = 224;
    localparam IFMAP_W    = 224;
    localparam CIN        = 3;
    localparam COUT       = 64;
    localparam KERNEL_R   = 3;
    localparam KERNEL_S   = 3;
    localparam OUT_POS    = IFMAP_H * IFMAP_W;                // 50176
    localparam K_TOTAL    = KERNEL_R * KERNEL_S * CIN;        // 27
    localparam K_CHUNKS   = (K_TOTAL + K_BITS - 1) / K_BITS;  // 7
    localparam K_PADDED   = K_CHUNKS * K_BITS;                // 28
    localparam M_TILES    = OUT_POS / NUM_ROWS;               // 25088
    localparam N_TILES    = COUT / NUM_COLS;                  // 32

    // Keep runtime practical while sampling beginning, middle, and end.
    localparam SAMPLE_M_COUNT = 8;
    localparam SAMPLE_N_COUNT = 8;

    reg clk, reset, start_i, clear_accum_i;
    reg a_wr_en_i, b_wr_en_i;
    reg [ADDR_W_A-1:0] a_wr_addr_i;
    reg [ADDR_W_B-1:0] b_wr_addr_i;
    reg [ID_WIDTH-1:0] a_wr_id_i, b_wr_id_i;
    reg [K_BITS-1:0]   a_wr_mask_i, b_wr_mask_i;
    reg [VAL_W-1:0]    a_wr_values_i, b_wr_values_i;

    wire busy_o, done_o, overflow_o, overflow_seen_o;
    wire [NUM_OUTPUTS-1:0]                tile_valid_o;
    wire [NUM_OUTPUTS*TILE_ACC_WIDTH-1:0] tile_result_o;
    wire [NUM_OUTPUTS-1:0]                partial_valid_o;
    wire [NUM_OUTPUTS*ACC_WIDTH-1:0]      partial_result_o;
    wire [CNT_W-1:0]                      match_count_o;
    wire [7:0]                            chunk_count_o;

    trip_tile_compute_engine #(
        .NUM_ROWS       (NUM_ROWS),
        .NUM_COLS       (NUM_COLS),
        .K_BITS         (K_BITS),
        .LANES          (LANES),
        .DATA_WIDTH     (DATA_WIDTH),
        .ID_WIDTH       (ID_WIDTH),
        .TILE_ACC_WIDTH (TILE_ACC_WIDTH)
    ) dut (
        .clk              (clk),
        .reset            (reset),
        .a_wr_en_i        (a_wr_en_i),
        .a_wr_addr_i      (a_wr_addr_i),
        .a_wr_id_i        (a_wr_id_i),
        .a_wr_mask_i      (a_wr_mask_i),
        .a_wr_values_i    (a_wr_values_i),
        .b_wr_en_i        (b_wr_en_i),
        .b_wr_addr_i      (b_wr_addr_i),
        .b_wr_id_i        (b_wr_id_i),
        .b_wr_mask_i      (b_wr_mask_i),
        .b_wr_values_i    (b_wr_values_i),
        .start_i          (start_i),
        .clear_accum_i    (clear_accum_i),
        .busy_o           (busy_o),
        .done_o           (done_o),
        .partial_valid_o  (partial_valid_o),
        .partial_result_o (partial_result_o),
        .match_count_o    (match_count_o),
        .overflow_o       (overflow_o),
        .overflow_seen_o  (overflow_seen_o),
        .tile_valid_o     (tile_valid_o),
        .tile_result_o    (tile_result_o),
        .chunk_count_o    (chunk_count_o)
    );

    initial clk = 1'b0;
    always #5 clk = ~clk;

    integer pass_cnt = 0;
    integer fail_cnt = 0;

    function integer sample_m_tile;
        input integer idx;
        begin
            case (idx)
                0: sample_m_tile = 0;
                1: sample_m_tile = 1;
                2: sample_m_tile = 17;
                3: sample_m_tile = 257;
                4: sample_m_tile = 1024;
                5: sample_m_tile = 8191;
                6: sample_m_tile = 16384;
                default: sample_m_tile = M_TILES - 1;
            endcase
        end
    endfunction

    function integer sample_n_tile;
        input integer idx;
        begin
            case (idx)
                0: sample_n_tile = 0;
                1: sample_n_tile = 1;
                2: sample_n_tile = 3;
                3: sample_n_tile = 7;
                4: sample_n_tile = 11;
                5: sample_n_tile = 16;
                6: sample_n_tile = 23;
                default: sample_n_tile = N_TILES - 1;
            endcase
        end
    endfunction

    function [DATA_WIDTH-1:0] act_at;
        input integer row;
        input integer k;
        integer kc, local_k, selected_k;
        begin
            if (k >= K_TOTAL) begin
                act_at = 0;
            end else begin
                kc = k / K_BITS;
                local_k = k & (K_BITS - 1);
                selected_k = (row + 2*kc) & (K_BITS - 1);
                if (local_k == selected_k)
                    act_at = ((row + 3*kc) % 13) + 1;
                else
                    act_at = 0;
            end
        end
    endfunction

    function [DATA_WIDTH-1:0] weight_at;
        input integer k;
        input integer col;
        integer kc, local_k, selected_k;
        begin
            if (k >= K_TOTAL) begin
                weight_at = 0;
            end else begin
                kc = k / K_BITS;
                local_k = k & (K_BITS - 1);
                selected_k = (col + kc) & (K_BITS - 1);
                if (local_k == selected_k)
                    weight_at = ((5*col + kc) % 17) + 1;
                else
                    weight_at = 0;
            end
        end
    endfunction

    function [K_BITS-1:0] a_mask_for;
        input integer row;
        input integer kc;
        integer k;
        begin
            a_mask_for = {K_BITS{1'b0}};
            for (k = 0; k < K_BITS; k = k + 1)
                if (act_at(row, kc*K_BITS + k) != 0)
                    a_mask_for[k] = 1'b1;
        end
    endfunction

    function [VAL_W-1:0] a_vals_for;
        input integer row;
        input integer kc;
        integer k;
        reg [VAL_W-1:0] v;
        begin
            v = {VAL_W{1'b0}};
            for (k = 0; k < K_BITS; k = k + 1)
                v[k*DATA_WIDTH +: DATA_WIDTH] = act_at(row, kc*K_BITS + k);
            a_vals_for = v;
        end
    endfunction

    function [K_BITS-1:0] b_mask_for;
        input integer col;
        input integer kc;
        integer k;
        begin
            b_mask_for = {K_BITS{1'b0}};
            for (k = 0; k < K_BITS; k = k + 1)
                if (weight_at(kc*K_BITS + k, col) != 0)
                    b_mask_for[k] = 1'b1;
        end
    endfunction

    function [VAL_W-1:0] b_vals_for;
        input integer col;
        input integer kc;
        integer k;
        reg [VAL_W-1:0] v;
        begin
            v = {VAL_W{1'b0}};
            for (k = 0; k < K_BITS; k = k + 1)
                v[k*DATA_WIDTH +: DATA_WIDTH] = weight_at(kc*K_BITS + k, col);
            b_vals_for = v;
        end
    endfunction

    function integer golden_at;
        input integer row;
        input integer col;
        integer k;
        begin
            golden_at = 0;
            for (k = 0; k < K_TOTAL; k = k + 1)
                golden_at = golden_at + act_at(row, k) * weight_at(k, col);
        end
    endfunction

    function [TILE_ACC_WIDTH-1:0] tile_result_at;
        input integer idx;
        begin
            tile_result_at = tile_result_o[idx*TILE_ACC_WIDTH +: TILE_ACC_WIDTH];
        end
    endfunction

    task check_int;
        input [255:0] label;
        input integer got;
        input integer exp;
        begin
            if (got === exp) begin
                if (!FULL_RUN)
                    $display("PASS  %s (%0d)", label, got);
                pass_cnt = pass_cnt + 1;
            end else begin
                $display("FAIL  %s got=%0d exp=%0d", label, got, exp);
                fail_cnt = fail_cnt + 1;
            end
        end
    endtask

    task check_bit;
        input [255:0] label;
        input got;
        input exp;
        begin
            if (got === exp) begin
                if (!FULL_RUN)
                    $display("PASS  %s", label);
                pass_cnt = pass_cnt + 1;
            end else begin
                $display("FAIL  %s got=%0b exp=%0b", label, got, exp);
                fail_cnt = fail_cnt + 1;
            end
        end
    endtask

    task write_a_fiber;
        input [ADDR_W_A-1:0] addr;
        input [ID_WIDTH-1:0] id;
        input [K_BITS-1:0]   mask;
        input [VAL_W-1:0]    values;
        begin
            @(negedge clk);
            a_wr_en_i = 1'b1;
            a_wr_addr_i = addr;
            a_wr_id_i = id;
            a_wr_mask_i = mask;
            a_wr_values_i = values;
            @(posedge clk); #1;
            a_wr_en_i = 1'b0;
        end
    endtask

    task write_b_fiber;
        input [ADDR_W_B-1:0] addr;
        input [ID_WIDTH-1:0] id;
        input [K_BITS-1:0]   mask;
        input [VAL_W-1:0]    values;
        begin
            @(negedge clk);
            b_wr_en_i = 1'b1;
            b_wr_addr_i = addr;
            b_wr_id_i = id;
            b_wr_mask_i = mask;
            b_wr_values_i = values;
            @(posedge clk); #1;
            b_wr_en_i = 1'b0;
        end
    endtask

    task run_tile;
        input integer mt;
        input integer nt;
        integer kc, r, c;
        begin
            for (kc = 0; kc < K_CHUNKS; kc = kc + 1) begin
                for (r = 0; r < NUM_ROWS; r = r + 1)
                    write_a_fiber(r[ADDR_W_A-1:0], r[ID_WIDTH-1:0],
                                  a_mask_for(mt*NUM_ROWS + r, kc),
                                  a_vals_for(mt*NUM_ROWS + r, kc));

                for (c = 0; c < NUM_COLS; c = c + 1)
                    write_b_fiber(c[ADDR_W_B-1:0], c[ID_WIDTH-1:0],
                                  b_mask_for(nt*NUM_COLS + c, kc),
                                  b_vals_for(nt*NUM_COLS + c, kc));

                @(negedge clk);
                start_i       = 1'b1;
                clear_accum_i = (kc == 0) ? 1'b1 : 1'b0;
                @(posedge clk); #1;
                start_i       = 1'b0;
                clear_accum_i = 1'b0;
                wait (done_o === 1'b1);
                #1;
            end
        end
    endtask

    task check_tile;
        input integer mt;
        input integer nt;
        integer r, c, idx, row, col, got, exp;
        begin
            check_bit("conv1_1 sampled overflow_seen=0", overflow_seen_o, 1'b0);
            check_int("conv1_1 sampled chunk_count", chunk_count_o, K_CHUNKS);

            for (r = 0; r < NUM_ROWS; r = r + 1) begin
                for (c = 0; c < NUM_COLS; c = c + 1) begin
                    idx = r * NUM_COLS + c;
                    row = mt*NUM_ROWS + r;
                    col = nt*NUM_COLS + c;
                    got = tile_result_at(idx);
                    exp = golden_at(row, col);
                    check_int("conv1_1 sampled C element", got, exp);
                end
            end
        end
    endtask

    task reset_dut;
        begin
            reset         = 1'b1;
            start_i       = 1'b0;
            clear_accum_i = 1'b0;
            a_wr_en_i     = 1'b0;
            b_wr_en_i     = 1'b0;
            a_wr_addr_i   = {ADDR_W_A{1'b0}};
            b_wr_addr_i   = {ADDR_W_B{1'b0}};
            a_wr_id_i     = {ID_WIDTH{1'b0}};
            b_wr_id_i     = {ID_WIDTH{1'b0}};
            a_wr_mask_i   = {K_BITS{1'b0}};
            b_wr_mask_i   = {K_BITS{1'b0}};
            a_wr_values_i = {VAL_W{1'b0}};
            b_wr_values_i = {VAL_W{1'b0}};
            repeat (3) @(posedge clk);
            @(negedge clk);
            reset = 1'b0;
        end
    endtask

    integer mi, ni, mt, nt;
    integer tile_counter;

    initial begin
        reset_dut;
        tile_counter = 0;

        $display("\n--- Full-shape sampled VGG conv1_1 GEMM test ---");
        $display("Input feature map = %0dx%0dx%0d", IFMAP_H, IFMAP_W, CIN);
        $display("Weight = %0dx%0dx%0dx%0d", KERNEL_R, KERNEL_S, CIN, COUT);
        $display("GEMM A = %0d x %0d", OUT_POS, K_TOTAL);
        $display("GEMM B = %0d x %0d", K_TOTAL, COUT);
        $display("GEMM C = %0d x %0d", OUT_POS, COUT);
        $display("Total full run would be %0d M tiles x %0d N tiles x %0d K chunks",
                 M_TILES, N_TILES, K_CHUNKS);

        if (FULL_RUN) begin
            $display("Mode = FULL. Checking all %0d C tiles (%0d C elements).",
                     M_TILES*N_TILES, OUT_POS*COUT);
            for (mt = 0; mt < M_TILES; mt = mt + 1) begin
                for (nt = 0; nt < N_TILES; nt = nt + 1) begin
                    run_tile(mt, nt);
                    check_tile(mt, nt);
                    tile_counter = tile_counter + 1;
                    if ((tile_counter % PROGRESS_STEP_TILES) == 0)
                        $display("PROGRESS full conv1_1: %0d / %0d C tiles checked",
                                 tile_counter, M_TILES*N_TILES);
                end
            end
        end else begin
            $display("Mode = SAMPLED. Checking %0d M tiles x %0d N tiles.",
                     SAMPLE_M_COUNT, SAMPLE_N_COUNT);
            for (mi = 0; mi < SAMPLE_M_COUNT; mi = mi + 1) begin
                mt = sample_m_tile(mi);
                for (ni = 0; ni < SAMPLE_N_COUNT; ni = ni + 1) begin
                    nt = sample_n_tile(ni);
                    run_tile(mt, nt);
                    check_tile(mt, nt);
                    tile_counter = tile_counter + 1;
                end
            end
        end

        $display("\n------------------------------------------");
        $display("Checked C tiles: %0d", tile_counter);
        $display("tb_trip_vgg_conv1_1_sampled: %0d passed, %0d failed", pass_cnt, fail_cnt);
        if (fail_cnt == 0) $display("ALL PASS"); else $display("SOME FAILURES");
        $display("------------------------------------------");
        $finish;
    end

endmodule
